import test from 'node:test';
import assert from 'node:assert/strict';
import { canAccessStewardCenter, createStewardInquiry, exportAppealPackage, issueFinalRuling, saveDecisionDraft, summarizeEvidenceForStewards, validateStewardAuditTrail } from '../dist/index.js';

function fixture() { return createStewardInquiry({ id:'inq-1', raceId:'race-7', openedAt:'2026-06-13T21:00:00Z', openedBy:'steward-1', involvedHorses:[{ horseId:'h1', name:'One', programNumber:'1', officialResultLocked:true }], involvedJockeys:[{ jockeyId:'j1', name:'J One', licenseId:'L1', horseId:'h1' }], evidenceReferences:[{ id:'ev1', kind:'video', uri:'s3://clip', capturedAt:'2026-06-13T21:00:00Z', addedBy:'steward-1', description:'pan replay', hash:'sha256:clip' }], ruleReferences:[{ id:'r1', jurisdiction:'NY', rulebook:'rules', section:'1', citation:'interference', summary:'review interference' }] }); }

test('AI can summarize and draft recommendations but cannot issue official rulings', () => { const inquiry = fixture(); const aiDraft = summarizeEvidenceForStewards(inquiry); assert.equal(aiDraft.aiGenerated, true); assert.equal(aiDraft.officialRuling, false); assert.throws(() => issueFinalRuling(inquiry, { id:'final-ai', issuedBy:'ai-agent', issuedByRole:'read-only-auditor', issuedAt:'2026-06-13T21:10:00Z', decision:'make official', rationale:'bad', penalties:[], officialResultsModified:false, evidenceIds:['ev1'], ruleIds:['r1'] }), /authorized human steward/); assert.equal(inquiry.finalRuling, undefined); });

test('final rulings are human-only and cannot modify official results', () => { const inquiry = fixture(); assert.throws(() => issueFinalRuling(inquiry, { id:'final-1', issuedBy:'steward-1', issuedByRole:'steward', issuedAt:'2026-06-13T21:12:00Z', decision:'no change', rationale:'reviewed', penalties:[], officialResultsModified:true, evidenceIds:['ev1'], ruleIds:['r1'] }), /may not modify official results/); const ruling = issueFinalRuling(inquiry, { id:'final-2', issuedBy:'steward-1', issuedByRole:'steward', issuedAt:'2026-06-13T21:13:00Z', decision:'objection dismissed; results unchanged', rationale:'insufficient impact', penalties:[], officialResultsModified:false, evidenceIds:['ev1'], ruleIds:['r1'] }); assert.equal(ruling.officialResultsModified, false); assert.equal(inquiry.status, 'finalized'); });

test('audit trail is complete across drafts, final ruling, and appeal package', () => { const inquiry = fixture(); saveDecisionDraft(inquiry, { id:'draft-human', authorId:'steward-2', authorRole:'steward', createdAt:'2026-06-13T21:08:00Z', recommendation:'dismiss objection', rationale:'horse maintained path', evidenceIds:['ev1'], ruleIds:['r1'], aiGenerated:false }); issueFinalRuling(inquiry, { id:'final-1', issuedBy:'steward-1', issuedByRole:'steward', issuedAt:'2026-06-13T21:13:00Z', decision:'official ruling recorded without result mutation', rationale:'panel reviewed all evidence', penalties:[], officialResultsModified:false, evidenceIds:['ev1'], ruleIds:['r1'] }); const pkg = exportAppealPackage(inquiry, 'clerk-1'); assert.ok(pkg.contents.auditRecordIds.includes('audit-1')); const validation = validateStewardAuditTrail(inquiry); assert.equal(validation.complete, true); assert.ok(validation.recordCount >= 4); });

test('role-based access separates read, draft, appeal, and finalization duties', () => { assert.equal(canAccessStewardCenter(['read-only-auditor'], 'read'), true); assert.equal(canAccessStewardCenter(['read-only-auditor'], 'draft'), false); assert.equal(canAccessStewardCenter(['compliance-officer'], 'appeal'), true); assert.equal(canAccessStewardCenter(['compliance-officer'], 'finalize'), false); assert.equal(canAccessStewardCenter(['steward'], 'finalize'), true); });
