import { nexusApiBasePath } from '@trackmind/shared';
import type { DomainRouteId } from '@/domain/support';

export function normalizeApiBaseUrl(value: string | undefined): string {
  const baseUrl = (value ?? nexusApiBasePath).trim().replace(/\/+$/, '');
  return baseUrl || nexusApiBasePath;
}

export const API_BASE_URL = normalizeApiBaseUrl(import.meta.env.VITE_TRACKMIND_API_BASE_URL);
export const AGENTS_BASE_URL = (import.meta.env.VITE_TRACKMIND_AGENTS_URL ?? '/agents').replace(/\/+$/, '');

export type ApiAdapterSource = 'live-api' | 'facade-api' | 'documented-stub';

export const apiPaths = {
  dashboard: {
    operations: '/operations/command-center',
    platformHealth: '/platform/health',
    aiControlPlaneRecommendations: '/ai-control-plane/recommendations',
    aiGovernanceWorkspace: '/ai-governance/workspace',
    aiControlPlaneWorkspace: '/ai-control-plane/workspace',
  },
  kpis: { workspace: '/kpis' },
  raceDay: {
    races: '/races',
    raceOffice: '/race-operations/race-office',
    racingCalendar: '/racing-calendar/workspace',
    raceCards: '/race-cards/workspace',
    readiness: '/race-day-readiness/dashboard',
    surface: '/surface-intelligence/workspace',
    trackConfiguration: '/track-configuration/map',
    paddock: '/race-operations/paddock',
    startingGate: '/race-operations/starting-gate',
    startingGateOperations: '/starting-gate-operations/workspace',
    paddockOperations: '/paddock-operations/workspace',
    schedule: '/race-operations/schedule',
  },
  equine: {
    horse: '/equine-intelligence/horses/horse-1',
    horseRegistry: '/horse-registry/workspace',
    trainerManagement: '/trainer-management/workspace',
    jockeyManagement: '/jockey-management/workspace',
    jockeyDashboard: '/jockey-management/dashboard',
    veterinaryOperations: '/veterinary-operations/workspace',
    veterinaryDashboard: '/veterinary-operations/dashboard',
    paddockOperations: '/paddock-operations/workspace',
    paddockDashboard: '/paddock-operations/dashboard',
    stewardOperations: '/steward-operations/workspace',
    stewardDashboard: '/steward-operations/dashboard',
    startingGateOperations: '/starting-gate-operations/workspace',
    startingGateDashboard: '/starting-gate-operations/dashboard',
    surfaceIntelligence: '/surface-intelligence/workspace',
    surfaceDashboard: '/surface-intelligence/dashboard',
    equineWelfare: '/equine-welfare/workspace',
    equineWelfareDashboard: '/equine-welfare/dashboard',
    equineWelfareAuditTrail: '/equine-welfare/audit-trail',
    barnOperations: '/barn-operations/workspace',
    horseProfile: '/horses/horse-1/profile',
    eligibility: '/horses/horse-1/eligibility',
  },
  approvals: { list: '/approvals/requests', durable: '/approvals/durable' },
  incidents: {
    security: '/security-operations/workspace',
    emergency: '/emergency-operations/workspace',
    list: '/incidents',
  },
  compliance: { library: '/compliance/control-library' },
  security: { workspace: '/security-operations/workspace', zonesLive: '/security-operations/zones/live' },
  facilities: { workspace: '/facilities-maintenance/workspace' },
  finance: { ticketing: '/services/finance/ticketing', workspace: '/finance/workspace', dashboard: '/finance/dashboard', auditTrail: '/finance/audit-trail' },
  federation: { workspace: '/federation/workspace', kpiAggregation: '/federation/kpi-aggregation', industryIntelligence: '/industry-intelligence/workspace', industryDashboard: '/industry-intelligence/dashboard', industryBenchmarks: '/industry-intelligence/benchmarks', industryTrends: '/industry-intelligence/trends', federationIntelligence: '/federation-intelligence/workspace' },
  dataHub: { workspace: '/racing-data' },
  audit: { events: '/audit/events', search: '/audit/search' },
  admin: {
    platformHealth: '/platform/health',
    foundation: '/platform/foundation',
    environment: '/platform/environment',
    featureFlags: '/platform/feature-flags',
    modules: '/platform/modules',
    identity: '/identity/workspace',
    domainOwnership: '/platform/domain-ownership',
    lineageValidation: '/platform/governance-lineage/validation',
    readinessScorecards: '/platform/readiness-scorecards',
    executiveScorecard: '/platform/executive-scorecard',
    workflowHealth: '/platform/workflow-health',
    maturityReview: '/platform/maturity-review',
    governedArtifacts: '/platform/governed-artifacts',
  },
  analytics: { workspace: '/analytics/workspace', knowledgeGraph: '/knowledge-graph/workspace', knowledgeGraphSearch: '/knowledge-graph/search', reporting: '/reporting/workspace' },
  fanExperience: { workspace: '/fan-experience/workspace', dashboard: '/fan-experience/dashboard', auditTrail: '/fan-experience/audit-trail' },
  notifications: { inbox: '/notifications/inbox' },
  settings: {
    policy: '/ai-control-plane/policy',
    workspace: '/ai-control-plane/workspace',
    models: '/ai-control-plane/models',
    blockedActions: '/ai-control-plane/blocked-actions',
    events: '/ai-control-plane/events',
    features: '/ai-control-plane/features',
    modelRegistry: '/ai-governance/model-registry',
  },
  stewarding: {
    inquiries: '/stewarding/inquiries',
    workspace: '/steward-operations/workspace',
    dashboard: '/steward-operations/dashboard',
    auditTrail: '/steward-operations/audit-trail',
  },
  workforce: { workspace: '/workforce-operations/workspace' },
  digitalTwin: { state: '/digital-twin/state', assets: '/assets' },
  surface: {
    workspace: '/surface-intelligence/workspace',
    measurements: '/track-surface/measurements',
  },
  emergency: { workspace: '/emergency-operations/workspace' },
  events: { stream: '/events/stream' },
  collaboration: {
    threads: '/collaboration/threads',
    activity: '/collaboration/activity',
  },
  search: { global: '/search/global', globalSample: '/search/global?q=horse' },
} as const;

export const commonContextApiPaths = [
  apiPaths.approvals.list,
  apiPaths.audit.events,
  apiPaths.dashboard.aiControlPlaneRecommendations,
  apiPaths.dashboard.aiGovernanceWorkspace,
  apiPaths.dashboard.aiControlPlaneWorkspace,
  apiPaths.kpis.workspace,
] as const;

export const routeApiPathGroups = {
  dashboard: [apiPaths.dashboard.operations, apiPaths.dashboard.platformHealth, ...commonContextApiPaths],
  raceDay: [
    apiPaths.raceDay.races,
    apiPaths.raceDay.raceOffice,
    apiPaths.raceDay.racingCalendar,
    apiPaths.raceDay.raceCards,
    apiPaths.raceDay.readiness,
    apiPaths.raceDay.surface,
    apiPaths.raceDay.trackConfiguration,
    apiPaths.raceDay.paddock,
    apiPaths.raceDay.paddockOperations,
    apiPaths.raceDay.startingGate,
    apiPaths.raceDay.startingGateOperations,
    apiPaths.raceDay.schedule,
    ...commonContextApiPaths,
  ],
  equine: [
    apiPaths.equine.horse,
    apiPaths.equine.horseRegistry,
    apiPaths.equine.trainerManagement,
    apiPaths.equine.jockeyManagement,
    apiPaths.equine.veterinaryOperations,
    apiPaths.equine.barnOperations,
    apiPaths.equine.horseProfile,
    apiPaths.equine.eligibility,
    apiPaths.equine.equineWelfare,
    apiPaths.equine.equineWelfareDashboard,
    apiPaths.equine.equineWelfareAuditTrail,
    ...commonContextApiPaths,
  ],
  approvals: [apiPaths.approvals.list, apiPaths.approvals.durable, ...commonContextApiPaths],
  incidents: [apiPaths.incidents.security, apiPaths.incidents.emergency, apiPaths.incidents.list, ...commonContextApiPaths],
  compliance: [apiPaths.compliance.library, ...commonContextApiPaths],
  security: [apiPaths.security.workspace, apiPaths.security.zonesLive, ...commonContextApiPaths],
  facilities: [apiPaths.facilities.workspace, ...commonContextApiPaths],
  ticketing: [apiPaths.finance.ticketing, ...commonContextApiPaths],
  finance: [apiPaths.finance.workspace, apiPaths.finance.dashboard, apiPaths.finance.auditTrail, apiPaths.finance.ticketing, ...commonContextApiPaths],
  federation: [apiPaths.federation.workspace, apiPaths.federation.kpiAggregation, apiPaths.federation.industryIntelligence, apiPaths.federation.industryDashboard, apiPaths.federation.industryBenchmarks, apiPaths.federation.industryTrends, apiPaths.federation.federationIntelligence, ...commonContextApiPaths],
  dataHub: [apiPaths.dataHub.workspace, ...commonContextApiPaths],
  audit: [apiPaths.audit.events, apiPaths.audit.search, ...commonContextApiPaths],
  admin: [
    apiPaths.admin.platformHealth,
    apiPaths.admin.foundation,
    apiPaths.admin.environment,
    apiPaths.admin.featureFlags,
    apiPaths.admin.modules,
    apiPaths.admin.identity,
    apiPaths.admin.domainOwnership,
    apiPaths.admin.lineageValidation,
    apiPaths.admin.readinessScorecards,
    apiPaths.admin.executiveScorecard,
    apiPaths.admin.workflowHealth,
    apiPaths.admin.maturityReview,
    apiPaths.admin.governedArtifacts,
    ...commonContextApiPaths,
  ],
  analytics: [apiPaths.analytics.workspace, apiPaths.analytics.knowledgeGraph, apiPaths.analytics.knowledgeGraphSearch, apiPaths.analytics.reporting, apiPaths.search.globalSample, apiPaths.federation.kpiAggregation, ...commonContextApiPaths],
  fanExperience: [apiPaths.fanExperience.workspace, apiPaths.fanExperience.dashboard, apiPaths.fanExperience.auditTrail, ...commonContextApiPaths],
  notifications: [apiPaths.notifications.inbox, ...commonContextApiPaths],
  settings: [
    apiPaths.settings.policy,
    apiPaths.settings.workspace,
    apiPaths.settings.models,
    apiPaths.settings.blockedActions,
    apiPaths.settings.events,
    apiPaths.settings.features,
    apiPaths.settings.modelRegistry,
    ...commonContextApiPaths,
  ],
  stewarding: [
    apiPaths.stewarding.inquiries,
    apiPaths.stewarding.workspace,
    apiPaths.stewarding.dashboard,
    apiPaths.stewarding.auditTrail,
    ...commonContextApiPaths,
  ],
  workforce: [apiPaths.workforce.workspace, ...commonContextApiPaths],
  digitalTwin: [apiPaths.digitalTwin.state, apiPaths.digitalTwin.assets, ...commonContextApiPaths],
  surface: [
    apiPaths.surface.workspace,
    apiPaths.surface.measurements,
    apiPaths.equine.surfaceIntelligence,
    apiPaths.equine.surfaceDashboard,
    ...commonContextApiPaths,
  ],
  emergency: [apiPaths.emergency.workspace, ...commonContextApiPaths],
} as const satisfies Record<DomainRouteId, readonly string[]>;

const pathSources: Record<string, ApiAdapterSource> = {
  [apiPaths.dashboard.operations]: 'live-api',
  [apiPaths.dashboard.platformHealth]: 'live-api',
  [apiPaths.approvals.list]: 'live-api',
  [apiPaths.approvals.durable]: 'live-api',
  [apiPaths.facilities.workspace]: 'live-api',
  [apiPaths.audit.events]: 'live-api',
  [apiPaths.audit.search]: 'live-api',
  [apiPaths.admin.foundation]: 'live-api',
  [apiPaths.admin.environment]: 'live-api',
  [apiPaths.analytics.workspace]: 'live-api',
  [apiPaths.analytics.knowledgeGraph]: 'live-api',
  [apiPaths.analytics.knowledgeGraphSearch]: 'live-api',
  [apiPaths.fanExperience.workspace]: 'live-api',
  [apiPaths.fanExperience.dashboard]: 'live-api',
  [apiPaths.fanExperience.auditTrail]: 'live-api',
  [apiPaths.notifications.inbox]: 'live-api',
  [apiPaths.finance.workspace]: 'live-api',
  [apiPaths.finance.dashboard]: 'live-api',
  [apiPaths.finance.auditTrail]: 'live-api',
  [apiPaths.incidents.list]: 'live-api',
  [apiPaths.raceDay.paddock]: 'live-api',
  [apiPaths.raceDay.startingGate]: 'live-api',
  [apiPaths.equine.startingGateDashboard]: 'live-api',
  [apiPaths.equine.surfaceIntelligence]: 'live-api',
  [apiPaths.equine.surfaceDashboard]: 'live-api',
  [apiPaths.equine.equineWelfare]: 'live-api',
  [apiPaths.equine.equineWelfareDashboard]: 'live-api',
  [apiPaths.equine.equineWelfareAuditTrail]: 'live-api',
  [apiPaths.raceDay.schedule]: 'live-api',
  [apiPaths.security.zonesLive]: 'live-api',
  [apiPaths.settings.modelRegistry]: 'live-api',
  [apiPaths.federation.kpiAggregation]: 'live-api',
  [apiPaths.federation.industryIntelligence]: 'live-api',
  [apiPaths.federation.industryDashboard]: 'live-api',
  [apiPaths.federation.industryBenchmarks]: 'live-api',
  [apiPaths.federation.industryTrends]: 'live-api',
  [apiPaths.federation.federationIntelligence]: 'live-api',
  [apiPaths.analytics.reporting]: 'live-api',
  [apiPaths.search.global]: 'live-api',
  [apiPaths.search.globalSample]: 'live-api',
  [apiPaths.raceDay.racingCalendar]: 'live-api',
  [apiPaths.raceDay.raceCards]: 'live-api',
  [apiPaths.raceDay.paddockOperations]: 'live-api',
  [apiPaths.raceDay.startingGateOperations]: 'live-api',
  [apiPaths.equine.horseRegistry]: 'live-api',
  [apiPaths.equine.trainerManagement]: 'live-api',
  [apiPaths.equine.jockeyManagement]: 'live-api',
  [apiPaths.equine.veterinaryOperations]: 'live-api',
  [apiPaths.admin.identity]: 'live-api',
  [apiPaths.admin.domainOwnership]: 'live-api',
  [apiPaths.admin.lineageValidation]: 'live-api',
  [apiPaths.admin.readinessScorecards]: 'live-api',
  [apiPaths.admin.executiveScorecard]: 'live-api',
  [apiPaths.admin.workflowHealth]: 'live-api',
  [apiPaths.admin.maturityReview]: 'live-api',
  [apiPaths.admin.governedArtifacts]: 'live-api',
  [apiPaths.equine.eligibility]: 'live-api',
};

export function adapterSourceForPath(path: string): ApiAdapterSource {
  const url = new URL(path, 'https://trackmind.local');
  return pathSources[url.pathname] ?? 'live-api';
}

export function backendContractPathsForRoute(routeId: DomainRouteId): string[] {
  return routeApiPathGroups[routeId].map((path) => `${nexusApiBasePath}${path}`);
}

export function apiUrl(path: string): string {
  const normalizedPath = path.startsWith('/') ? path : `/${path}`;
  return `${API_BASE_URL}${normalizedPath}`;
}

export function agentsUrl(path: string): string {
  const normalizedPath = path.startsWith('/') ? path : `/${path}`;
  return `${AGENTS_BASE_URL}${normalizedPath}`;
}
