import { nexusApiBasePath } from '@trackmind/shared';
import type { DomainRouteId } from '@/domain/support';

export function normalizeApiBaseUrl(value: string | undefined): string {
  const baseUrl = (value ?? nexusApiBasePath).trim().replace(/\/+$/, '');
  return baseUrl || nexusApiBasePath;
}

export const API_BASE_URL = normalizeApiBaseUrl(import.meta.env.VITE_TRACKMIND_API_BASE_URL);
export const AGENTS_BASE_URL = (import.meta.env.VITE_TRACKMIND_AGENTS_URL ?? '/agents').replace(/\/+$/, '');

/** Canonical paddock workspace GET; API also serves /paddock-operations/workspace from the same service. */
export const canonicalPaddockWorkspacePath = '/race-operations/paddock' as const;

export type ApiAdapterSource = 'live-api' | 'facade-api' | 'documented-stub';

export const apiPaths = {
  dashboard: {
    operations: '/operations/command-center',
    platformHealth: '/platform/health',
    aiControlPlaneRecommendations: '/ai-control-plane/recommendations',
    aiGovernanceWorkspace: '/ai-governance/workspace',
    aiControlPlaneWorkspace: '/ai-control-plane/workspace',
  },
  kpis: {
    workspace: '/kpis',
    registry: '/kpis/registry',
    definitions: '/kpis/definitions',
    thresholds: '/kpis/thresholds',
    thresholdDraftRequests: '/kpis/thresholds/draft-requests',
  },
  raceDay: {
    races: '/races',
    raceStart: (raceId: string) => `/races/${encodeURIComponent(raceId)}/start`,
    raceStop: (raceId: string) => `/races/${encodeURIComponent(raceId)}/stop`,
    raceScratch: (raceId: string) => `/races/${encodeURIComponent(raceId)}/scratches`,
    raceStartApproval: (raceId: string) =>
      `/starting-gate-operations/races/${encodeURIComponent(raceId)}/race-start-approval`,
    raceOffice: '/race-operations/race-office',
    racingCalendar: '/racing-calendar/workspace',
    raceCards: '/race-cards/workspace',
    readiness: '/race-day-readiness/dashboard',
    surface: '/surface-intelligence/workspace',
    surfaceMeasurements: '/track-surface/measurements',
    trackConfiguration: '/track-configuration/map',
    paddock: canonicalPaddockWorkspacePath,
    startingGate: '/race-operations/starting-gate',
    startingGateOperations: '/starting-gate-operations/workspace',
    schedule: '/race-operations/schedule',
  },
  equine: {
    horseRegistry: '/horse-registry/workspace',
    trainerManagement: '/trainer-management/workspace',
    jockeyManagement: '/jockey-management/workspace',
    jockeyDashboard: '/jockey-management/dashboard',
    veterinaryOperations: '/veterinary-operations/workspace',
    veterinaryDashboard: '/veterinary-operations/dashboard',
    /** Alias of raceDay.paddock; mutations remain under /paddock-operations/*. */
    paddockOperations: canonicalPaddockWorkspacePath,
    paddockDashboard: '/paddock-operations/dashboard',
    stewardOperations: '/steward-operations/workspace',
    stewardDashboard: '/steward-operations/dashboard',
    startingGateOperations: '/starting-gate-operations/workspace',
    startingGateDashboard: '/starting-gate-operations/dashboard',
    surfaceIntelligence: '/surface-intelligence/workspace',
    surfaceDashboard: '/surface-intelligence/dashboard',
    equineWelfare: '/equine-welfare/workspace',
    equineWelfareDashboard: '/equine-welfare/dashboard',
    equineWelfareAuditTrail: '/equine-welfare/audit-trail',
    barnOperations: '/barn-operations/workspace',
    horseProfile: '/horses/horse-1/profile',
    eligibility: '/horses/horse-1/eligibility',
    horseAudit: '/horses/horse-1/audit',
    horseVeterinaryRecord: '/horses/horse-1/veterinary',
    horseEligibilityUpdate: '/horses/horse-1/eligibility',
  },
  approvals: {
    list: '/approvals/requests',
    durable: '/approvals/durable',
    composer: '/approvals/composer',
    controlledActions: '/approvals/controlled-actions',
    draftRequests: '/approvals/draft-requests',
    escalationSimulate: '/approvals/escalation/simulate',
  },
  incidents: {
    security: '/security-operations/workspace',
    emergency: '/emergency-operations/workspace',
    list: '/incidents',
    detail: (incidentId: string) => `/incidents/${incidentId}`,
    timeline: (incidentId: string) => `/incidents/${incidentId}/timeline`,
    timelineStream: (incidentId: string) => `/incidents/${incidentId}/timeline/stream`,
    kpiPack: '/incidents/kpi-pack',
    safetyIntelligenceHotPath: '/safety-intelligence/hot-path/evaluate',
    safetyIntelligenceWarmPath: '/safety-intelligence/warm-path/analyze',
    safetyIntelligenceDebrief: '/safety-intelligence/debrief',
  },
  compliance: {
    library: '/compliance/control-library',
    dashboard: '/compliance/dashboard',
    correctiveActions: '/compliance/corrective-actions',
    correctiveActionUpdates: (correctiveActionId: string) =>
      `/compliance/corrective-actions/${correctiveActionId}/updates`,
    correctiveActionClose: (correctiveActionId: string) =>
      `/compliance/corrective-actions/${correctiveActionId}/close`,
    correctiveActionDelete: (correctiveActionId: string) =>
      `/compliance/corrective-actions/${correctiveActionId}/delete`,
    evidencePacketGenerate: '/compliance/evidence-packets/generate',
    evidenceIntake: '/compliance/evidence/intake',
    evidenceMetadataPatch: '/compliance/evidence/metadata-patch',
  },
  operationalNotes: {
    journal: '/operational-notes/journal',
    workspace: '/operational-notes/workspace',
    intake: '/operational-notes/intake',
    revisions: '/operational-notes/revisions',
    metadataPatch: '/operational-notes/metadata-patch',
  },
  security: {
    workspace: '/security-operations/workspace',
    zonesLive: '/security-operations/zones/live',
    camerasReadiness: '/security-operations/cameras/readiness',
    sensorsReadiness: '/security-operations/sensors/readiness',
    kpis: '/security-operations/kpis',
    events: '/security-operations/events',
    incidentMetadataPatch: '/security-operations/incidents/metadata-patch',
  },
  facilities: {
    workspace: '/facilities-maintenance/workspace',
    map: '/facilities-maintenance/map',
    utilities: '/facilities-maintenance/utilities',
    maintenanceSchedules: '/facilities-maintenance/maintenance-schedules',
    inspections: '/facilities-maintenance/inspections',
    incidents: '/facilities-maintenance/incidents',
    workOrderMetadataPatch: '/facilities-maintenance/work-orders/metadata-patch',
  },
  finance: {
    ticketing: '/services/finance/ticketing',
    payouts: '/services/finance/payouts',
    workspace: '/finance/workspace',
    dashboard: '/finance/dashboard',
    auditTrail: '/finance/audit-trail',
  },
  federation: { workspace: '/federation/workspace', kpiAggregation: '/federation/kpi-aggregation', industryIntelligence: '/industry-intelligence/workspace', industryDashboard: '/industry-intelligence/dashboard', industryBenchmarks: '/industry-intelligence/benchmarks', industryTrends: '/industry-intelligence/trends', federationIntelligence: '/federation-intelligence/workspace' },
  dataHub: {
    workspace: '/racing-data',
    entityResolution: '/racing-data/entity-resolution',
    entityResolutionReview: '/racing-data/entity-resolution/review',
    providerInvoke: (providerId: string) => `/racing-data/providers/${providerId}/invoke`,
  },
  audit: { events: '/audit/events', search: '/audit/search' },
  admin: {
    platformHealth: '/platform/health',
    foundation: '/platform/foundation',
    environment: '/platform/environment',
    featureFlags: '/platform/feature-flags',
    modules: '/platform/modules',
    tenants: '/platform/tenants',
    racetracks: '/platform/racetracks',
    identity: '/identity/workspace',
    domainOwnership: '/platform/domain-ownership',
    lineageValidation: '/platform/governance-lineage/validation',
    readinessScorecards: '/platform/readiness-scorecards',
    executiveScorecard: '/platform/executive-scorecard',
    workflowHealth: '/platform/workflow-health',
    maturityReview: '/platform/maturity-review',
    governedArtifacts: '/platform/governed-artifacts',
  },
  analytics: { workspace: '/analytics/workspace', workspaceStream: '/analytics/workspace/stream', knowledgeGraph: '/knowledge-graph/workspace', knowledgeGraphSearch: '/knowledge-graph/search', reporting: '/reporting/workspace' },
  fanExperience: {
    workspace: '/fan-experience/workspace',
    dashboard: '/fan-experience/dashboard',
    auditTrail: '/fan-experience/audit-trail',
    attendance: '/fan-experience/attendance',
    capacity: '/fan-experience/capacity',
  },
  notifications: {
    inbox: '/notifications/inbox',
    deliveryAdapters: '/notifications/delivery-adapters',
    deliveryAuditTrail: '/notifications/delivery-audit-trail',
    dispatch: '/notifications/dispatch',
    acknowledge: '/notifications/acknowledge',
  },
  settings: {
    policy: '/ai-control-plane/policy',
    workspace: '/ai-control-plane/workspace',
    models: '/ai-control-plane/models',
    blockedActions: '/ai-control-plane/blocked-actions',
    events: '/ai-control-plane/events',
    features: '/ai-control-plane/features',
    modelRegistry: '/ai-governance/model-registry',
    modelCards: '/ai-governance/model-cards',
    promptCards: '/ai-governance/prompt-cards',
    aiGovernanceKpiPack: '/ai-governance/kpi-pack',
    promptLineageDrafts: '/ai-governance/prompt-lineage/drafts',
    publishPromptLineage: (draftId: string) => `/ai-governance/prompt-lineage/${encodeURIComponent(draftId)}/publish`,
  },
  stewarding: {
    inquiries: '/stewarding/inquiries',
    workspace: '/steward-operations/workspace',
    dashboard: '/steward-operations/dashboard',
    auditTrail: '/steward-operations/audit-trail',
    decisionSupport: (inquiryId: string) => `/steward-operations/inquiries/${inquiryId}/decision-support`,
    finalRuling: (inquiryId: string) => `/steward-operations/inquiries/${inquiryId}/final-ruling`,
    evidence: (inquiryId: string) => `/steward-operations/inquiries/${inquiryId}/evidence`,
  },
  workforce: { workspace: '/workforce-operations/workspace' },
  digitalTwin: {
    state: '/digital-twin/state',
    assets: '/assets',
    sync: '/racing-data/sync/digital-twins',
  },
  surface: {
    workspace: '/surface-intelligence/workspace',
    measurements: '/track-surface/measurements',
    operationalActions: '/surface-intelligence/operational-actions',
  },
  emergency: {
    workspace: '/emergency-operations/workspace',
    workflows: '/emergency-operations/workflows',
    communications: (workflowId: string) => `/emergency-operations/workflows/${workflowId}/communications`,
    drills: '/emergency-operations/drills',
    completeDrill: (drillId: string) => `/emergency-operations/drills/${drillId}/complete`,
    afterActionReports: '/emergency-operations/after-action-reports',
  },
  events: { stream: '/events/stream' },
  collaboration: {
    threads: '/collaboration/threads',
    activity: '/collaboration/activity',
    assignments: '/collaboration/assignments',
  },
  entityPicker: {
    kinds: '/entity-picker/kinds',
    search: (kind: string, query = '', limit?: number) => {
      const params = new URLSearchParams({ kind });
      if (query) params.set('q', query);
      if (limit != null) params.set('limit', String(limit));
      return `/entity-picker/search?${params.toString()}`;
    },
  },
  search: { global: '/search/global', globalSample: '/search/global?q=horse' },
} as const;

export const commonContextApiPaths = [
  apiPaths.approvals.list,
  apiPaths.audit.events,
  apiPaths.dashboard.aiControlPlaneRecommendations,
  apiPaths.dashboard.aiGovernanceWorkspace,
  apiPaths.dashboard.aiControlPlaneWorkspace,
  apiPaths.kpis.workspace,
] as const;

export const stewardingSeededInquiryId = 'inq-race-7-1';

export function stewardingFeedPaths(inquiryId = stewardingSeededInquiryId): readonly string[] {
  return [
    apiPaths.stewarding.inquiries,
    apiPaths.stewarding.workspace,
    apiPaths.stewarding.dashboard,
    apiPaths.stewarding.auditTrail,
    apiPaths.stewarding.decisionSupport(inquiryId),
    ...commonContextApiPaths,
  ];
}

export const routeApiPathGroups = {
  dashboard: [
    apiPaths.dashboard.operations,
    apiPaths.dashboard.platformHealth,
    apiPaths.raceDay.readiness,
    apiPaths.raceDay.raceOffice,
    apiPaths.raceDay.races,
    apiPaths.raceDay.surface,
    apiPaths.workforce.workspace,
    apiPaths.equine.horseRegistry,
    apiPaths.digitalTwin.state,
    ...commonContextApiPaths,
  ],
  raceDay: [
    apiPaths.raceDay.races,
    apiPaths.raceDay.raceOffice,
    apiPaths.raceDay.racingCalendar,
    apiPaths.raceDay.raceCards,
    apiPaths.raceDay.readiness,
    apiPaths.raceDay.surface,
    apiPaths.raceDay.surfaceMeasurements,
    apiPaths.raceDay.trackConfiguration,
    apiPaths.raceDay.paddock,
    apiPaths.raceDay.startingGate,
    apiPaths.raceDay.startingGateOperations,
    apiPaths.raceDay.schedule,
    apiPaths.operationalNotes.journal,
    ...commonContextApiPaths,
  ],
  equine: [
    apiPaths.equine.horseProfile,
    apiPaths.equine.eligibility,
    apiPaths.equine.horseAudit,
    apiPaths.equine.horseRegistry,
    apiPaths.equine.trainerManagement,
    apiPaths.equine.jockeyManagement,
    apiPaths.equine.veterinaryOperations,
    apiPaths.equine.barnOperations,
    apiPaths.equine.equineWelfare,
    apiPaths.equine.equineWelfareDashboard,
    apiPaths.equine.equineWelfareAuditTrail,
    ...commonContextApiPaths,
  ],
  approvals: [apiPaths.approvals.list, apiPaths.approvals.durable, ...commonContextApiPaths],
  incidents: [apiPaths.incidents.security, apiPaths.incidents.emergency, apiPaths.incidents.list, apiPaths.incidents.kpiPack, apiPaths.incidents.safetyIntelligenceHotPath, apiPaths.incidents.safetyIntelligenceWarmPath, apiPaths.incidents.safetyIntelligenceDebrief, ...commonContextApiPaths],
  compliance: [
    apiPaths.compliance.dashboard,
    apiPaths.compliance.correctiveActions,
    apiPaths.compliance.library,
    apiPaths.operationalNotes.journal,
    ...commonContextApiPaths,
  ],
  security: [apiPaths.security.workspace, apiPaths.security.zonesLive, apiPaths.security.camerasReadiness, apiPaths.security.sensorsReadiness, apiPaths.security.kpis, ...commonContextApiPaths],
  facilities: [
    apiPaths.facilities.workspace,
    apiPaths.facilities.map,
    apiPaths.facilities.utilities,
    ...commonContextApiPaths,
  ],
  ticketing: [apiPaths.finance.ticketing, ...commonContextApiPaths],
  finance: [apiPaths.finance.workspace, apiPaths.finance.dashboard, apiPaths.finance.auditTrail, ...commonContextApiPaths],
  federation: [apiPaths.federation.workspace, apiPaths.federation.kpiAggregation, apiPaths.federation.industryIntelligence, apiPaths.federation.industryDashboard, apiPaths.federation.industryBenchmarks, apiPaths.federation.industryTrends, apiPaths.federation.federationIntelligence, ...commonContextApiPaths],
  dataHub: [apiPaths.dataHub.workspace, apiPaths.dataHub.entityResolution, ...commonContextApiPaths],
  audit: [apiPaths.audit.events, apiPaths.audit.search, apiPaths.operationalNotes.journal, ...commonContextApiPaths],
  admin: [
    apiPaths.admin.platformHealth,
    apiPaths.admin.foundation,
    apiPaths.admin.environment,
    apiPaths.admin.featureFlags,
    apiPaths.admin.modules,
    apiPaths.admin.identity,
    apiPaths.admin.domainOwnership,
    apiPaths.admin.lineageValidation,
    apiPaths.admin.readinessScorecards,
    apiPaths.admin.executiveScorecard,
    apiPaths.admin.workflowHealth,
    apiPaths.admin.maturityReview,
    apiPaths.admin.governedArtifacts,
    ...commonContextApiPaths,
  ],
  analytics: [
    apiPaths.analytics.workspace,
    apiPaths.analytics.knowledgeGraph,
    apiPaths.analytics.knowledgeGraphSearch,
    apiPaths.analytics.reporting,
    apiPaths.search.globalSample,
    apiPaths.federation.kpiAggregation,
    apiPaths.kpis.registry,
    apiPaths.kpis.definitions,
    apiPaths.kpis.thresholds,
    ...commonContextApiPaths,
  ],
  fanExperience: [
    apiPaths.fanExperience.workspace,
    apiPaths.fanExperience.dashboard,
    apiPaths.fanExperience.auditTrail,
    apiPaths.fanExperience.attendance,
    apiPaths.fanExperience.capacity,
    ...commonContextApiPaths,
  ],
  notifications: [
    apiPaths.notifications.inbox,
    apiPaths.notifications.deliveryAdapters,
    apiPaths.notifications.deliveryAuditTrail,
    ...commonContextApiPaths,
  ],
  account: [
    '/platform/session',
    '/platform/notification-preferences',
    ...commonContextApiPaths,
  ],
  settings: [
    apiPaths.settings.policy,
    apiPaths.settings.workspace,
    apiPaths.settings.models,
    apiPaths.settings.blockedActions,
    apiPaths.settings.events,
    apiPaths.settings.features,
    apiPaths.settings.modelRegistry,
    apiPaths.settings.modelCards,
    apiPaths.settings.promptCards,
    apiPaths.settings.aiGovernanceKpiPack,
    apiPaths.dashboard.aiGovernanceWorkspace,
    ...commonContextApiPaths,
  ],
  stewarding: stewardingFeedPaths(),
  workforce: [apiPaths.workforce.workspace, ...commonContextApiPaths],
  digitalTwin: [
    apiPaths.digitalTwin.state,
    apiPaths.digitalTwin.assets,
    '/track-configuration/map',
    ...commonContextApiPaths,
  ],
  surface: [
    apiPaths.surface.workspace,
    apiPaths.surface.measurements,
    apiPaths.equine.surfaceIntelligence,
    apiPaths.equine.surfaceDashboard,
    ...commonContextApiPaths,
  ],
  emergency: [apiPaths.emergency.workspace, ...commonContextApiPaths],
} as const satisfies Record<DomainRouteId, readonly string[]>;

const defaultRaceId = 'race-7';

/** POST/mutation contract paths declared on routes but not fetched by workspace GET loaders. */
export const routeMutationPathGroups = {
  dashboard: [apiPaths.approvals.draftRequests],
  raceDay: [
    apiPaths.raceDay.raceStart(defaultRaceId),
    apiPaths.raceDay.raceStop(defaultRaceId),
    apiPaths.raceDay.raceScratch(defaultRaceId),
    apiPaths.raceDay.raceStartApproval(defaultRaceId),
  ],
  equine: [apiPaths.equine.horseEligibilityUpdate],
  stewarding: [apiPaths.stewarding.finalRuling(stewardingSeededInquiryId)],
  surface: [apiPaths.surface.operationalActions],
  approvals: [apiPaths.approvals.escalationSimulate, apiPaths.approvals.composer],
  incidents: [apiPaths.security.events],
  emergency: [
    apiPaths.emergency.workflows,
    apiPaths.emergency.drills,
    apiPaths.emergency.afterActionReports,
  ],
  compliance: [apiPaths.compliance.correctiveActions, apiPaths.compliance.evidencePacketGenerate],
  security: [apiPaths.security.events],
  facilities: [apiPaths.facilities.maintenanceSchedules, apiPaths.facilities.incidents],
  workforce: [apiPaths.collaboration.assignments],
  digitalTwin: [apiPaths.digitalTwin.sync],
  ticketing: [apiPaths.notifications.dispatch],
  finance: [apiPaths.finance.payouts],
  dataHub: [apiPaths.dataHub.providerInvoke('default-provider')],
  audit: [apiPaths.approvals.controlledActions],
  admin: [apiPaths.approvals.controlledActions],
  analytics: [apiPaths.kpis.thresholdDraftRequests],
  fanExperience: [apiPaths.notifications.dispatch],
  notifications: [apiPaths.notifications.dispatch, apiPaths.notifications.acknowledge],
  settings: [apiPaths.settings.promptLineageDrafts],
} as const satisfies Partial<Record<DomainRouteId, readonly string[]>>;

const pathSources: Record<string, ApiAdapterSource> = {
  [apiPaths.dashboard.operations]: 'live-api',
  [apiPaths.dashboard.platformHealth]: 'live-api',
  [apiPaths.kpis.workspace]: 'live-api',
  [apiPaths.kpis.registry]: 'live-api',
  [apiPaths.kpis.definitions]: 'live-api',
  [apiPaths.kpis.thresholds]: 'live-api',
  [apiPaths.kpis.thresholdDraftRequests]: 'live-api',
  [apiPaths.approvals.list]: 'live-api',
  [apiPaths.approvals.durable]: 'live-api',
  [apiPaths.facilities.workspace]: 'live-api',
  [apiPaths.facilities.map]: 'live-api',
  [apiPaths.facilities.utilities]: 'live-api',
  [apiPaths.facilities.maintenanceSchedules]: 'live-api',
  [apiPaths.facilities.incidents]: 'live-api',
  [apiPaths.audit.events]: 'live-api',
  [apiPaths.audit.search]: 'facade-api',
  [apiPaths.admin.featureFlags]: 'live-api',
  [apiPaths.admin.modules]: 'live-api',
  [apiPaths.admin.tenants]: 'live-api',
  [apiPaths.admin.racetracks]: 'live-api',
  [apiPaths.admin.foundation]: 'live-api',
  [apiPaths.admin.environment]: 'live-api',
  [apiPaths.analytics.workspace]: 'live-api',
  [apiPaths.analytics.knowledgeGraph]: 'live-api',
  [apiPaths.analytics.knowledgeGraphSearch]: 'live-api',
  [apiPaths.fanExperience.workspace]: 'live-api',
  [apiPaths.fanExperience.dashboard]: 'live-api',
  [apiPaths.fanExperience.auditTrail]: 'live-api',
  [apiPaths.fanExperience.attendance]: 'live-api',
  [apiPaths.fanExperience.capacity]: 'live-api',
  [apiPaths.notifications.inbox]: 'live-api',
  [apiPaths.notifications.deliveryAdapters]: 'live-api',
  [apiPaths.notifications.deliveryAuditTrail]: 'live-api',
  [apiPaths.finance.workspace]: 'live-api',
  [apiPaths.finance.dashboard]: 'live-api',
  [apiPaths.finance.auditTrail]: 'live-api',
  [apiPaths.incidents.list]: 'live-api',
  [apiPaths.incidents.kpiPack]: 'live-api',
  '/incidents/inc-1': 'live-api',
  '/incidents/inc-1/timeline': 'live-api',
  [apiPaths.incidents.safetyIntelligenceHotPath]: 'live-api',
  [apiPaths.incidents.safetyIntelligenceWarmPath]: 'live-api',
  [apiPaths.incidents.safetyIntelligenceDebrief]: 'live-api',
  [apiPaths.raceDay.paddock]: 'live-api',
  [apiPaths.raceDay.raceOffice]: 'live-api',
  [apiPaths.raceDay.startingGate]: 'live-api',
  // surface.workspace and raceDay.surface share pathname /surface-intelligence/workspace
  [apiPaths.raceDay.surface]: 'live-api',
  // surface.measurements and raceDay.surfaceMeasurements share pathname /track-surface/measurements
  [apiPaths.raceDay.surfaceMeasurements]: 'live-api',
  [apiPaths.equine.startingGateDashboard]: 'live-api',
  [apiPaths.equine.equineWelfare]: 'live-api',
  [apiPaths.equine.equineWelfareDashboard]: 'live-api',
  [apiPaths.equine.equineWelfareAuditTrail]: 'live-api',
  [apiPaths.raceDay.schedule]: 'live-api',
  [apiPaths.security.zonesLive]: 'live-api',
  [apiPaths.security.camerasReadiness]: 'live-api',
  [apiPaths.security.sensorsReadiness]: 'live-api',
  [apiPaths.security.kpis]: 'live-api',
  [apiPaths.settings.modelRegistry]: 'live-api',
  [apiPaths.settings.modelCards]: 'live-api',
  [apiPaths.settings.promptCards]: 'live-api',
  [apiPaths.settings.aiGovernanceKpiPack]: 'live-api',
  [apiPaths.federation.kpiAggregation]: 'facade-api',
  [apiPaths.federation.workspace]: 'facade-api',
  [apiPaths.federation.industryIntelligence]: 'live-api',
  [apiPaths.federation.industryDashboard]: 'live-api',
  [apiPaths.federation.industryBenchmarks]: 'live-api',
  [apiPaths.federation.industryTrends]: 'live-api',
  [apiPaths.federation.federationIntelligence]: 'live-api',
  [apiPaths.analytics.reporting]: 'live-api',
  [apiPaths.search.global]: 'live-api',
  [apiPaths.search.globalSample]: 'live-api',
  [apiPaths.raceDay.racingCalendar]: 'live-api',
  [apiPaths.raceDay.raceCards]: 'live-api',
  [apiPaths.raceDay.startingGateOperations]: 'live-api',
  [apiPaths.equine.horseRegistry]: 'live-api',
  [apiPaths.equine.trainerManagement]: 'live-api',
  [apiPaths.equine.jockeyManagement]: 'live-api',
  [apiPaths.equine.veterinaryOperations]: 'live-api',
  [apiPaths.equine.barnOperations]: 'live-api',
  [apiPaths.admin.identity]: 'live-api',
  [apiPaths.admin.domainOwnership]: 'live-api',
  [apiPaths.admin.lineageValidation]: 'live-api',
  [apiPaths.admin.readinessScorecards]: 'live-api',
  [apiPaths.admin.executiveScorecard]: 'live-api',
  [apiPaths.admin.workflowHealth]: 'live-api',
  [apiPaths.admin.maturityReview]: 'live-api',
  [apiPaths.admin.governedArtifacts]: 'live-api',
  [apiPaths.equine.horseProfile]: 'live-api',
  [apiPaths.equine.eligibility]: 'live-api',
  [apiPaths.equine.horseAudit]: 'live-api',
  [apiPaths.compliance.dashboard]: 'live-api',
  [apiPaths.compliance.correctiveActions]: 'live-api',
  [apiPaths.compliance.library]: 'live-api',
  [apiPaths.compliance.evidencePacketGenerate]: 'live-api',
  [apiPaths.compliance.evidenceIntake]: 'live-api',
  [apiPaths.operationalNotes.journal]: 'live-api',
  [apiPaths.operationalNotes.workspace]: 'live-api',
  [apiPaths.operationalNotes.intake]: 'live-api',
  [apiPaths.operationalNotes.revisions]: 'live-api',
  [apiPaths.approvals.escalationSimulate]: 'live-api',
  [apiPaths.approvals.controlledActions]: 'live-api',
  [apiPaths.approvals.draftRequests]: 'live-api',
  [apiPaths.surface.operationalActions]: 'live-api',
  [apiPaths.notifications.dispatch]: 'live-api',
  [apiPaths.notifications.acknowledge]: 'live-api',
  [apiPaths.collaboration.assignments]: 'live-api',
  [apiPaths.digitalTwin.sync]: 'facade-api',
  [apiPaths.digitalTwin.state]: 'facade-api',
  [apiPaths.digitalTwin.assets]: 'facade-api',
  [apiPaths.finance.payouts]: 'live-api',
  [apiPaths.raceDay.raceStart(defaultRaceId)]: 'live-api',
  [apiPaths.raceDay.raceStop(defaultRaceId)]: 'live-api',
  [apiPaths.raceDay.raceScratch(defaultRaceId)]: 'live-api',
  [apiPaths.raceDay.raceStartApproval(defaultRaceId)]: 'live-api',
};

export function adapterSourceForPath(path: string): ApiAdapterSource {
  const url = new URL(path, 'https://trackmind.local');
  return pathSources[url.pathname] ?? 'documented-stub';
}

export function backendContractPathsForRoute(routeId: DomainRouteId): string[] {
  const fetchPaths = routeApiPathGroups[routeId].map((path) => `${nexusApiBasePath}${path}`);
  const mutationPaths = (routeMutationPathGroups[routeId as keyof typeof routeMutationPathGroups] ?? []).map(
    (path) => `${nexusApiBasePath}${path}`,
  );
  return [...fetchPaths, ...mutationPaths];
}

export function apiUrl(path: string): string {
  const normalizedPath = path.startsWith('/') ? path : `/${path}`;
  return `${API_BASE_URL}${normalizedPath}`;
}

export function agentsUrl(path: string): string {
  const normalizedPath = path.startsWith('/') ? path : `/${path}`;
  return `${AGENTS_BASE_URL}${normalizedPath}`;
}
