import type { ApprovalStatus, ProtectedAction, Role } from '@trackmind/shared';

export type NexusRole = Role;
export type AdapterMode = 'live' | 'mock';
export type LoadState<T> = { status: 'loading' } | { status: 'error'; message: string; mock: boolean } | { status: 'empty'; mock: boolean } | { status: 'ready'; data: T; mock: boolean };
export interface UserSession { userId: string; displayName: string; roles: NexusRole[]; authenticated: boolean }
export interface ApprovalDto { id: string; action: ProtectedAction | string; target: string; requestedBy: string; status: ApprovalStatus; createdAt: string; expiresAt: string; evidence: string[]; mock: boolean }
export interface AuditEventDto { id: string; type: string; actor: string; timestamp: string; subjectId?: string; severity: 'info' | 'warning' | 'critical'; hash: string; previousHash: string; mock: boolean }
export interface TrackSectorDto { id: string; name: string; startMeters: number; endMeters: number; condition: 'fast' | 'good' | 'muddy' | 'maintenance' }
export interface SurfaceMeasurementDto { sectorId: string; moisture: number; compaction: number; measuredAt: string }
export interface AssetMarkerDto { id: string; type: 'gate' | 'sensor' | 'vehicle' | 'camera' | 'crew'; label: string; sectorId: string; status: 'online' | 'offline' | 'standby' | 'warning' }

export type GeospatialLayerDto = 'sector' | 'gate' | 'rail' | 'barn' | 'facility' | 'camera' | 'emergency' | 'measurement' | 'incident' | 'maintenance' | 'workforce' | 'twin' | 'simulation';
export interface GeospatialFeatureDto { id: string; layer: GeospatialLayerDto; label: string; status: 'nominal' | 'standby' | 'warning' | 'critical' | 'closed' | 'in-progress' | 'simulated'; source: 'asset-registry' | 'telemetry' | 'event-service' | 'digital-twin' | 'simulation' | 'track-configuration'; coordinates: { latitude: number; longitude: number }; properties: Record<string, unknown> }
export interface GeospatialMapDto { viewport: { center: { latitude: number; longitude: number }; zoom: number; bounds: { north: number; south: number; east: number; west: number } }; overlays: Array<{ id: string; name: string; layer: GeospatialLayerDto; visible: boolean; opacity: number }>; features: GeospatialFeatureDto[]; playback: Array<{ at: string; featureIds: string[]; summary: string }>; simulationOverlays: Array<{ id: string; scenario: string; featureIds: string[]; riskDelta: number; approvalRequired: boolean }>; digitalTwinState: Array<{ twinId: string; assetId: string; health: string; version: number; lastUpdatedAt: string }>; controls: { zoom: { current: number; presets: number[] }; filters: string[]; overlayModes: string[]; playbackEnabled: boolean } }
export interface TrackMapDto { trackId: string; distanceMeters: number; startingGate: { sectorId: string; metersFromStart: number }; sectors: TrackSectorDto[]; measurements: SurfaceMeasurementDto[]; assets: AssetMarkerDto[]; geospatial?: GeospatialMapDto; mock: boolean }

export interface CommandWidgetDto { id: string; title: string; domain: string; status: 'nominal' | 'advisory' | 'warning' | 'critical'; value: string; detail: string; source: 'service' | 'event-stream' | 'digital-twin' | 'approved-mock-adapter'; drillDownPath: string; roleView: NexusRole[] | 'all'; configurable: boolean }
export interface OperationsLayoutDto { id: string; name: string; role: NexusRole | 'all'; widgetIds: string[] }
export interface LiveEventDto { id: string; timestamp: string; type: string; domain: string; summary: string; severity: 'info' | 'advisory' | 'warning' | 'critical'; source: CommandWidgetDto['source'] }
export interface OperationalAlertDto { id: string; title: string; severity: 'advisory' | 'warning' | 'critical'; acknowledged: boolean; actionPath: string; evidence: string[] }
export interface OperationsCommandCenterDto { generatedAt: string; activeLayoutId: string; widgets: CommandWidgetDto[]; savedLayouts: OperationsLayoutDto[]; liveEvents: LiveEventDto[]; alerts: OperationalAlertDto[]; aiRecommendations: Array<{ id: string; recommendation: string; confidence: number; evidence: string[]; requiresApproval: boolean; actionPath: string }> ; dataLineage: Array<{ domain: string; source: CommandWidgetDto['source']; reference: string }> ; mock: boolean }

export type SurfaceRiskDto = 'low' | 'moderate' | 'high' | 'critical';
export interface SurfaceSectorDto { id: string; name: string; surfaceType: 'dirt' | 'turf' | 'synthetic'; startMeters: number; endMeters: number; status: 'open' | 'watch' | 'maintenance' | 'closed'; conditionScore: number; moisture: number; compaction: number; cushionDepth: number; drainageRate: number; latestInspectionAt: string }
export interface SurfaceTimelinePointDto { id: string; sectorId: string; kind: 'moisture' | 'compaction' | 'cushion-depth' | 'drainage' | 'weather' | 'inspection' | 'maintenance-activity' | 'manual-observation'; observedAt: string; label: string; value: string; eventId: string; auditId: string }
export interface SurfaceHeatmapCellDto { id: string; sectorId: string; latitude: number; longitude: number; averageMoisture: number; averageCompaction: number; averageDrainage: number; riskIndex: number; latestObservedAt: string }
export interface SurfaceRecommendationDto { id: string; type: 'maintenance' | 'irrigation' | 'inspection' | 'drainage' | 'race-readiness'; sectorId: string; priority: SurfaceRiskDto; recommendation: string; requiresHumanApproval: true; executionState: 'approval-required' | 'approved-for-execution'; eventId: string; auditId: string }
export interface SurfaceIntelligenceDto { trackId: string; generatedAt: string; overallScore: number; approvalState: 'required' | 'approved'; operationalActionsRequireHumanApproval: true; statusCards: Array<{ label: string; value: string; tone: 'nominal' | 'advisory' | 'warning' | 'critical'; detail: string }>; sectors: SurfaceSectorDto[]; timeline: SurfaceTimelinePointDto[]; heatmap: SurfaceHeatmapCellDto[]; recommendations: SurfaceRecommendationDto[]; riskBadges: Array<{ sectorId: string; level: SurfaceRiskDto; drivers: string[] }>; weatherObservation: { observedAt: string; rainfallMm: number; forecastRainMm: number; temperature: number; windMph: number }; digitalTwinSync: Array<{ twinId: string; status: 'queued-for-human-approved-sync' | 'synced'; patch: Record<string, unknown>; eventId: string; auditId: string }>; mock: boolean }


export interface EquineIntelligenceDto { horse: { horseId: string; name: string; lifecycleStatus: string; microchipId?: string }; ownership: Array<{ ownerId: string; ownerName: string; percentage: number; effectiveFrom: string }>; trainerAssignments: Array<{ trainerId: string; trainerName: string; licenseStatus: string; effectiveFrom: string }>; raceHistory: Array<{ raceId: string; date: string; trackId: string; status: string; finishPosition?: number }>; workoutHistory: Array<{ workoutId: string; date: string; distanceFurlongs: number; timeSeconds: number; surface: string }>; veterinaryStatus: { status: string; summary: string; requiresVeterinarian: true }; eligibilityStatus: { eligible: boolean; complianceStatus: string; flags: string[]; failedRules: string[] }; welfareStatus: { level: string; latestScore?: number; interventions: string[] }; barnAssignment: { barnId: string; stallId?: string; assignedAt: string }; digitalTwinReferences: Array<{ twinId: string; twinType: string; sourceSystem: string; relationship: string; readOnly: boolean }>; aiRiskRecommendations: Array<{ id: string; summary: string; advisoryOnly: true; veterinarianReviewRequired: boolean; status: string; proposedOperationalAction?: string }>; approvals: Array<{ id: string; action: string; status: string; requiredRole: string }>; audit: Array<{ id: string; actor: string; action: string; timestamp: string }>; events: Array<{ eventId: string; type: string; auditId: string }>; mock: boolean }

export interface ActionResultDto { accepted: boolean; approvalId: string; eventType: string; audited: boolean; message: string; mock: boolean }


export type ReadinessDomainDto = 'track' | 'gate' | 'staffing' | 'veterinary' | 'stewards' | 'emergency' | 'security' | 'weather' | 'facility';
export type ReadinessStatusDto = 'ready' | 'watch' | 'blocked';
export interface RaceDayReadinessCheckDto { domain: ReadinessDomainDto; label: string; score: number; status: ReadinessStatusDto; evidence: string[]; blockers: string[]; updatedAt: string; approvalRequired?: boolean; ownerRole: string }
export interface RaceDayReadinessDashboardDto { generatedAt: string; averageScore: number; ready: number; watch: number; blocked: number; races: Array<{ raceId: string; trackId: string; postTime: string; score: number; status: ReadinessStatusDto; warnings: number; approvals: number }>; warnings: Array<{ id: string; raceId: string; domain: ReadinessDomainDto; severity: 'advisory' | 'warning' | 'critical'; message: string; recommendedAction: string; evidence: string[] }>; approvals: Array<{ id: string; raceId: string; action: string; requiredRoles: string[]; reason: string; evidence: string[]; status: 'pending' | 'satisfied' }>; events: Array<{ id: string; raceId: string; type: string; domain?: ReadinessDomainDto; severity: 'info' | 'advisory' | 'warning' | 'critical'; message: string; evidence: string[]; timestamp: string }>; auditRecords: Array<{ id: string; raceId: string; actor: string; timestamp: string; summaryHash: string; previousHash: string; score: number; status: ReadinessStatusDto; evidence: string[] }>; domainScores: Array<{ domain: ReadinessDomainDto; averageScore: number; blocked: number; watch: number }> ; mock: boolean }

export interface GatePositionDto { gateId: string; sectorId: string; metersFromStart: number; gpsVerified: boolean; lastApprovedRequestId?: string; mock: boolean }
export interface RaceDistanceConfigurationDto { raceId: string; distanceMeters: number; gateSectorId: string; configuredBy: string; approvedRequestId?: string; mock: boolean }
export interface DigitalTwinStateDto { twinId: string; assetId: string; health: string; version: number; lastUpdatedAt: string; state?: Record<string, unknown>; mock: boolean }
export interface CommandCenterModelDto { assets: AssetMarkerDto[]; trackSectors: TrackSectorDto[]; gatePosition: GatePositionDto; raceDistanceConfiguration: RaceDistanceConfigurationDto; pendingApprovals: ApprovalDto[]; auditEvents: AuditEventDto[]; digitalTwinState: DigitalTwinStateDto[]; barnOperations: BarnOperationsDto; mock: boolean }
export type DraftActionDto = { action: 'starting-gate-move' | 'race-distance-configuration'; target: string; reason: string; actor: string; evidence: string[]; payload: Record<string, unknown> };


export interface BarnOperationsDto { barns: Array<{ id: string; name: string; location: string; status: string; capacity: number; incidentIds: string[]; trainerIds: string[] }>; stalls: Array<{ id: string; barnId: string; label: string; status: string; occupancyHorseId?: string; restrictionIds: string[] }>; occupancy: Array<{ horseId: string; barnId: string; stallId: string; assignedAt: string; assignedBy: string; eventId: string; auditId: string; twinId: string }>; movements: Array<{ id: string; horseId: string; fromBarnId?: string; fromStallId?: string; toBarnId: string; toStallId: string; reason: string; movedAt: string; movedBy: string; eventId: string; auditId: string; approvalRequestId?: string }>; access: Array<{ id: string; barnId: string; actorId: string; purpose: string; accessAt: string; decision: string; eventId: string; auditId: string }>; inspections: Array<{ id: string; barnId: string; inspectedBy: string; inspectedAt: string; score: number; findings: string[]; status: string; eventId: string; auditId: string }>; restrictions: Array<{ id: string; barnId: string; stallId?: string; horseId?: string; type: string; reason: string; active: boolean; createdAt: string; createdBy: string; approvalRequestId?: string; eventId: string; auditId: string }>; trainers: Array<{ id: string; barnId: string; trainerId: string; assignedBy: string; assignedAt: string; active: boolean; auditId: string; eventId: string }>; vetVisits: Array<{ id: string; horseId: string; barnId: string; stallId?: string; veterinarianId: string; visitAt: string; findings: string[]; restrictionsCreated: string[]; eventId: string; auditId: string }>; readiness: Array<{ barnId: string; status: string; score: number; blockers: string[]; openRestrictions: number; occupiedStalls: number; capacity: number }>; mock: boolean }


export interface StewardCenterDto { inquiries: Array<{ id: string; raceId: string; openedAt: string; status: string; objections: Array<{ id: string; filedBy: string; allegation: string; status: string }>; incidentsUnderReview: Array<{ id: string; description: string; severity: string; status: string }>; involvedHorses: Array<{ horseId: string; name: string; programNumber: string; officialResultLocked: true }>; involvedJockeys: Array<{ jockeyId: string; name: string; licenseId: string; horseId: string }>; evidenceReferences: Array<{ id: string; kind: string; uri: string; capturedAt: string; description: string; hash: string; aiGenerated?: boolean }>; ruleReferences: Array<{ id: string; jurisdiction: string; rulebook: string; section: string; citation: string; summary: string }>; decisionDrafts: Array<{ id: string; authorId: string; authorRole: string; recommendation: string; rationale: string; aiGenerated: boolean; officialRuling: false; evidenceIds: string[]; ruleIds: string[] }>; finalRuling?: { id: string; issuedBy: string; decision: string; officialResultsModified: false }; appealPackages: Array<{ id: string; contents: { auditRecordIds: string[] } }>; auditRecords: Array<{ id: string; actorId: string; action: string; subjectId: string; hash: string; previousHash: string }>; aiGuardrails: { advisoryOnly: true; mayIssueOfficialRuling: false; mayModifyOfficialResults: false } }>; permissions: { canRead: boolean; canDraft: boolean; canFinalize: boolean; canExportAppeal: boolean }; mock: boolean }

export interface SecurityOperationsDto { restrictedZones: Array<{ id: string; name: string; classification: string; requiredCredential: string; cameraIds: string[] }>; cameras: Array<{ id: string; zoneId: string; label: string; health: 'online' | 'degraded' | 'offline'; privacyMasking: boolean; lastHeartbeatAt: string }>; accessEvents: Array<{ id: string; zoneId: string; credentialId: string; personDisplayName: string; personLegalName?: string; decision: string; reason: string; occurredAt: string; eventId: string; auditId: string }>; incidents: Array<{ id: string; title: string; severity: 'low' | 'medium' | 'high' | 'critical'; status: string; zoneId: string; eventIds: string[]; assignedTo?: string; createdAt: string; auditId: string }>; investigations: Array<{ id: string; incidentId: string; status: string; lead: string; evidence: string[]; openedAt: string; auditId: string }>; watchlistPlaceholders: Array<{ id: string; category: string; displayLabel: string; sensitiveNotes?: string; requiresHumanReview: true }>; visitorLogs: Array<{ id: string; visitorDisplayName: string; visitorLegalName?: string; host: string; zoneId: string; checkedInAt: string; checkedOutAt?: string; credentialCheckId: string; auditId: string }>; credentialChecks: Array<{ id: string; credentialId: string; holderDisplayName: string; holderLegalName?: string; status: string; checkedAt: string; decision: string; auditId: string }>; escalations: Array<{ id: string; incidentId: string; routeTo: string[]; status: string; reason: string; auditId: string }>; auditRecords: Array<{ id: string; action: string; actorId: string; subjectId: string; timestamp: string; hash: string; previousHash: string; sensitiveFields: string[] }>; dashboard: { activeAlerts: number; restrictedZoneEvents: number; cameraHealth: Record<'online' | 'degraded' | 'offline', number>; incidentTimeline: Array<{ at: string; label: string; severity: 'low' | 'medium' | 'high' | 'critical' }>; investigationQueue: number }; mock: boolean }


export interface EmergencyOperationsDto { activeEmergencyStatus: string; plans: Array<{ id: string; name: string; scenarios: string[]; activationCriteria: string[]; drillCadenceDays: number }>; commandRoles: Array<{ id: string; role: string; assignee: string; permissions: string[] }>; resources: Array<{ id: string; kind: string; label: string; status: string; zoneId: string; coordinates: { latitude: number; longitude: number }; capacity?: number }>; resourceMap: Array<{ id: string; label: string; kind: string; status: string; zoneId: string; coordinates: { latitude: number; longitude: number } }>; medicalResponse: { lead: string; checklist: string[]; humanOverrideSupported: true; aiMayBlock: false }; fireResponse: { lead: string; checklist: string[]; humanOverrideSupported: true; aiMayBlock: false }; severeWeatherResponse: { lead: string; checklist: string[]; humanOverrideSupported: true; aiMayBlock: false }; evacuationZones: Array<{ id: string; name: string; status: string; route: string[]; assemblyArea: string; capacity: number }>; checklist: Array<{ id: string; label: string; completed: boolean; humanOverrideAvailable: true; aiBlockingAllowed: false }>; communicationLog: Array<{ id: string; audience: string; channel: string; message: string; completed: boolean; completedBy?: string; completedAt?: string }>; drills: Array<{ id: string; scenario: string; participants: string[]; successCriteria: string[] }>; afterActionReports: Array<{ incidentId: string; findings: Array<{ finding: string; severity: string; owner: string }>; correctiveActions: Array<{ id: string; owner: string; action: string; dueDays: number }> }>; auditTimeline: Array<{ id: string; action: string; actor: string; subjectId: string; timestamp: string; humanOverride: boolean; aiBlocked: false; hash: string; previousHash: string }>; events: Array<{ id: string; type: string; subjectId: string; severity: string; timestamp: string; auditId: string }>; emergencyActions: { humanOverrideSupported: true; aiMayBlock: false; reason: string }; mock: boolean }

export type ComplianceFrameworkIdDto = 'ISO-42001'|'ISO-27001'|'ISO-27701'|'ISO-31000'|'ISO-22301'|'SOC-2'|'PCI-DSS'|'HISA'|'ARCI'|'LOCAL-RACING-COMMISSION';
export interface ComplianceControlLibraryDto { frameworks: Array<{ id: ComplianceFrameworkIdDto; name: string; placeholder: boolean; domains: string[]; authority: string }>; controls: Array<{ id: string; frameworkIds: ComplianceFrameworkIdDto[]; title: string; description: string; status: string; ownerId: string; obligationIds: string[]; evidenceIds: string[]; assessmentIds: string[]; workflowInstanceIds: string[]; auditRecordIds: string[] }>; obligations: Array<{ id: string; frameworkId: ComplianceFrameworkIdDto; citation: string; summary: string; applicability: string; controlIds: string[] }>; owners: Array<{ id: string; displayName: string; role: NexusRole; permissions: string[] }>; findings: Array<{ id: string; controlId: string; severity: string; summary: string; status: string; correctiveActionIds: string[] }>; correctiveActions: Array<{ id: string; findingId: string; ownerId: string; action: string; dueAt: string; status: string; workflowInstanceId?: string }>; reviewCycles: Array<{ id: string; frameworkId: ComplianceFrameworkIdDto; periodStart: string; periodEnd: string; controlIds: string[]; status: string; readinessScore: number }>; readiness: { score: number; totalControls: number; effectiveControls: number; evidenceCoverage: number; openFindings: number; overdueActions: number; byFramework: Array<{ frameworkId: ComplianceFrameworkIdDto; score: number; controls: number }> }; mock: boolean }

export type PlatformHealthState = 'healthy' | 'degraded' | 'critical';
export interface PlatformHealthWorkspaceDto { generatedAt: string; overallStatus: PlatformHealthState; services: Array<{ serviceId: string; status: PlatformHealthState; latencyMs: number; dependencies: Array<{ id: string; status: PlatformHealthState; required: boolean }>; lastCheckedAt: string }>; eventBus: { status: PlatformHealthState; publishedEvents: number; deadLetters: number; schemas: number; eventsPerMinute: number; throughputCapacity: number; backpressure: boolean }; audit: { status: PlatformHealthState; validLedger: boolean; records: number; criticalRecords: number }; approvalEngine: { status: PlatformHealthState; pending: number; approved: number; rejected: number; escalated: number; expired: number }; aiGovernance: { status: PlatformHealthState; activeAgents: number; pendingReviews: number; blockedActions: number; driftBreaches: number }; digitalTwin: { status: PlatformHealthState; totalTwins: number; healthy: number; degraded: number; critical: number; queuedSync: number; lastSyncAt?: string }; workflows: { status: PlatformHealthState; active: number; completed: number; failed: number }; apiLatency: { p50Ms: number; p95Ms: number; budgetMs: number; status: PlatformHealthState }; frontend: { status: PlatformHealthState; reportedErrors: number; lastErrorAt?: string; degradedMode: boolean }; telemetrySchema: { version: 'platform-observability.v1'; requiredSignals: Array<'log'|'metric'|'trace'|'frontend-error'>; consistent: boolean }; signals: Array<{ kind: string; name: string; serviceId: string; severity: string; traceId: string; spanId?: string; attributes: Record<string, unknown>; timestamp: string }>; }

export interface AIGovernanceWorkspaceDto {
  generatedAt: string;
  activeAgents: Array<{ id: string; name: string; owner: string; status: string; modelVersionId: string; promptTemplateId: string; allowedActions: string[]; restrictedActions: string[] }>;
  modelVersions: Array<{ id: string; name: string; version: string; status: string; riskLevel: string; evidence: string[]; lineage: string[] }>;
  promptTemplates: Array<{ id: string; name: string; version: string; status: string; evidence: string[] }>;
  recommendationQueue: Array<{ id: string; agentId: string; recommendation: string; confidence: number; affectedAssets: string[]; evidence: string[]; approvalPolicy: string; riskLevel: string; lineage: string[]; status: string }>;
  safetyBlockedActions: Array<{ id: string; action: string; target: string; reason: string; evidence: string[]; affectedAssets: string[]; approvalPolicy: string; confidence: number; lineage: string[] }>;
  evaluationStatus: Array<{ modelVersionId: string; status: string; readiness: { deployable: boolean; gaps: string[] }; latestEvaluation?: { safetyPassed: boolean; explainabilityScore: number; fairnessScore: number } }>;
  riskClassifications: Array<{ subjectId: string; level: string; drivers: string[] }>;
  approvalRequirements: Array<{ id: string; recommendationId: string; policy: string; requiredRoles: string[]; status: string; evidence: string[] }>;
  evidencePackages: Array<{ id: string; recommendationId: string; evidence: string[]; lineage: string[]; hash: string }>;
  overrides: Array<{ id: string; recommendationId: string; actor: string; reason: string; evidence: string[] }>;
  rollbackRecords: Array<{ id: string; recommendationId: string; actor: string; reason: string; restoredVersionId: string; evidence: string[] }>;
  monitoringMetrics: Array<{ modelId: string; metric: string; value: number; threshold: number; evidence: string[] }>;
  auditTrails: Array<{ id: string; action: string; actor: string; subject: string; evidence: string[]; timestamp: string }>;
  events: Array<{ id: string; type: string; subjectId: string; timestamp: string }>;
  mock: boolean;
}
