import type { Role } from '@trackmind/shared';
import { ImmutableAuditLog } from './auditLog.js';
import { type ApprovalToken, CentralizedApprovalService } from './approvals.js';
import { UniversalEventBus } from './eventBus.js';

export type BarnStatus = 'ready' | 'watch' | 'restricted' | 'closed';
export type StallStatus = 'available' | 'occupied' | 'maintenance' | 'restricted';
export type BarnPermission = 'barn:read' | 'barn:manage' | 'stall:assign' | 'movement:record' | 'access:record' | 'inspection:perform' | 'vet:record' | 'restriction:manage';
export interface BarnActor { id: string; roles: Role[]; tenantId: string }
export interface Barn { id: string; name: string; tenantId: string; location: string; status: BarnStatus; capacity: number; incidentIds: string[]; trainerIds: string[] }
export interface Stall { id: string; barnId: string; label: string; status: StallStatus; occupancyHorseId?: string; restrictionIds: string[] }
export interface HorseOccupancy { horseId: string; barnId: string; stallId: string; assignedAt: string; assignedBy: string; eventId: string; auditId: string; twinId: string }
export interface HorseMovementRecord { id: string; horseId: string; fromBarnId?: string; fromStallId?: string; toBarnId: string; toStallId: string; reason: string; movedAt: string; movedBy: string; eventId: string; auditId: string; approvalRequestId?: string }
export interface BarnAccessRecord { id: string; barnId: string; actorId: string; purpose: string; accessAt: string; decision: 'allowed' | 'denied'; eventId: string; auditId: string }
export interface BarnInspection { id: string; barnId: string; inspectedBy: string; inspectedAt: string; score: number; findings: string[]; status: BarnStatus; eventId: string; auditId: string }
export interface BarnRestriction { id: string; barnId: string; stallId?: string; horseId?: string; type: 'quarantine' | 'maintenance' | 'security' | 'veterinary'; reason: string; active: boolean; createdAt: string; createdBy: string; approvalRequestId?: string; eventId: string; auditId: string }
export interface BarnTrainerAssignment { id: string; barnId: string; trainerId: string; assignedBy: string; assignedAt: string; active: boolean; auditId: string; eventId: string }
export interface VeterinaryVisitRecord { id: string; horseId: string; barnId: string; stallId?: string; veterinarianId: string; visitAt: string; findings: string[]; restrictionsCreated: string[]; eventId: string; auditId: string }
export interface BarnReadiness { barnId: string; status: BarnStatus; score: number; blockers: string[]; openRestrictions: number; occupiedStalls: number; capacity: number }

const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v)) as T;
const id = (p: string) => `${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
const rolePermissions: Record<Role, BarnPermission[]> = {
  admin: ['barn:read','barn:manage','stall:assign','movement:record','access:record','inspection:perform','vet:record','restriction:manage'],
  steward: ['barn:read','access:record'], veterinarian: ['barn:read','access:record','vet:record','restriction:manage'],
  'track-superintendent': ['barn:read','barn:manage','stall:assign','movement:record','inspection:perform','restriction:manage'],
  security: ['barn:read','access:record','restriction:manage'], 'racing-secretary': ['barn:read','stall:assign','movement:record'],
  'compliance-officer': ['barn:read','access:record'], 'read-only-auditor': ['barn:read'], finance: ['barn:read'], 'ticketing-manager': ['barn:read'],
};

export class CoordinatedBarnOperationsService {
  readonly eventBus: UniversalEventBus; readonly auditLog: ImmutableAuditLog; readonly approvals: CentralizedApprovalService;
  private barns = new Map<string, Barn>(); private stalls = new Map<string, Stall>(); private occupancy = new Map<string, HorseOccupancy>(); private movements: HorseMovementRecord[] = []; private access: BarnAccessRecord[] = []; private inspections: BarnInspection[] = []; private restrictions: BarnRestriction[] = []; private trainers: BarnTrainerAssignment[] = []; private vetVisits: VeterinaryVisitRecord[] = [];
  constructor(deps: { eventBus?: UniversalEventBus; auditLog?: ImmutableAuditLog; approvals?: CentralizedApprovalService } = {}) { this.eventBus = deps.eventBus ?? new UniversalEventBus(); this.auditLog = deps.auditLog ?? new ImmutableAuditLog(); this.approvals = deps.approvals ?? new CentralizedApprovalService({ auditLog: this.auditLog, eventBus: this.eventBus }); }
  createBarn(actor: BarnActor, barn: Barn, stalls: Array<Omit<Stall, 'barnId'|'status'|'restrictionIds'|'occupancyHorseId'>>): Barn { this.require(actor,'barn:manage'); this.barns.set(barn.id, clone(barn)); for (const s of stalls) this.stalls.set(s.id,{...s,barnId:barn.id,status:'available',restrictionIds:[]}); this.audit('barn.created', actor.id, barn.id, barn); void this.eventBus.publish({ type:'barn.created', payload:barn, aggregateId:barn.id, producer:'barn-operations', metadata:{ compliance:'regulated', team:'barn-operations', accountableRole:'track-superintendent' } }); return clone(barn); }
  assignHorse(input: { actor: BarnActor; horseId: string; barnId: string; stallId: string; assignedAt: string; reason: string; approvalToken?: ApprovalToken }): HorseOccupancy { this.require(input.actor,'stall:assign'); const stall = this.requireAssignable(input.stallId); if (input.barnId !== stall.barnId) throw new Error('stall does not belong to barn'); if (this.restrictions.some(r=>r.active && (r.barnId===input.barnId || r.stallId===input.stallId || r.horseId===input.horseId))) this.approvals.assertAuthorized(input.approvalToken, 'safety-critical-control', input.stallId, input.actor.tenantId, input.assignedAt); const previous = this.occupancy.get(input.horseId); if (previous?.stallId === input.stallId) return clone(previous); if ([...this.occupancy.values()].some(o=>o.stallId===input.stallId && o.horseId!==input.horseId)) throw new Error('stall already occupied'); if (previous) this.stalls.set(previous.stallId,{...this.stalls.get(previous.stallId)!,status:'available',occupancyHorseId:undefined}); stall.status='occupied'; stall.occupancyHorseId=input.horseId; this.stalls.set(stall.id, stall); const audit = this.audit('stall.assignment.changed', input.actor.id, input.horseId, { ...input, previous }); void this.eventBus.publish({ type:'barn.horse.assigned', payload:{ horseId:input.horseId,barnId:input.barnId,stallId:input.stallId,previous }, aggregateId:input.horseId, producer:'barn-operations', metadata:{ compliance:'regulated', team:'barn-operations', accountableRole:'racing-secretary' } }); void this.eventBus.publish({ type:'digital-twin.state.patch', payload:{ twinId:`equine:${input.horseId}`, patch:{ barnId:input.barnId, stallId:input.stallId, occupancyStatus:'stabled' }, actor:input.actor.id }, aggregateId:`equine:${input.horseId}`, producer:'barn-operations', metadata:{ compliance:'regulated', team:'barn-operations', accountableRole:'digital-twin-owner' } }); const occ = { horseId:input.horseId,barnId:input.barnId,stallId:input.stallId,assignedAt:input.assignedAt,assignedBy:input.actor.id,eventId:'barn.horse.assigned',auditId:audit.id,twinId:`equine:${input.horseId}` }; this.occupancy.set(input.horseId, occ); return clone(occ); }
  moveHorse(input: { actor: BarnActor; horseId: string; toBarnId: string; toStallId: string; reason: string; movedAt: string; approvalToken?: ApprovalToken }): HorseMovementRecord { this.require(input.actor,'movement:record'); const before = this.occupancy.get(input.horseId); const occ = this.assignHorse({ actor:input.actor, horseId:input.horseId, barnId:input.toBarnId, stallId:input.toStallId, reason:input.reason, assignedAt:input.movedAt, approvalToken:input.approvalToken }); const audit = this.audit('horse.movement.recorded', input.actor.id, input.horseId, { ...input, before, occupancy: occ }); void this.eventBus.publish({ type:'barn.horse.moved', payload:{ horseId:input.horseId, from:before, to:occ, reason:input.reason }, aggregateId:input.horseId, producer:'barn-operations', metadata:{ compliance:'regulated', team:'barn-operations', accountableRole:'racing-secretary' } }); const rec = { id:id('movement'), horseId:input.horseId, fromBarnId:before?.barnId, fromStallId:before?.stallId, toBarnId:input.toBarnId, toStallId:input.toStallId, reason:input.reason, movedAt:input.movedAt, movedBy:input.actor.id, eventId:'barn.horse.moved', auditId:audit.id, approvalRequestId:input.approvalToken?.requestId }; this.movements.push(rec); return clone(rec); }
  recordAccess(input: { actor: BarnActor; barnId: string; purpose: string; at: string }): BarnAccessRecord { this.require(input.actor,'access:record'); const audit = this.audit('barn.access.recorded', input.actor.id, input.barnId, input); void this.eventBus.publish({ type:'barn.access.recorded', payload:input, aggregateId:input.barnId, producer:'barn-operations', metadata:{ compliance:'restricted', team:'security', accountableRole:'security' } }); const rec = { id:id('access'), barnId:input.barnId, actorId:input.actor.id, purpose:input.purpose, accessAt:input.at, decision:'allowed' as const, eventId:'barn.access.recorded', auditId:audit.id }; this.access.push(rec); return clone(rec); }
  inspect(input: { actor: BarnActor; barnId: string; score: number; findings: string[]; at: string }): BarnInspection { this.require(input.actor,'inspection:perform'); const status: BarnStatus = input.score < 60 ? 'restricted' : input.score < 80 ? 'watch' : 'ready'; const barn = this.barns.get(input.barnId); if (barn) this.barns.set(input.barnId,{...barn,status}); const audit = this.audit('barn.inspected', input.actor.id, input.barnId, input); void this.eventBus.publish({ type:'barn.inspected', payload:{...input,status}, aggregateId:input.barnId, producer:'barn-operations', metadata:{ compliance:'regulated', team:'barn-operations', accountableRole:'track-superintendent' } }); const rec = { id:id('inspection'), barnId:input.barnId, inspectedBy:input.actor.id, inspectedAt:input.at, score:input.score, findings:[...input.findings], status, eventId:'barn.inspected', auditId:audit.id }; this.inspections.push(rec); return clone(rec); }
  createRestriction(input: { actor: BarnActor; barnId: string; stallId?: string; horseId?: string; type: BarnRestriction['type']; reason: string; at: string; approvalToken?: ApprovalToken }): BarnRestriction { this.require(input.actor,'restriction:manage'); if (input.type !== 'maintenance') this.approvals.assertAuthorized(input.approvalToken, 'safety-critical-control', input.stallId ?? input.barnId, input.actor.tenantId, input.at); const audit = this.audit('barn.restriction.created', input.actor.id, input.stallId ?? input.barnId, input); void this.eventBus.publish({ type:'barn.restriction.created', payload:input, aggregateId:input.stallId ?? input.barnId, producer:'barn-operations', metadata:{ compliance:'restricted', team:'barn-operations', accountableRole:'compliance-officer' } }); const rec = { id:id('restriction'), active:true, createdBy:input.actor.id, createdAt:input.at, eventId:'barn.restriction.created', auditId:audit.id, approvalRequestId:input.approvalToken?.requestId, ...input }; this.restrictions.push(rec); return clone(rec); }
  assignTrainer(input: { actor: BarnActor; barnId: string; trainerId: string; at: string }): BarnTrainerAssignment { this.require(input.actor,'barn:manage'); const audit = this.audit('barn.trainer.assigned', input.actor.id, input.barnId, input); void this.eventBus.publish({ type:'barn.trainer.assigned', payload:input, aggregateId:input.barnId, producer:'barn-operations', metadata:{ compliance:'regulated', team:'barn-operations', accountableRole:'racing-secretary' } }); const rec = { id:id('trainer'), barnId:input.barnId, trainerId:input.trainerId, assignedBy:input.actor.id, assignedAt:input.at, active:true, auditId:audit.id, eventId:'barn.trainer.assigned' }; this.trainers.push(rec); return clone(rec); }
  recordVeterinaryVisit(input: { actor: BarnActor; horseId: string; findings: string[]; at: string }): VeterinaryVisitRecord { this.require(input.actor,'vet:record'); const occ = this.occupancy.get(input.horseId); if (!occ) throw new Error('horse is not assigned to a stall'); const audit = this.audit('barn.veterinary-visit.recorded', input.actor.id, input.horseId, input); void this.eventBus.publish({ type:'barn.veterinary-visit.recorded', payload:{...input,occupancy:occ}, aggregateId:input.horseId, producer:'barn-operations', metadata:{ compliance:'restricted', team:'veterinary', accountableRole:'veterinarian' } }); const rec = { id:id('vet'), horseId:input.horseId, barnId:occ.barnId, stallId:occ.stallId, veterinarianId:input.actor.id, visitAt:input.at, findings:[...input.findings], restrictionsCreated:[], eventId:'barn.veterinary-visit.recorded', auditId:audit.id }; this.vetVisits.push(rec); return clone(rec); }
  readiness(): BarnReadiness[] { return [...this.barns.values()].map(b=>{ const open = this.restrictions.filter(r=>r.active && r.barnId===b.id).length; const occupied = [...this.occupancy.values()].filter(o=>o.barnId===b.id).length; const score = Math.max(0, 100 - open * 25 - (b.status==='watch'?10:0) - (b.status==='restricted'?35:0)); return { barnId:b.id, status:score<70?'restricted':score<85?'watch':'ready', score, blockers:this.restrictions.filter(r=>r.active&&r.barnId===b.id).map(r=>r.reason), openRestrictions:open, occupiedStalls:occupied, capacity:b.capacity }; }); }
  snapshot() { return clone({ barns:[...this.barns.values()], stalls:[...this.stalls.values()], occupancy:[...this.occupancy.values()], movements:this.movements, access:this.access, inspections:this.inspections, restrictions:this.restrictions, trainers:this.trainers, vetVisits:this.vetVisits, readiness:this.readiness() }); }
  private require(actor: BarnActor, permission: BarnPermission) { if (!actor.roles.some(r=>rolePermissions[r]?.includes(permission))) throw new Error(`Actor lacks ${permission}`); }
  private requireAssignable(stallId: string): Stall { const stall = this.stalls.get(stallId); if (!stall) throw new Error(`Unknown stall ${stallId}`); if (stall.status === 'maintenance' || stall.status === 'restricted') throw new Error(`stall ${stallId} is not assignable`); return { ...stall, restrictionIds:[...stall.restrictionIds] }; }
  private audit(action: string, actor: string, subjectId: string, payload: unknown) { return this.auditLog.append({ id:id('audit-barn'), type:'data-change', actor, timestamp:new Date().toISOString(), subjectId, payload:{ action, ...payload as object }, severity:'warning', regulations:['HISA','ARCI'] }); }
}

export function createSeededBarnOperationsService(): CoordinatedBarnOperationsService { const service = new CoordinatedBarnOperationsService(); const actor = { id:'ops-admin', roles:['admin'] as Role[], tenantId:'tenant-1' }; service.createBarn(actor,{ id:'barn-2', name:'Barn 2', tenantId:'tenant-1', location:'Backstretch', status:'ready', capacity:3, incidentIds:['incident-credential-1'], trainerIds:['trainer-1'] }, [{ id:'stall-12A', label:'12A' },{ id:'stall-12B', label:'12B' },{ id:'stall-12C', label:'12C' }]); service.assignHorse({ actor, horseId:'horse-1', barnId:'barn-2', stallId:'stall-12A', assignedAt:'2026-06-13T00:00:00.000Z', reason:'race-day stabling' }); service.assignTrainer({ actor, barnId:'barn-2', trainerId:'trainer-1', at:'2026-06-13T00:01:00.000Z' }); service.inspect({ actor, barnId:'barn-2', score:88, findings:['aisles clear','water available'], at:'2026-06-13T00:02:00.000Z' }); service.recordAccess({ actor:{ id:'security-1', roles:['security'], tenantId:'tenant-1' }, barnId:'barn-2', purpose:'credential patrol', at:'2026-06-13T00:03:00.000Z' }); return service; }
