import type { ApiServiceDefinition } from './enterpriseApiGateway.js';
import type { UniversalEventBus } from './eventBus.js';
import type { ImmutableAuditLog } from './auditLog.js';

type Severity = 'info' | 'advisory' | 'warning' | 'critical';
type Status = 'ready' | 'watch' | 'blocked';
const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v)) as T;
const id = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;

export interface OpsDeps { eventBus?: UniversalEventBus; auditLog?: ImmutableAuditLog }
export interface NotificationPreference { userId: string; channels: Array<'in-app'|'email'|'sms'|'radio'|'webhook'>; minimumSeverity: Severity; quietHours?: string }
export interface NotificationRecord { id: string; category: 'operations'|'safety'|'approval'|'compliance'|'maintenance'|'incident'|'weather'|'emergency'; severity: Severity; title: string; message: string; targetRoles: string[]; evidence: string[]; status: 'queued'|'delivered'|'acknowledged'|'escalated'; createdAt: string; acknowledgements: Array<{ actor: string; at: string }>; escalationChain: string[] }
export class NotificationAlertingService {
  private notifications = new Map<string, NotificationRecord>();
  private preferences = new Map<string, NotificationPreference>();
  constructor(private readonly deps: OpsDeps = {}) {}
  setPreference(pref: NotificationPreference) { this.preferences.set(pref.userId, clone(pref)); return clone(pref); }
  publish(input: Omit<NotificationRecord,'id'|'status'|'createdAt'|'acknowledgements'> & { id?: string; createdAt?: string }) { const record: NotificationRecord = { ...input, id: input.id ?? id('notification'), createdAt: input.createdAt ?? new Date().toISOString(), status: 'delivered', acknowledgements: [] }; this.notifications.set(record.id, record); this.deps.auditLog?.append({ id: id('audit-notification'), type: 'workflow-action', actor: 'notification-service', timestamp: record.createdAt, subjectId: record.id, severity: record.severity === 'critical' ? 'critical' : record.severity === 'warning' ? 'warning' : 'info', payload: record, regulations: ['HISA','ARCI'] }); void this.deps.eventBus?.publish({ type: `notification.${record.category}`, payload: record, aggregateId: record.id, producer: 'notification-alerting', metadata: { accountableRole: 'operations-commander' } }); return clone(record); }
  acknowledge(id: string, actor: string, at = new Date().toISOString()) { const n = this.require(id); n.status = 'acknowledged'; n.acknowledgements.push({ actor, at }); return clone(n); }
  escalate(id: string, role: string) { const n = this.require(id); n.status = 'escalated'; n.escalationChain = [...new Set([...n.escalationChain, role])]; return clone(n); }
  list(filter: Partial<Pick<NotificationRecord,'category'|'severity'|'status'>> = {}) { return [...this.notifications.values()].filter((n) => (!filter.category || n.category === filter.category) && (!filter.severity || n.severity === filter.severity) && (!filter.status || n.status === filter.status)).map(clone); }
  private require(notificationId: string) { const n = this.notifications.get(notificationId); if (!n) throw new Error(`Unknown notification ${notificationId}`); return n; }
}

export interface WorkforceProfile { id: string; name: string; role: string; certifications: Array<{ name: string; expiresAt: string }>; shift: { startsAt: string; endsAt: string }; assignment?: string; checkedIn: boolean; trainingRecords: string[]; incidentAssignments: string[] }
export class WorkforceOperationsService { private profiles = new Map<string, WorkforceProfile>(); upsert(profile: WorkforceProfile) { this.profiles.set(profile.id, clone(profile)); return clone(profile); } readiness(now = new Date().toISOString()) { const profiles = [...this.profiles.values()]; const expired = profiles.flatMap((p) => p.certifications.filter((c) => c.expiresAt <= now).map((c) => `${p.id}:${c.name}`)); const checkedIn = profiles.filter((p) => p.checkedIn).length; const score = profiles.length ? Math.max(0, Math.round((checkedIn / profiles.length) * 100) - expired.length * 10) : 0; return { generatedAt: now, score, status: score >= 90 ? 'ready' as Status : score >= 70 ? 'watch' as Status : 'blocked' as Status, headcount: profiles.length, checkedIn, expiredCredentials: expired, assignments: profiles.map((p) => ({ workerId: p.id, role: p.role, assignment: p.assignment, incidents: p.incidentAssignments })) }; } list() { return [...this.profiles.values()].map(clone); } }

export interface BarnRecord { id: string; name: string; stalls: number; occupied: number; horses: Array<{ horseId: string; stall: string; trainer: string }>; movements: Array<{ horseId: string; from: string; to: string; at: string; actor: string }>; inspections: Array<{ at: string; status: Status; evidence: string[] }>; accessEvents: Array<{ actor: string; area: string; at: string; decision: 'granted'|'denied' }> }
export class BarnOperationsService { private barns = new Map<string, BarnRecord>(); upsert(record: BarnRecord) { this.barns.set(record.id, clone(record)); return clone(record); } recordMovement(barnId: string, movement: BarnRecord['movements'][number]) { const barn = this.require(barnId); barn.movements.push(movement); return clone(barn); } occupancyDashboard() { const barns = [...this.barns.values()]; return { barns: barns.map((b) => ({ id: b.id, name: b.name, stalls: b.stalls, occupied: b.occupied, utilization: Math.round((b.occupied / Math.max(1, b.stalls)) * 100), latestInspection: b.inspections.at(-1) })), movements: barns.flatMap((b) => b.movements.map((m) => ({ barnId: b.id, ...m }))) }; } private require(barnId: string) { const barn = this.barns.get(barnId); if (!barn) throw new Error(`Unknown barn ${barnId}`); return barn; } }

export interface FacilityAssetHealth { assetId: string; name: string; type: 'lighting'|'irrigation'|'generator'|'vehicle'|'camera'|'communications'|'security-manager'|'gate'|'emergency-equipment'; healthScore: number; status: Status; inspections: string[]; maintenanceHistory: string[]; predictedFailureRisk: number; incidents: string[]; twinId?: string }
export class FacilityAssetHealthService { private assets = new Map<string, FacilityAssetHealth>(); upsert(asset: FacilityAssetHealth) { this.assets.set(asset.assetId, clone(asset)); return clone(asset); } dashboard() { const assets = [...this.assets.values()]; return { generatedAt: new Date().toISOString(), averageHealth: assets.length ? Math.round(assets.reduce((s, a) => s + a.healthScore, 0) / assets.length) : 0, critical: assets.filter((a) => a.status === 'blocked').length, watch: assets.filter((a) => a.status === 'watch').length, assets: assets.map(clone), predictiveMaintenance: assets.filter((a) => a.predictedFailureRisk >= 70).map((a) => ({ assetId: a.assetId, risk: a.predictedFailureRisk, evidence: [...a.inspections, ...a.incidents] })) }; } }

export interface KpiMetric { id: string; label: string; domain: string; value: number; unit: string; trend: 'up'|'down'|'flat'; source: string; evidence: string[] }
export class ExecutiveKpiIntelligenceService { constructor(private readonly metrics: KpiMetric[] = []) {} addMetric(metric: KpiMetric) { this.metrics.push(clone(metric)); return clone(metric); } dashboard() { return { generatedAt: new Date().toISOString(), metrics: this.metrics.map(clone), benchmarks: this.metrics.map((m) => ({ metricId: m.id, benchmark: m.value >= 90 ? 'leading' : m.value >= 75 ? 'stable' : 'needs-attention' })), exportFormats: ['csv','json','pdf'], drillDowns: this.metrics.map((m) => ({ metricId: m.id, route: `/${m.domain}` })) }; } }

export interface ServiceHealthSignal { service: string; status: 'healthy'|'degraded'|'down'; latencyMs: number; eventThroughput: number; dependencyOf: string[]; telemetryQuality: number; aiHealthy?: boolean }
export class PlatformHealthService { private signals = new Map<string, ServiceHealthSignal>(); upsert(signal: ServiceHealthSignal) { this.signals.set(signal.service, clone(signal)); return clone(signal); } diagnostics() { const signals = [...this.signals.values()]; return { generatedAt: new Date().toISOString(), services: signals.map(clone), apiHealth: signals.filter((s) => s.status !== 'down').length / Math.max(1, signals.length), eventThroughput: signals.reduce((s, v) => s + v.eventThroughput, 0), digitalTwinSync: signals.some((s) => s.service.includes('digital-twin') && s.status !== 'healthy') ? 'degraded' : 'healthy', approvalProcessing: signals.find((s) => s.service.includes('approval'))?.status ?? 'degraded', auditVolume: signals.reduce((s, v) => s + Math.round(v.eventThroughput / 10), 0), dependencyMap: signals.flatMap((s) => s.dependencyOf.map((target) => ({ source: s.service, target }))), alerts: signals.filter((s) => s.status !== 'healthy' || s.telemetryQuality < 90).map((s) => ({ service: s.service, severity: s.status === 'down' ? 'critical' : 'warning', message: `${s.service} requires diagnostics` })) }; } }

export function dailyOperationsApiDefinitions(): ApiServiceDefinition[] { const owner = { team: 'racetrack-platform', productOwner: 'Director of Operations Technology', technicalOwner: 'Daily Operations Platform Owner', supportChannel: '#trackmind-ops' }; return ['notifications','workforce','barn-operations','facility-asset-health','executive-kpi','platform-health'].map((name) => ({ id: name, name, domain: 'operations', version: 'v1', basePath: `/api/v1/${name}`, description: `${name} service for the TrackMind Nexus daily operational experience.`, owner, lifecycle: 'active' as const, auth: ['jwt','oauth2','mtls'], rateLimit: { requests: 600, perSeconds: 60, burst: 100 }, tags: ['operations','digital-twin','audit'], slo: { availability: 99.9, latencyMs: 250 }, endpoints: [{ method: 'GET' as const, path: '/dashboard', summary: 'Read operational dashboard state', scopes: ['read:any'] }, { method: 'POST' as const, path: '/events', summary: 'Publish governed operational event', scopes: ['incident:manage'] }] })); }
