export type Sensitivity = 'public' | 'internal' | 'confidential' | 'restricted';
export type ApprovalStatus = 'draft' | 'pending-approval' | 'approved' | 'rejected';
export interface DataSourceDescriptor { id: string; domain: string; system: string; tenantId?: string; sensitivity: Sensitivity; owner: string; regulatoryBoundary?: string }
export interface OntologyEntity { name: string; description: string; attributes: string[]; relationships: string[] }
export interface SchemaMapping { sourceId: string; targetEntity: string; fieldMap: Record<string, string>; transformations: string[]; lineage: string[] }
export interface MetadataRecord { assetId: string; owner: string; steward: string; classification: Sensitivity; retention: string; qualityScore: number; tags: string[] }

export function unifiedOperationalKnowledgeLayer(sources: DataSourceDescriptor[]) {
  const domains = [...new Set(sources.map((source) => source.domain))];
  return { ontology: trackMindOntology(), domains, sources: sources.map((s) => ({ ...s })), semanticModel: ['Race', 'Horse', 'Asset', 'Incident', 'WorkOrder', 'Evidence', 'Control', 'Recommendation', 'Regulation'], capabilities: ['schema-mapping', 'metadata-catalog', 'lineage-tracking', 'semantic-search', 'graph-relationships', 'knowledge-versioning', 'governance-workflows', 'auditable-apis'], trusted: sources.every((source) => !!source.owner && !!source.sensitivity) };
}
export function trackMindOntology(): OntologyEntity[] { return [
  { name: 'Horse', description: 'Registered equine athlete and welfare lifecycle subject', attributes: ['horseId', 'registration', 'welfareStatus'], relationships: ['PARTICIPATES_IN', 'HAS_WELFARE_EVENT', 'ASSIGNED_TO'] },
  { name: 'Race', description: 'Race-day operational event', attributes: ['raceId', 'surface', 'scheduledAt', 'status'], relationships: ['USES_SURFACE', 'HAS_EVIDENCE', 'GOVERNED_BY'] },
  { name: 'FacilityAsset', description: 'Infrastructure, venue, or digital-twin asset', attributes: ['assetId', 'assetType', 'health', 'criticality'], relationships: ['LOCATED_AT', 'MAINTAINED_BY', 'MONITORED_BY'] },
  { name: 'Control', description: 'Operational, security, privacy, AI, or compliance control', attributes: ['controlId', 'framework', 'owner', 'status'], relationships: ['PRODUCES_EVIDENCE', 'MITIGATES_RISK'] },
  { name: 'Recommendation', description: 'Explainable AI or analytical recommendation requiring human authority', attributes: ['recommendationId', 'confidence', 'rationale', 'status'], relationships: ['SUPPORTED_BY', 'APPROVED_BY'] },
]; }
export class MetadataCatalog { private readonly records = new Map<string, MetadataRecord>(); register(record: MetadataRecord) { this.records.set(record.assetId, { ...record, tags: [...record.tags] }); return this.records.get(record.assetId)!; } findByTag(tag: string) { return [...this.records.values()].filter((r) => r.tags.includes(tag)).map((r) => ({ ...r, tags: [...r.tags] })); } score() { const values = [...this.records.values()]; return Math.round(values.reduce((s, r) => s + r.qualityScore, 0) / Math.max(1, values.length)); } }
export class LineageTracker { private readonly edges: Array<{ from: string; to: string; operation: string; actor: string; timestamp: string }> = []; link(edge: { from: string; to: string; operation: string; actor: string; timestamp: string }) { this.edges.push({ ...edge }); return edge; } trace(assetId: string) { return this.edges.filter((e) => e.from === assetId || e.to === assetId).map((e) => ({ ...e })); } }
export class SemanticSearchIndex { private readonly docs: Array<{ id: string; text: string; metadata: Record<string, unknown> }> = []; add(doc: { id: string; text: string; metadata?: Record<string, unknown> }) { this.docs.push({ id: doc.id, text: doc.text.toLowerCase(), metadata: { ...(doc.metadata ?? {}) } }); return doc.id; } search(query: string) { const terms = query.toLowerCase().split(/\s+/).filter(Boolean); return this.docs.map((doc) => ({ id: doc.id, score: terms.filter((term) => doc.text.includes(term)).length, metadata: { ...doc.metadata } })).filter((r) => r.score > 0).sort((a, b) => b.score - a.score); } }
export class KnowledgeVersionStore<T extends { id: string }> { private readonly versions = new Map<string, Array<T & { version: number; approvedBy?: string }>>(); commit(item: T, approvedBy?: string) { const stream = this.versions.get(item.id) ?? []; const next = { ...item, version: stream.length + 1, approvedBy }; stream.push(next); this.versions.set(item.id, stream); return next; } history(id: string) { return [...(this.versions.get(id) ?? [])]; } latest(id: string) { return this.history(id).at(-1); } }
export function governanceWorkflow(request: { id: string; sensitivity: Sensitivity; approvers: string[]; evidence: string[] }): { id: string; status: ApprovalStatus; requiredControls: string[] } { const needsDual = request.sensitivity === 'restricted' || request.sensitivity === 'confidential'; const status = request.evidence.length > 0 && request.approvers.length >= (needsDual ? 2 : 1) ? 'approved' : 'pending-approval'; return { id: request.id, status, requiredControls: ['data-owner-review', 'steward-attestation', 'audit-log', ...(needsDual ? ['dual-authorization'] : [])] }; }

export function globalRacingIntelligenceNetwork(tracks: Array<{ tenantId: string; region: string; regulations: string[] }>) { return { trackCount: tracks.length, tenantIsolation: ['row-level-security', 'tenant-scoped-keys', 'policy-decision-point', 'clean-room-analytics'], analytics: ['federated-analytics', 'cross-track-benchmarking', 'anonymized-safety-studies', 'maintenance-effectiveness', 'weather-patterns', 'incident-discovery'], sharingAllowed: tracks.every((t) => t.regulations.length > 0), benchmarkCohorts: [...new Set(tracks.map((t) => t.region))] }; }
export function federatedBenchmark(metrics: Array<{ tenantId: string; metric: string; value: number; shareable: boolean }>) { const safe = metrics.filter((m) => m.shareable); const avg = safe.reduce((s, m) => s + m.value, 0) / Math.max(1, safe.length); return { participants: new Set(safe.map((m) => m.tenantId)).size, average: Number(avg.toFixed(2)), anonymized: true, suppressed: metrics.length - safe.length }; }
export function equineWelfareIntelligencePlatform(record: { horseId: string; lifecycleEvents: string[]; welfareAlerts: number; veterinarianApproved: boolean }) { return { horseId: record.horseId, lifecycleCoverage: ['registration', 'training', 'racing', 'rehabilitation', 'retirement', 'post-racing-care'], workflows: ['assessment', 'retirement-planning', 'rehab-tracking', 'adoption-records', 'compliance-review'], decisionMaker: 'authorized-veterinarian-or-welfare-officer', eligible: record.veterinarianApproved && record.welfareAlerts === 0, explainableReport: record.lifecycleEvents }; }
export function trackMaintenanceIntelligence(input: { workOrders: number; weatherRisk: number; inventoryReadiness: number; humanApproved?: boolean }) { const score = Math.max(0, Math.min(100, 100 - input.weatherRisk * 10 + input.inventoryReadiness - input.workOrders)); return { qualityScore: Math.round(score), optimizedPlan: ['surface-inspection', 'equipment-staging', 'crew-allocation', 'post-work-validation'], executionRequiresHumanApproval: true, approvedForExecution: !!input.humanApproved }; }
export function infrastructureDigitalTwin(assets: Array<{ id: string; type: string; health: number; criticality: number }>) { return { assetCount: assets.length, modeledSystems: ['electrical', 'generators', 'irrigation', 'lighting', 'hvac', 'communications', 'security', 'transportation', 'emergency-equipment', 'utilities'], risks: assets.filter((a) => a.health < 70 || a.criticality >= 4).map((a) => a.id), capabilities: ['health-monitoring', 'fault-detection', 'lifecycle-management', 'spare-parts-planning', 'capacity-forecasting'] }; }
export function workforceManagementPlatform(input: { demand: number; available: number; certificationsValid: number; managerApproved?: boolean }) { return { staffingGap: Math.max(0, input.demand - input.available), complianceReady: input.certificationsValid >= input.demand, recommendationRequiresManagementApproval: true, scheduleChangeApproved: !!input.managerApproved, workflows: ['forecasting', 'scheduling', 'credentialing', 'training', 'emergency-staffing'] }; }
export function venueIntelligencePlatform(input: { occupancyPct: number; parkingPct: number; securityCoveragePct: number }) { const bottlenecks = [input.occupancyPct > 85 ? 'crowd-flow' : '', input.parkingPct > 90 ? 'parking' : '', input.securityCoveragePct < 80 ? 'security-coverage' : ''].filter(Boolean); return { bottlenecks, recommendations: bottlenecks.map((b) => `increase-${b}-resources`), explainable: true, auditable: true }; }
export function enterpriseDataGovernanceFramework() { return ['data-quality', 'master-data', 'metadata-governance', 'ownership', 'retention', 'legal-hold', 'privacy-classification', 'lineage', 'stewardship', 'regulatory-reporting'].map((capability) => ({ capability, automatedMonitoring: true })); }
export function federatedAiResearchEnvironment(approved: boolean) { return { productionSeparated: true, syntheticData: true, experimentTracking: true, deploymentGate: approved ? 'ready-for-review' : 'blocked', liveOperationsImpact: 'prohibited' }; }
export function digitalEvidenceManagementPlatform(items: Array<{ id: string; signed: boolean; retainedUntil: string }>) { return { evidenceCount: items.length, chainOfCustody: items.every((i) => i.signed), workflows: ['retention', 'access-control', 'digital-signature', 'evidentiary-timeline', 'legal-discovery'] }; }
export function notificationCommunicationsPlatform(alerts: Array<{ id: string; severity: 'low'|'medium'|'high'|'critical'; acknowledged: boolean }>) { return { total: alerts.length, escalations: alerts.filter((a) => ['high','critical'].includes(a.severity) && !a.acknowledged).length, capabilities: ['templates', 'multilingual', 'acknowledgment', 'escalation', 'audit-log'] }; }
export function geospatialIntelligencePlatform(layers: string[]) { return { layers, supported: ['assets', 'weather', 'maintenance', 'emergency-resources', 'security-incidents', 'crowd-movement'], capabilities: ['geofencing', 'route-optimization', 'incident-overlays', 'simulation-playback', 'digital-twin-integration'] }; }
export function financialIntelligencePlatform(input: { revenue: number; costs: number; capitalNeeds: number }) { return { margin: input.revenue - input.costs, scenarios: ['base', 'downside', 'investment'], capitalRisk: input.capitalNeeds > input.revenue * 0.25 ? 'elevated' : 'normal', dashboards: ['forecast', 'risk', 'budget', 'executive'] }; }
export function sustainabilityEnvironmentalPlatform(input: { energy: number; water: number; wasteDiversionPct: number }) { const score = Math.max(0, Math.min(100, 100 - input.energy / 1000 - input.water / 1000 + input.wasteDiversionPct / 2)); return { sustainabilityScore: Math.round(score), scorecards: ['energy', 'water', 'waste', 'emissions', 'compliance'], recommendations: ['optimize-irrigation', 'reduce-peak-energy', 'increase-diversion'] }; }
export function vendorPartnerManagementSystem(vendors: Array<{ id: string; insured: boolean; compliant: boolean; sla: number }>) { return { vendors: vendors.length, auditReady: vendors.every((v) => v.insured && v.compliant), renewalsAtRisk: vendors.filter((v) => v.sla < 0.95).map((v) => v.id), workflows: ['onboarding', 'contracting', 'insurance', 'risk-assessment', 'renewal'] }; }
export function enterpriseRiskManagementPlatform(risks: Array<{ id: string; likelihood: number; impact: number; controlEffectiveness: number }>) { return { standard: 'ISO 31000', risks: risks.map((r) => ({ id: r.id, inherent: r.likelihood * r.impact, residual: Number((r.likelihood * r.impact * (1 - r.controlEffectiveness)).toFixed(2)) })), workflows: ['identify', 'assess', 'map-controls', 'mitigate', 'track-issues', 'report'] }; }
export function enterpriseObservabilityPlatform(signals: Array<{ service: string; errors: number; latencyMs: number }>) { return { services: new Set(signals.map((s) => s.service)).size, unhealthy: signals.filter((s) => s.errors > 0 || s.latencyMs > 1000).map((s) => s.service), capabilities: ['metrics', 'logs', 'traces', 'anomaly-detection', 'capacity-planning', 'incident-response'] }; }
export function continuousComplianceAssuranceEngine(controls: Array<{ id: string; passed: boolean; evidence: string[] }>) { const passed = controls.filter((c) => c.passed && c.evidence.length > 0).length; return { score: Math.round((passed / Math.max(1, controls.length)) * 100), evidencePackages: controls.flatMap((c) => c.evidence), outputs: ['audit-report', 'readiness-assessment', 'scorecard', 'remediation-plan', 'executive-summary'] }; }
export function strategicIntelligenceForecastingPlatform(signals: Array<{ domain: string; trend: number }>) { const trend = signals.reduce((s, x) => s + x.trend, 0) / Math.max(1, signals.length); return { outlook: trend >= 0 ? 'favorable' : 'watch', domains: [...new Set(signals.map((s) => s.domain))], outputs: ['predictive-scenarios', 'strategic-recommendations', 'investment-roadmap', 'board-report'] }; }
export function trackMindNexusEnterpriseOperatingModel() { return { organization: ['enterprise-command-center', 'track-operations', 'safety-and-welfare', 'data-and-ai-governance', 'security-and-compliance'], committees: ['AI oversight', 'risk committee', 'change advisory board', 'data governance council'], processes: ['service-management', 'incident-management', 'business-continuity', 'disaster-recovery', 'accreditation'], roadmap: ['year-1-foundation', 'year-2-federation', 'year-3-intelligence', 'year-4-optimization', 'year-5-industry-network'] }; }
