import { ImmutableAuditLog, type AuditLogEntry } from './auditLog.js';
import type { CanonicalEventRef } from '@trackmind/shared';
import { DigitalTwinRuntimeEngine, type AssetState } from './enterpriseArchitecture.js';
import { UniversalEventBus, type RaceDayEvent } from './eventBus.js';
import { CentralizedApprovalService } from './approvals.js';
import { nonDiagnosticRiskScore, type HorseSafetyProfile } from './horseSafety.js';

export type EquinePrivacyScope = 'public' | 'racing-officials' | 'care-team' | 'regulator' | 'veterinary-confidential';
export type EquineLifecycleStatus = 'active' | 'inactive' | 'retired' | 'deceased';
export type EquineComplianceStatus = 'compliant' | 'under-review' | 'suspended' | 'ineligible';
export type EquineDomainEventType = `equine.${string}`;
export type EquineRelationshipType = 'owned-by' | 'trained-by' | 'treated-by' | 'transported-by' | 'entered-in-race' | 'worked-at-track' | 'assigned-to-barn' | 'mirrored-by-digital-twin' | 'retired-to';
export type AIRecommendationDomain = 'health' | 'welfare' | 'eligibility' | 'training' | 'transportation' | 'retirement';
export type AIRecommendationStatus = 'advisory' | 'pending-veterinarian-review' | 'veterinarian-reviewed' | 'rejected' | 'operationalized';

export interface EquineActor { id: string; roles: Array<'owner' | 'trainer' | 'veterinarian' | 'racing-secretary' | 'steward' | 'compliance-officer' | 'welfare-officer' | 'transport-coordinator' | 'auditor' | 'ai-agent'>; tenantId: string; human?: boolean }
export interface EquineIdentity { horseId: string; tenantId: string; racetrackId?: string; name: string; microchipId?: string; foaled?: string; sex?: 'colt' | 'filly' | 'gelding' | 'mare' | 'stallion'; breed?: string; lifecycleStatus: EquineLifecycleStatus }
export interface OwnershipRecord { ownerId: string; ownerName: string; effectiveFrom: string; effectiveTo?: string; percentage: number; evidence: string[] }
export interface TrainerAssignment { trainerId: string; trainerName: string; effectiveFrom: string; effectiveTo?: string; licenseStatus: 'active' | 'expired' | 'suspended'; evidence: string[] }
export interface RaceHistoryRecord { raceId: string; date: string; trackId: string; finishPosition?: number; status: 'entered' | 'started' | 'scratched' | 'completed' | 'disqualified'; stewardNotes?: string; evidence: string[] }
export interface WorkoutRecord { workoutId: string; date: string; trackId: string; distanceFurlongs: number; timeSeconds: number; surface: string; source: string }
export interface TransportationRecord { tripId: string; from: string; to: string; departedAt: string; arrivedAt?: string; transporter: string; welfareChecks: string[] }
export interface VeterinaryRecord { recordId: string; recordedAt: string; veterinarianId: string; category: 'exam' | 'medication' | 'injury' | 'clearance' | 'lab' | 'ai-review'; summary: string; privacyScope: EquinePrivacyScope; restrictions?: string[]; recommendationId?: string }
export interface WelfareRecord { recordId: string; observedAt: string; observerId: string; score: number; notes: string; interventions: string[] }
export interface BarnAssignment { barnId: string; stallId?: string; assignedAt: string; releasedAt?: string; assignedBy: string; evidence: string[] }
export interface DigitalTwinReference { twinId: string; twinType: 'horse' | 'biometric' | 'location' | 'training' | 'veterinary'; sourceSystem: string; relationship: 'primary' | 'sensor-feed' | 'analytics-shadow'; lastSyncedAt?: string; readOnly: boolean }
export interface VeterinaryStatusPlaceholder { status: 'not-recorded' | 'pending-exam' | 'cleared' | 'restricted'; summary: string; updatedAt: string; requiresVeterinarian: true }
export interface EquineEligibilityStatus { eligible: boolean; complianceStatus: EquineComplianceStatus; failedRules: string[]; flags: string[]; updatedAt: string }
export interface EquineWelfareStatus { level: 'unknown' | 'acceptable' | 'monitor' | 'intervention-required'; latestScore?: number; latestObservedAt?: string; interventions: string[] }
export interface RetirementRecord { retiredAt: string; reason: string; destination: string; aftercareContact?: string; evidence: string[] }
export interface HorseBreedingMetadata { sireId?: string; sireName?: string; damId?: string; damName?: string; breedingDate?: string; foalingDate?: string; studBook?: string; breedRegistry?: string; color?: string; markings?: string[]; breederId?: string; breederName?: string }
export interface HorseRegistrationRecord { recordId: string; authority: string; registrationNumber: string; registrationType: 'racing' | 'breeding' | 'microchip' | 'passport' | 'stud-book'; effectiveFrom: string; effectiveTo?: string; status: 'active' | 'suspended' | 'revoked' | 'pending'; evidence: string[]; recordedAt: string }
export interface OperationalEvent { eventId: string; occurredAt: string; type: string; actorId: string; summary: string; evidence: string[] }
export interface EligibilityRule { id: string; description: string; evaluate: (profile: EquineProfile) => boolean; failureStatus: EquineComplianceStatus }
export interface EquineEventStreamEntry extends Pick<CanonicalEventRef, 'eventId' | 'eventType' | 'tenantId' | 'racetrackId' | 'actorId' | 'source' | 'timestamp' | 'version'> { sequence: number; occurredAt: string; type: EquineDomainEventType; payload: unknown; twinSynced: boolean; auditId: string }
export interface EquineRelationship { id: string; type: EquineRelationshipType; fromId: string; toId: string; effectiveFrom: string; effectiveTo?: string; evidence: string[] }
export interface EquineApprovalRecord { id: string; recommendationId?: string; externalRequestId?: string; action: string; status: 'pending' | 'approved' | 'rejected'; requestedBy: string; reviewedBy?: string; reviewedAt?: string; reason?: string; evidence: string[]; requiredRole: EquineActor['roles'][number] }
export interface EquineAIRecommendation { id: string; horseId: string; tenantId: string; domain: AIRecommendationDomain; createdAt: string; requestedBy: string; modelId: string; summary: string; confidence: number; proposedOperationalAction?: 'add-eligibility-flag' | 'add-veterinary-restriction' | 'clear-to-race' | 'adjust-training' | 'transport-welfare-check'; advisoryOnly: boolean; status: AIRecommendationStatus; veterinarianReviewRequired: boolean; veterinarianReview?: { veterinarianId: string; reviewedAt: string; decision: 'approved' | 'rejected'; reason: string; evidence: string[] }; evidence: string[] }
export type AIRecommendationHook = (profile: EquineProfile) => EquineAIRecommendation[];

export interface EquinePlatformDeps { twinRuntime?: DigitalTwinRuntimeEngine; auditLog?: ImmutableAuditLog; eventBus?: UniversalEventBus; approvalService?: CentralizedApprovalService; rules?: EligibilityRule[] }
export interface BarnOperationsHorseAssignment { horseId: string; barnId: string; stallId?: string; assignedAt: string; assignedBy: string; eventId: string; auditId: string; twinId?: string }
export interface RaceOfficeHorseEntry { raceId: string; raceDate: string; trackId: string; trainerId: string; ownerId: string; status: RaceHistoryRecord['status']; finishPosition?: number; evidence: string[] }
export interface EquineObservabilitySnapshot { generatedAt: string; profiles: number; tenantIds: string[]; pendingVeterinarianReviews: number; openApprovals: number; auditRecords: number; eventCount: number; twinStates: number; ineligibleProfiles: number; advisoryRecommendations: number }

export interface EquineProfile {
  identity: EquineIdentity; ownershipHistory: OwnershipRecord[]; trainerAssignments: TrainerAssignment[]; racingHistory: RaceHistoryRecord[]; workouts: WorkoutRecord[]; transportationRecords: TransportationRecord[]; veterinaryRecords: VeterinaryRecord[]; veterinaryStatus: VeterinaryStatusPlaceholder; welfareRecords: WelfareRecord[]; barnAssignments: BarnAssignment[]; breedingMetadata: HorseBreedingMetadata; registrationRecords: HorseRegistrationRecord[]; digitalTwinReferences: DigitalTwinReference[]; retirementRecord?: RetirementRecord; complianceStatus: EquineComplianceStatus; eligibilityFlags: string[]; operationalHistory: OperationalEvent[]; twinId: string; relationships: EquineRelationship[]; approvals: EquineApprovalRecord[]; aiRecommendations: EquineAIRecommendation[]; eventStream: EquineEventStreamEntry[]; version: number; updatedAt: string;
}

const readScopesByRole: Record<EquineActor['roles'][number], EquinePrivacyScope[]> = { owner: ['public', 'racing-officials', 'care-team'], trainer: ['public', 'racing-officials', 'care-team'], veterinarian: ['public', 'racing-officials', 'care-team', 'veterinary-confidential'], 'racing-secretary': ['public', 'racing-officials'], steward: ['public', 'racing-officials', 'regulator'], 'compliance-officer': ['public', 'racing-officials', 'care-team', 'regulator', 'veterinary-confidential'], 'welfare-officer': ['public', 'racing-officials', 'care-team', 'regulator'], 'transport-coordinator': ['public', 'care-team'], auditor: ['public', 'racing-officials', 'regulator'], 'ai-agent': ['public'] };

export const defaultEligibilityRules: EligibilityRule[] = [
  { id: 'active-lifecycle', description: 'Horse must be active', evaluate: (p) => p.identity.lifecycleStatus === 'active', failureStatus: 'ineligible' },
  { id: 'no-active-compliance-flags', description: 'No open eligibility flags', evaluate: (p) => p.eligibilityFlags.length === 0, failureStatus: 'under-review' },
  { id: 'trainer-license-active', description: 'Current trainer license must be active', evaluate: (p) => !currentTrainer(p) || currentTrainer(p)?.licenseStatus === 'active', failureStatus: 'suspended' },
  { id: 'recent-welfare-ok', description: 'Latest welfare score must be at least 70', evaluate: (p) => latest(p.welfareRecords)?.score === undefined || latest(p.welfareRecords)!.score >= 70, failureStatus: 'under-review' },
  { id: 'no-unreviewed-health-ai', description: 'Health AI recommendations must not affect operations before veterinarian review', evaluate: (p) => !p.aiRecommendations.some((r) => r.domain === 'health' && r.proposedOperationalAction && r.status !== 'veterinarian-reviewed' && r.status !== 'operationalized'), failureStatus: 'under-review' },
];

const id = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 9)}`;

export class EquineIntelligencePlatform {
  private readonly profiles = new Map<string, EquineProfile>();
  private readonly audit: ImmutableAuditLog;
  private readonly eventBus: UniversalEventBus;
  private readonly twinRuntime: DigitalTwinRuntimeEngine;
  private readonly approvalService?: CentralizedApprovalService;
  private readonly rules: EligibilityRule[];
  private readonly aiHooks: AIRecommendationHook[] = [];
  private eventSequence = 0;

  constructor(depsOrTwin?: EquinePlatformDeps | DigitalTwinRuntimeEngine, rules = defaultEligibilityRules) {
    if (depsOrTwin instanceof DigitalTwinRuntimeEngine) {
      this.twinRuntime = depsOrTwin;
      this.rules = rules;
      this.audit = new ImmutableAuditLog();
      this.eventBus = new UniversalEventBus();
      return;
    }
    const deps = depsOrTwin ?? {};
    this.twinRuntime = deps.twinRuntime ?? new DigitalTwinRuntimeEngine();
    this.audit = deps.auditLog ?? new ImmutableAuditLog();
    this.eventBus = deps.eventBus ?? new UniversalEventBus();
    this.approvalService = deps.approvalService;
    this.rules = deps.rules ?? rules;
  }

  createProfile(identity: EquineIdentity, actor: EquineActor): EquineProfile {
    this.requireTenant(identity.tenantId, actor); this.requireRole(actor, ['racing-secretary', 'compliance-officer']); if (this.profiles.has(identity.horseId)) throw new Error('Equine profile already exists');
    const now = new Date().toISOString();
    const profile: EquineProfile = { identity: { ...identity }, ownershipHistory: [], trainerAssignments: [], racingHistory: [], workouts: [], transportationRecords: [], veterinaryRecords: [], veterinaryStatus: { status: 'not-recorded', summary: 'Veterinary status placeholder pending licensed veterinarian update.', updatedAt: now, requiresVeterinarian: true }, welfareRecords: [], barnAssignments: [], breedingMetadata: {}, registrationRecords: [], digitalTwinReferences: [{ twinId: `equine:${identity.horseId}`, twinType: 'horse', sourceSystem: 'trackmind-digital-twin', relationship: 'primary', lastSyncedAt: now, readOnly: true }], complianceStatus: 'under-review', eligibilityFlags: [], operationalHistory: [], twinId: `equine:${identity.horseId}`, relationships: [], approvals: [], aiRecommendations: [], eventStream: [], version: 1, updatedAt: now };
    const next = this.appendDomainEvent(profile, actor, 'equine.profile.created', { identity }, 'profile-created'); this.profiles.set(identity.horseId, structuredClone(next)); this.syncTwin(next, actor, 'profile-created'); return this.clone(next);
  }

  recordLifecycleEvent(horseId: string, patch: Partial<Omit<EquineProfile, 'identity' | 'twinId' | 'version' | 'updatedAt' | 'eventStream' | 'relationships' | 'approvals' | 'aiRecommendations'>> & { identity?: Partial<EquineIdentity>; operationalEvent?: OperationalEvent }, actor: EquineActor, reason: string): EquineProfile {
    this.requireRole(actor, ['racing-secretary', 'compliance-officer', 'veterinarian', 'welfare-officer', 'transport-coordinator', 'trainer']);
    const current = this.getWritable(horseId, actor); const next: EquineProfile = { ...current, ...patch, identity: { ...current.identity, ...(patch.identity ?? {}) }, operationalHistory: patch.operationalEvent ? [...current.operationalHistory, patch.operationalEvent] : current.operationalHistory, relationships: this.deriveRelationships({ ...current, ...patch } as EquineProfile), version: current.version + 1, updatedAt: new Date().toISOString() };
    next.complianceStatus = this.evaluateEligibility(next).complianceStatus; const withEvent = this.appendDomainEvent(next, actor, `equine.lifecycle.${reason}` as EquineDomainEventType, { changes: Object.keys(patch) }, reason); this.profiles.set(horseId, structuredClone(withEvent)); this.syncTwin(withEvent, actor, reason); return this.clone(withEvent);
  }

  retireHorse(horseId: string, retirementRecord: RetirementRecord, actor: EquineActor): EquineProfile { return this.recordLifecycleEvent(horseId, { retirementRecord, identity: { lifecycleStatus: 'retired' } }, actor, 'horse-retired'); }
  updateOwnership(horseId: string, ownershipHistory: OwnershipRecord[], actor: EquineActor): EquineProfile { this.validateOwnership(ownershipHistory); return this.recordLifecycleEvent(horseId, { ownershipHistory }, actor, 'ownership-updated'); }
  assignTrainer(horseId: string, assignment: TrainerAssignment, actor: EquineActor): EquineProfile { return this.recordLifecycleEvent(horseId, { trainerAssignments: [...this.getWritable(horseId, actor).trainerAssignments.map((a) => ({ ...a, effectiveTo: a.effectiveTo ?? assignment.effectiveFrom })), assignment] }, actor, 'trainer-assigned'); }
  recordRaceHistory(horseId: string, record: RaceHistoryRecord, actor: EquineActor): EquineProfile { return this.recordLifecycleEvent(horseId, { racingHistory: [...this.getWritable(horseId, actor).racingHistory, record] }, actor, 'race-history-recorded'); }
  recordWorkout(horseId: string, workout: WorkoutRecord, actor: EquineActor): EquineProfile { if (workout.distanceFurlongs <= 0 || workout.timeSeconds <= 0) throw new Error('Workout distance and time must be positive'); return this.recordLifecycleEvent(horseId, { workouts: [...this.getWritable(horseId, actor).workouts, workout] }, actor, 'workout-recorded'); }
  recordTransportation(horseId: string, record: TransportationRecord, actor: EquineActor): EquineProfile { this.requireRole(actor, ['transport-coordinator', 'racing-secretary', 'compliance-officer']); if (!record.departedAt || record.arrivedAt && record.arrivedAt < record.departedAt) throw new Error('Transportation record timestamps are invalid'); return this.recordLifecycleEvent(horseId, { transportationRecords: [...this.getWritable(horseId, actor).transportationRecords, record] }, actor, 'transportation-recorded'); }
  updateVeterinaryStatus(horseId: string, veterinaryStatus: VeterinaryStatusPlaceholder, actor: EquineActor): EquineProfile { this.requireRole(actor, ['veterinarian']); return this.recordLifecycleEvent(horseId, { veterinaryStatus }, actor, 'veterinary-status-updated'); }
  recordWelfareStatus(horseId: string, welfareRecord: WelfareRecord, actor: EquineActor): EquineProfile { if (welfareRecord.score < 0 || welfareRecord.score > 100) throw new Error('Welfare score must be between 0 and 100'); return this.recordLifecycleEvent(horseId, { welfareRecords: [...this.getWritable(horseId, actor).welfareRecords, welfareRecord] }, actor, 'welfare-status-recorded'); }
  assignBarn(horseId: string, assignment: BarnAssignment, actor: EquineActor): EquineProfile { return this.recordLifecycleEvent(horseId, { barnAssignments: [...this.getWritable(horseId, actor).barnAssignments.map((a) => ({ ...a, releasedAt: a.releasedAt ?? assignment.assignedAt })), assignment] }, actor, 'barn-assigned'); }
  updateBreedingMetadata(horseId: string, breedingMetadata: HorseBreedingMetadata, actor: EquineActor): EquineProfile { this.requireRole(actor, ['racing-secretary', 'compliance-officer']); return this.recordLifecycleEvent(horseId, { breedingMetadata: { ...this.getWritable(horseId, actor).breedingMetadata, ...breedingMetadata } }, actor, 'breeding-metadata-updated'); }
  addRegistrationRecord(horseId: string, record: Omit<HorseRegistrationRecord, 'recordId' | 'recordedAt'> & Partial<Pick<HorseRegistrationRecord, 'recordId' | 'recordedAt'>>, actor: EquineActor): EquineProfile { this.requireRole(actor, ['racing-secretary', 'compliance-officer']); const current = this.getWritable(horseId, actor); const nextRecord: HorseRegistrationRecord = { recordId: record.recordId ?? id('registration'), recordedAt: record.recordedAt ?? new Date().toISOString(), authority: record.authority, registrationNumber: record.registrationNumber, registrationType: record.registrationType, effectiveFrom: record.effectiveFrom, effectiveTo: record.effectiveTo, status: record.status, evidence: [...record.evidence] }; return this.recordLifecycleEvent(horseId, { registrationRecords: [...current.registrationRecords, nextRecord] }, actor, 'registration-record-added'); }
  listProfiles(tenantId?: string): EquineProfile[] { return [...this.profiles.values()].filter((profile) => !tenantId || profile.identity.tenantId === tenantId).map((profile) => this.clone(profile)); }
  getProfile(horseId: string, actor: EquineActor): EquineProfile { return this.viewProfile(horseId, actor); }
  recordBarnAssignmentFromOperations(assignment: BarnOperationsHorseAssignment, actor: EquineActor): EquineProfile { return this.assignBarn(assignment.horseId, { barnId: assignment.barnId, stallId: assignment.stallId, assignedAt: assignment.assignedAt, assignedBy: assignment.assignedBy, evidence: [assignment.eventId, assignment.auditId, assignment.twinId ?? `equine:${assignment.horseId}`] }, actor); }
  recordRaceEntryFromRaceOffice(horseId: string, entry: RaceOfficeHorseEntry, actor: EquineActor): EquineProfile { return this.recordRaceHistory(horseId, { raceId: entry.raceId, date: entry.raceDate, trackId: entry.trackId, status: entry.status, finishPosition: entry.finishPosition, evidence: entry.evidence }, actor); }
  addDigitalTwinReference(horseId: string, reference: DigitalTwinReference, actor: EquineActor): EquineProfile { if (!reference.readOnly) throw new Error('Digital Twin references must be read-only from Equine Intelligence'); return this.recordLifecycleEvent(horseId, { digitalTwinReferences: [...this.getWritable(horseId, actor).digitalTwinReferences, reference] }, actor, 'digital-twin-reference-added'); }
  addEligibilityFlag(horseId: string, flag: string, actor: EquineActor): EquineProfile { this.requireRole(actor, ['racing-secretary', 'steward', 'compliance-officer', 'veterinarian']); return this.recordLifecycleEvent(horseId, { eligibilityFlags: [...new Set([...this.getWritable(horseId, actor).eligibilityFlags, flag])] }, actor, 'eligibility-flag-added'); }
  clearEligibilityFlag(horseId: string, flag: string, actor: EquineActor, reason: string, evidence: string[]): EquineProfile { this.requireRole(actor, ['veterinarian', 'steward', 'compliance-officer']); const current = this.getWritable(horseId, actor); return this.recordLifecycleEvent(horseId, { eligibilityFlags: current.eligibilityFlags.filter((item) => item !== flag), operationalEvent: { eventId: id('eligibility-clearance'), occurredAt: new Date().toISOString(), type: 'eligibility-clearance', actorId: actor.id, summary: reason, evidence } }, actor, 'eligibility-flag-cleared'); }
  eligibilityStatus(horseId: string, actor: EquineActor): EquineEligibilityStatus { const profile = this.viewProfile(horseId, actor); const evaluated = this.evaluateEligibility(profile); return { ...evaluated, flags: profile.eligibilityFlags, updatedAt: profile.updatedAt }; }
  welfareStatus(horseId: string, actor: EquineActor): EquineWelfareStatus { const latestRecord = latest(this.viewProfile(horseId, actor).welfareRecords); const score = latestRecord?.score; return { level: score === undefined ? 'unknown' : score < 50 ? 'intervention-required' : score < 70 ? 'monitor' : 'acceptable', latestScore: score, latestObservedAt: latestRecord?.observedAt, interventions: latestRecord?.interventions ?? [] }; }
  registerAIRecommendationHook(hook: AIRecommendationHook): void { this.aiHooks.push(hook); }
  runAIRecommendationHooks(horseId: string, actor: EquineActor): EquineAIRecommendation[] { const profile = this.getWritable(horseId, actor); const recs = this.aiHooks.flatMap((hook) => hook(this.clone(profile))); return recs.map((rec) => this.recordAIRecommendation(horseId, rec, actor)); }
  runAdvisoryRiskAssessment(horseId: string, actor: EquineActor, modelId = 'non-diagnostic-equine-risk-v1'): EquineAIRecommendation { const profile = this.getWritable(horseId, actor); const score = nonDiagnosticRiskScore(this.toHorseSafetyProfile(profile)); return this.recordAIRecommendation(horseId, { domain: 'health', modelId, summary: `${score.disclaimer} Score ${score.score}/100; factors: ${score.factors.join(', ') || 'none observed'}.`, confidence: Number((Math.max(0.5, Math.min(0.95, score.score / 100))).toFixed(2)), proposedOperationalAction: score.score >= 50 ? 'add-veterinary-restriction' : undefined, evidence: ['non-diagnostic-risk-score', ...score.factors] }, actor); }

  recordAIRecommendation(horseId: string, input: Omit<EquineAIRecommendation, 'id'|'horseId'|'tenantId'|'createdAt'|'requestedBy'|'advisoryOnly'|'status'|'veterinarianReviewRequired'> & Partial<Pick<EquineAIRecommendation, 'id'|'createdAt'|'requestedBy'>>, actor: EquineActor): EquineAIRecommendation {
    const profile = this.getWritable(horseId, actor); const healthGoverned = input.domain === 'health' || input.proposedOperationalAction === 'add-veterinary-restriction' || input.proposedOperationalAction === 'clear-to-race';
    const rec: EquineAIRecommendation = { ...input, id: input.id ?? id('ai-rec'), horseId, tenantId: profile.identity.tenantId, createdAt: input.createdAt ?? new Date().toISOString(), requestedBy: input.requestedBy ?? actor.id, advisoryOnly: true, status: healthGoverned ? 'pending-veterinarian-review' : 'advisory', veterinarianReviewRequired: healthGoverned, evidence: [...input.evidence] };
    const externalApproval = healthGoverned && this.approvalService ? this.approvalService.createRequest({ tenantId: profile.identity.tenantId, racetrackId: profileRacetrackId(profile), action: 'veterinary-clearance', target: horseId, requestedBy: actor.id, actorType: actor.human === false ? 'ai-agent' : 'human', reason: rec.summary, evidence: rec.evidence }) : undefined;
    const next = this.appendDomainEvent({ ...profile, aiRecommendations: [...profile.aiRecommendations, rec], approvals: healthGoverned ? [...profile.approvals, { id: externalApproval?.id ?? id('approval'), externalRequestId: externalApproval?.id, recommendationId: rec.id, action: rec.proposedOperationalAction ?? 'health-ai-review', status: 'pending', requestedBy: actor.id, evidence: rec.evidence, requiredRole: 'veterinarian' }] : profile.approvals, version: profile.version + 1, updatedAt: new Date().toISOString() }, actor, 'equine.ai.recommendation.recorded', { recommendationId: rec.id, advisoryOnly: rec.advisoryOnly, veterinarianReviewRequired: rec.veterinarianReviewRequired, externalApprovalRequestId: externalApproval?.id }, 'ai-recommendation-recorded');
    this.profiles.set(horseId, structuredClone(next)); this.syncTwin(next, actor, 'ai-recommendation-recorded'); return this.clone(rec);
  }

  reviewAIRecommendation(horseId: string, recommendationId: string, vet: EquineActor, decision: 'approved'|'rejected', reason: string, evidence: string[]): EquineProfile {
    this.requireRole(vet, ['veterinarian']); if (vet.human === false) throw new Error('Veterinarian AI review must be performed by a human veterinarian');
    const profile = this.getWritable(horseId, vet); const rec = profile.aiRecommendations.find((r) => r.id === recommendationId); if (!rec) throw new Error('AI recommendation not found');
    const reviewed = { ...rec, status: decision === 'approved' ? 'veterinarian-reviewed' as const : 'rejected' as const, veterinarianReview: { veterinarianId: vet.id, reviewedAt: new Date().toISOString(), decision, reason, evidence } };
    const next = this.appendDomainEvent({ ...profile, aiRecommendations: profile.aiRecommendations.map((r) => r.id === recommendationId ? reviewed : r), approvals: profile.approvals.map((a) => a.recommendationId === recommendationId ? { ...a, status: decision, reviewedBy: vet.id, reviewedAt: reviewed.veterinarianReview!.reviewedAt, reason, evidence } : a), version: profile.version + 1, updatedAt: new Date().toISOString() }, vet, 'equine.ai.recommendation.veterinarian-reviewed', { recommendationId, decision }, 'ai-recommendation-veterinarian-reviewed');
    this.profiles.set(horseId, structuredClone(next)); this.syncTwin(next, vet, 'ai-recommendation-veterinarian-reviewed'); return this.clone(next);
  }

  applyAIRecommendation(horseId: string, recommendationId: string, actor: EquineActor): EquineProfile {
    const profile = this.getWritable(horseId, actor); const rec = profile.aiRecommendations.find((r) => r.id === recommendationId); if (!rec) throw new Error('AI recommendation not found');
    if (rec.veterinarianReviewRequired && rec.status !== 'veterinarian-reviewed') throw new Error('Health-related AI recommendations are advisory only until reviewed by a veterinarian');
    if (!rec.proposedOperationalAction) throw new Error('Recommendation has no operational action');
    const patch = rec.proposedOperationalAction === 'add-eligibility-flag' || rec.proposedOperationalAction === 'add-veterinary-restriction' ? { eligibilityFlags: [...new Set([...profile.eligibilityFlags, `ai:${rec.id}:${rec.proposedOperationalAction}`])], aiRecommendations: profile.aiRecommendations.map((r) => r.id === rec.id ? { ...r, status: 'operationalized' as const } : r) } : { aiRecommendations: profile.aiRecommendations.map((r) => r.id === rec.id ? { ...r, status: 'operationalized' as const } : r) };
    return this.recordLifecycleEvent(horseId, patch, actor, 'ai-recommendation-operationalized');
  }

  evaluateEligibility(profile: EquineProfile): { eligible: boolean; complianceStatus: EquineComplianceStatus; failedRules: string[] } { const failed = this.rules.filter((rule) => !rule.evaluate(profile)); const complianceStatus = failed[0]?.failureStatus ?? (profile.retirementRecord ? 'ineligible' : 'compliant'); return { eligible: failed.length === 0 && !profile.retirementRecord, complianceStatus, failedRules: failed.map((rule) => rule.id) }; }
  viewProfile(horseId: string, actor: EquineActor): EquineProfile { const profile = this.getWritable(horseId, actor); const scopes = new Set(actor.roles.flatMap((role) => readScopesByRole[role])); return { ...this.clone(profile), veterinaryRecords: profile.veterinaryRecords.filter((record) => scopes.has(record.privacyScope)) }; }
  relationshipMap(horseId: string, actor: EquineActor): EquineRelationship[] { return this.viewProfile(horseId, actor).relationships; }
  eventStream(horseId: string, actor: EquineActor): EquineEventStreamEntry[] { return this.viewProfile(horseId, actor).eventStream; }
  platformEvents(horseId?: string): RaceDayEvent[] { return this.eventBus.events(horseId ? { aggregateId: horseId } : {}); }
  auditTrail(): AuditLogEntry[] { return this.audit.all(); }
  twinSnapshot(tenantId?: string): AssetState[] { return this.twinRuntime.snapshot(tenantId); }
  observabilitySnapshot(tenantId?: string): EquineObservabilitySnapshot { const profiles = [...this.profiles.values()].filter((p) => !tenantId || p.identity.tenantId === tenantId); return { generatedAt: new Date().toISOString(), profiles: profiles.length, tenantIds: [...new Set(profiles.map((p) => p.identity.tenantId))], pendingVeterinarianReviews: profiles.flatMap((p) => p.aiRecommendations).filter((r) => r.veterinarianReviewRequired && r.status === 'pending-veterinarian-review').length, openApprovals: profiles.flatMap((p) => p.approvals).filter((a) => a.status === 'pending').length, auditRecords: this.audit.all().filter((a) => !tenantId || a.tenantId === tenantId).length, eventCount: this.eventBus.events().filter((e) => !tenantId || (e.payload as { tenantId?: string })?.tenantId === tenantId || (e.payload as { payload?: { tenantId?: string } })?.payload?.tenantId === tenantId).length, twinStates: this.twinRuntime.snapshot(tenantId).length, ineligibleProfiles: profiles.filter((p) => this.evaluateEligibility(p).eligible === false).length, advisoryRecommendations: profiles.flatMap((p) => p.aiRecommendations).filter((r) => r.advisoryOnly).length }; }

  private getWritable(horseId: string, actor: EquineActor) { const profile = this.profiles.get(horseId); if (!profile) throw new Error('Equine profile not found'); this.requireTenant(profile.identity.tenantId, actor); return this.clone(profile); }
  private requireTenant(tenantId: string, actor: EquineActor) { if (actor.tenantId !== tenantId) throw new Error('Tenant boundary violation'); }
  private requireRole(actor: EquineActor, roles: EquineActor['roles']) { if (!actor.roles.some((role) => roles.includes(role))) throw new Error(`Actor lacks required role: ${roles.join('|')}`); }
  private appendDomainEvent(profile: EquineProfile, actor: EquineActor, type: EquineDomainEventType, payload: unknown, action: string): EquineProfile { const audit = this.auditChange(profile, actor, action, [type]); const eventId = id('equine-event'); const eventType = `${type}.v1` as CanonicalEventRef['eventType']; const tenantId = profile.identity.tenantId; const racetrackId = profile.identity.racetrackId ?? 'main-track'; const event: EquineEventStreamEntry = { sequence: ++this.eventSequence, eventId, eventType, tenantId, racetrackId, actorId: actor.id, source: 'equine-intelligence-platform', timestamp: profile.updatedAt, version: 1, occurredAt: profile.updatedAt, type, payload, twinSynced: false, auditId: audit.id }; void this.eventBus.publish({ id: event.eventId, type: event.eventType, occurredAt: event.timestamp, tenantId, racetrackId, actor: { id: actor.id, type: actor.human === false || actor.roles.includes('ai-agent') ? 'ai-agent' : 'human' }, subject: { id: profile.identity.horseId, type: 'horse', tenantId }, evidence: [audit.id], auditRef: audit.id, payload: { horseId: profile.identity.horseId, tenantId, racetrackId, payload }, aggregateId: profile.identity.horseId, producer: event.source, metadata: { compliance: 'regulated', team: 'equine-lifecycle', accountableRole: 'compliance-officer' } }); return { ...profile, eventStream: [...profile.eventStream, event] }; }
  private auditChange(profile: EquineProfile, actor: EquineActor, action: string, changes: string[]) { return this.audit.append({ id: `${profile.identity.horseId}:v${profile.version}:${action}:${this.eventSequence + 1}`, type: action.includes('ai-recommendation') ? 'ai-recommendation' : 'data-change', actor: actor.id, timestamp: profile.updatedAt, payload: { horseId: profile.identity.horseId, tenantId: profile.identity.tenantId, action, changes }, subjectId: profile.identity.horseId, tenantId: profile.identity.tenantId, severity: action.includes('ai') ? 'warning' : 'info', regulations: ['HISA', 'ARCI'] }); }
  private syncTwin(profile: EquineProfile, actor: EquineActor, reason: string) { const latestTransport = latest(profile.transportationRecords); const latestRace = latest(profile.racingHistory); const latestWorkout = latest(profile.workouts); const activeRegistration = profile.registrationRecords.find((record) => record.status === 'active' && !record.effectiveTo); this.twinRuntime.sync({ id: profile.twinId, tenantId: profile.identity.tenantId, updatedAt: profile.updatedAt, state: { horseId: profile.identity.horseId, lifecycleStatus: profile.identity.lifecycleStatus, complianceStatus: profile.complianceStatus, eligible: this.evaluateEligibility(profile).eligible, eligibilityFlags: profile.eligibilityFlags, currentOwner: latest(profile.ownershipHistory)?.ownerId, currentTrainer: currentTrainer(profile)?.trainerId, retirementDestination: profile.retirementRecord?.destination, currentBarn: latest(profile.barnAssignments)?.barnId, currentStall: latest(profile.barnAssignments)?.stallId, latestRaceId: latestRace?.raceId, latestRaceStatus: latestRace?.status, latestWorkoutId: latestWorkout?.workoutId, latestTransportTripId: latestTransport?.tripId, latestTransportTo: latestTransport?.to, veterinaryStatus: profile.veterinaryStatus.status, welfareStatus: this.welfareStatusFromProfile(profile).level, welfareScore: this.welfareStatusFromProfile(profile).latestScore, digitalTwinReferences: profile.digitalTwinReferences.map((r) => r.twinId), registrationNumber: activeRegistration?.registrationNumber, registrationAuthority: activeRegistration?.authority, sireId: profile.breedingMetadata.sireId, damId: profile.breedingMetadata.damId, studBook: profile.breedingMetadata.studBook, openApprovalCount: profile.approvals.filter((a) => a.status === 'pending').length, pendingHealthAiReviewCount: profile.aiRecommendations.filter((r) => r.veterinarianReviewRequired && r.status === 'pending-veterinarian-review').length, relationshipCount: profile.relationships.length, lastSyncedBy: actor.id, syncReason: reason } }); }
  private deriveRelationships(profile: EquineProfile): EquineRelationship[] { const horse = profile.identity.horseId; return [...profile.ownershipHistory.map((r) => ({ id: `${horse}:owner:${r.ownerId}:${r.effectiveFrom}`, type: 'owned-by' as const, fromId: horse, toId: r.ownerId, effectiveFrom: r.effectiveFrom, effectiveTo: r.effectiveTo, evidence: r.evidence })), ...profile.trainerAssignments.map((r) => ({ id: `${horse}:trainer:${r.trainerId}:${r.effectiveFrom}`, type: 'trained-by' as const, fromId: horse, toId: r.trainerId, effectiveFrom: r.effectiveFrom, effectiveTo: r.effectiveTo, evidence: r.evidence })), ...profile.veterinaryRecords.map((r) => ({ id: `${horse}:vet:${r.veterinarianId}:${r.recordId}`, type: 'treated-by' as const, fromId: horse, toId: r.veterinarianId, effectiveFrom: r.recordedAt, evidence: [r.recordId] })), ...profile.racingHistory.map((r) => ({ id: `${horse}:race:${r.raceId}`, type: 'entered-in-race' as const, fromId: horse, toId: r.raceId, effectiveFrom: r.date, evidence: r.evidence })), ...profile.workouts.map((r) => ({ id: `${horse}:workout:${r.workoutId}`, type: 'worked-at-track' as const, fromId: horse, toId: r.trackId, effectiveFrom: r.date, evidence: [r.workoutId, r.source] })), ...profile.transportationRecords.map((r) => ({ id: `${horse}:transport:${r.tripId}`, type: 'transported-by' as const, fromId: horse, toId: r.transporter, effectiveFrom: r.departedAt, effectiveTo: r.arrivedAt, evidence: [r.tripId, ...r.welfareChecks] })), ...profile.barnAssignments.map((r) => ({ id: `${horse}:barn:${r.barnId}:${r.assignedAt}`, type: 'assigned-to-barn' as const, fromId: horse, toId: r.barnId, effectiveFrom: r.assignedAt, effectiveTo: r.releasedAt, evidence: r.evidence })), ...profile.digitalTwinReferences.map((r) => ({ id: `${horse}:twin:${r.twinId}`, type: 'mirrored-by-digital-twin' as const, fromId: horse, toId: r.twinId, effectiveFrom: r.lastSyncedAt ?? profile.updatedAt, evidence: [r.sourceSystem] })), ...(profile.retirementRecord ? [{ id: `${horse}:retired:${profile.retirementRecord.retiredAt}`, type: 'retired-to' as const, fromId: horse, toId: profile.retirementRecord.destination, effectiveFrom: profile.retirementRecord.retiredAt, evidence: profile.retirementRecord.evidence }] : [])]; }
  private validateOwnership(records: OwnershipRecord[]) { const activeTotal = records.filter((r) => !r.effectiveTo).reduce((sum, r) => sum + r.percentage, 0); if (activeTotal !== 100) throw new Error('Active ownership percentages must total 100'); }
  private welfareStatusFromProfile(profile: EquineProfile): EquineWelfareStatus { const latestRecord = latest(profile.welfareRecords); const score = latestRecord?.score; return { level: score === undefined ? 'unknown' : score < 50 ? 'intervention-required' : score < 70 ? 'monitor' : 'acceptable', latestScore: score, latestObservedAt: latestRecord?.observedAt, interventions: latestRecord?.interventions ?? [] }; }
  private toHorseSafetyProfile(profile: EquineProfile): HorseSafetyProfile { const latestRace = latest(profile.racingHistory); const lastActivity = latestRace?.date ?? latest(profile.workouts)?.date ?? profile.updatedAt; const restDays = Math.max(0, Math.floor((Date.now() - Date.parse(lastActivity)) / 86_400_000)); return { horseId: profile.identity.horseId, workoutHistory: profile.workouts.map((workout) => ({ date: workout.date, distanceFurlongs: workout.distanceFurlongs, notes: workout.source })), raceHistory: profile.racingHistory.map((race) => ({ date: race.date, raceId: race.raceId, finishPosition: race.finishPosition })), vetFlags: profile.eligibilityFlags.map((flag) => ({ id: flag, status: 'open' as const, reason: flag })), restDays, medicationStatus: profile.veterinaryStatus.status === 'not-recorded' || profile.veterinaryStatus.status === 'pending-exam' ? 'placeholder-unknown' : 'recorded', shoeingEquipmentNotes: [] }; }
  private clone<T>(value: T): T { return structuredClone(value); }
}

function latest<T extends { effectiveFrom?: string; observedAt?: string; date?: string; assignedAt?: string; departedAt?: string }>(items: T[]): T | undefined { return [...items].sort((a, b) => String(b.effectiveFrom ?? b.observedAt ?? b.date ?? b.assignedAt ?? b.departedAt).localeCompare(String(a.effectiveFrom ?? a.observedAt ?? a.date ?? a.assignedAt ?? a.departedAt)))[0]; }
function currentTrainer(profile: EquineProfile): TrainerAssignment | undefined { return profile.trainerAssignments.find((assignment) => !assignment.effectiveTo) ?? latest(profile.trainerAssignments); }
function profileRacetrackId(profile: EquineProfile): string { return profile.identity.racetrackId ?? latest(profile.racingHistory)?.trackId ?? latest(profile.workouts)?.trackId ?? profile.identity.tenantId; }
