import { type ApiServiceDefinition } from './enterpriseApiGateway.js';
import { UniversalEventBus } from './eventBus.js';
import type { RegistryAsset } from './racetrackAssetRegistryService.js';
import type { TelemetryEvent } from './telemetryEngine.js';
import type { DigitalTwinRuntimeTwin, TwinSimulation } from './digitalTwinRuntime.js';
import type { GeoPoint, RaceSetupParameters, TrackConfigurationSnapshot } from './trackConfiguration.js';

export type MapLayerType = 'sector' | 'starting-gate' | 'rail' | 'barn' | 'facility' | 'camera' | 'emergency-resource' | 'surface-measurement' | 'incident' | 'maintenance' | 'workforce' | 'asset' | 'telemetry' | 'digital-twin' | 'simulation';
export type MapFeatureStatus = 'nominal' | 'standby' | 'warning' | 'critical' | 'closed' | 'in-progress' | 'simulated';
export type Geometry = { type: 'Point'; coordinates: GeoPoint } | { type: 'LineString'; coordinates: GeoPoint[] } | { type: 'Polygon'; coordinates: GeoPoint[] };
export interface MapViewport { center: GeoPoint; zoom: number; minZoom: number; maxZoom: number; bounds: { north: number; south: number; east: number; west: number } }
export interface MapFeature { id: string; layer: MapLayerType; label: string; geometry: Geometry; status: MapFeatureStatus; timestamp: string; source: 'asset-registry' | 'telemetry' | 'event-service' | 'digital-twin' | 'simulation' | 'track-configuration'; properties: Record<string, unknown>; linkedAssetId?: string; linkedTwinId?: string }
export interface MapOverlay { id: string; name: string; layer: MapLayerType; visible: boolean; opacity: number; zIndex: number; filters: Record<string, string[]> }
export interface PlaybackFrame { at: string; featureIds: string[]; summary: string }
export interface GeospatialMapState { trackId: string; generatedAt: string; viewport: MapViewport; layers: MapOverlay[]; features: MapFeature[]; playback: PlaybackFrame[]; digitalTwinState: Array<{ twinId: string; assetId: string; health: string; version: number; lastUpdatedAt: string; relationshipCount: number; dependencyCount: number; historyEvents: number; approvalRequired: boolean }>; simulationOverlays: Array<{ id: string; scenario: string; featureIds: string[]; riskDelta: number; approvalRequired: boolean }>; controls: { zoom: { current: number; presets: number[] }; filters: string[]; overlayModes: string[]; playbackEnabled: boolean } }
export interface MapFilter { layers?: MapLayerType[]; statuses?: MapFeatureStatus[]; sources?: MapFeature['source'][]; atOrBefore?: string; q?: string }

const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v)) as T;
const now = () => new Date().toISOString();

export class GeospatialOperationsService {
  private readonly features = new Map<string, MapFeature>();
  private readonly overlays = new Map<string, MapOverlay>();
  private readonly simulations = new Map<string, GeospatialMapState['simulationOverlays'][number]>();
  constructor(private readonly options: { eventBus?: UniversalEventBus; trackId?: string } = {}) { this.registerDefaultOverlays(); }

  upsertFeature(feature: MapFeature): MapFeature { const next = clone(feature); this.features.set(next.id, next); void this.options.eventBus?.publish({ type: 'geospatial.map.feature.updated', payload: { feature: next }, aggregateId: next.id, producer: 'geospatial-operations', metadata: { team: 'racetrack-platform', accountableRole: 'operations-map-owner' } }); return clone(next); }
  ingestAssets(assets: RegistryAsset[]): MapFeature[] { return assets.map((asset) => this.upsertFeature({ id: `asset:${asset.assetId}`, layer: layerForAsset(asset), label: asset.name, geometry: geometryFromLocation(asset.location), status: statusFromAsset(asset), timestamp: asset.updatedAt, source: 'asset-registry', linkedAssetId: asset.assetId, linkedTwinId: asset.digitalTwin?.twinId, properties: { assetType: asset.assetType, domain: asset.domain, maintenance: asset.maintenance.status, tags: asset.tags } })); }
  ingestTelemetry(events: TelemetryEvent[]): MapFeature[] { return events.filter((event) => typeof event.payload.latitude === 'number' && typeof event.payload.longitude === 'number').map((event) => this.upsertFeature({ id: `telemetry:${event.id}`, layer: event.source === 'camera' ? 'camera' : 'telemetry', label: `${event.source} ${event.subjectId}`, geometry: { type: 'Point', coordinates: { latitude: Number(event.payload.latitude), longitude: Number(event.payload.longitude), elevationMeters: typeof event.payload.elevationMeters === 'number' ? event.payload.elevationMeters : undefined } }, status: statusFromValue(event.payload.status), timestamp: event.observedAt, source: 'telemetry', properties: event.payload, linkedAssetId: event.subjectId })); }
  ingestTwinState(twins: DigitalTwinRuntimeTwin[]): MapFeature[] { return twins.map((twin) => this.upsertFeature({ id: `twin:${twin.twinId}`, layer: 'digital-twin', label: twin.name, geometry: geometryFromLocation(twin.state.location as Record<string, unknown> | undefined), status: twin.health === 'critical' ? 'critical' : twin.health === 'degraded' ? 'warning' : 'nominal', timestamp: twin.updatedAt, source: 'digital-twin', linkedAssetId: twin.assetId, linkedTwinId: twin.twinId, properties: { version: twin.version, health: twin.health, telemetryReferences: twin.telemetryReferences.length, risks: twin.riskIndicators, healthIndicators: twin.healthIndicators ?? [], relationshipCount: twin.relationships.length, dependencyCount: twin.dependencies.length, historyEvents: twin.eventHistory.length, approvalRequired: twin.approvalRequirements.length > 0 } })); }
  ingestTrackConfiguration(snapshot: TrackConfigurationSnapshot): MapFeature[] { const boundaryFeatures = snapshot.boundaries.map((boundary) => this.upsertFeature({ id: `track-boundary:${boundary.id}`, layer: 'sector' as const, label: boundary.name, geometry: { type: 'Polygon' as const, coordinates: boundary.polygon }, status: 'nominal' as const, timestamp: snapshot.generatedAt, source: 'track-configuration' as const, properties: { surface: boundary.surface } })); const sectorFeatures = snapshot.sectors.map((sector) => this.upsertFeature({ id: `track-sector:${sector.id}`, layer: 'sector' as const, label: sector.name, geometry: { type: 'LineString' as const, coordinates: sector.centerline.points }, status: sector.restrictions.length ? 'warning' as const : 'nominal' as const, timestamp: snapshot.generatedAt, source: 'track-configuration' as const, properties: { surface: sector.surface, kind: sector.kind, lengthMeters: sector.lengthMeters, widthMeters: sector.widthMeters, restrictions: sector.restrictions } })); const setupFeatures = snapshot.activeSetups.flatMap((setup) => featuresForRaceSetup(setup, snapshot.generatedAt).map((feature) => this.upsertFeature(feature))); return [...boundaryFeatures, ...sectorFeatures, ...setupFeatures].map(clone); }
  addSimulationOverlay(simulation: TwinSimulation): GeospatialMapState['simulationOverlays'][number] { const overlay = { id: `simulation:${simulation.twinId}:${simulation.scenario}`, scenario: simulation.scenario, featureIds: [`twin:${simulation.twinId}`], riskDelta: simulation.projectedRiskScore, approvalRequired: simulation.approvalRequired }; this.simulations.set(overlay.id, overlay); this.overlays.set(overlay.id, { id: overlay.id, name: `Simulation: ${simulation.scenario}`, layer: 'simulation', visible: true, opacity: 0.45, zIndex: 90, filters: {} }); return clone(overlay); }
  setOverlay(id: string, patch: Partial<MapOverlay>) { const current = this.overlays.get(id); if (!current) throw new Error(`Unknown overlay ${id}`); const next = { ...current, ...patch, id: current.id }; this.overlays.set(id, next); return clone(next); }
  render(filter: MapFilter = {}, zoom = 14): GeospatialMapState { const features = [...this.features.values()].filter((f) => matches(f, filter)); return { trackId: this.options.trackId ?? 'main-track', generatedAt: now(), viewport: viewportFor(features, zoom), layers: [...this.overlays.values()].map(clone), features: features.map(clone), playback: this.playback(features, filter.atOrBefore), digitalTwinState: features.filter((f) => f.layer === 'digital-twin').map((f) => ({ twinId: String(f.linkedTwinId), assetId: String(f.linkedAssetId), health: String(f.properties.health), version: Number(f.properties.version), lastUpdatedAt: f.timestamp, relationshipCount: Number(f.properties.relationshipCount ?? 0), dependencyCount: Number(f.properties.dependencyCount ?? 0), historyEvents: Number(f.properties.historyEvents ?? 0), approvalRequired: Boolean(f.properties.approvalRequired) })), simulationOverlays: [...this.simulations.values()].map(clone), controls: { zoom: { current: zoom, presets: [12, 14, 16, 18, 20] }, filters: ['layer', 'status', 'source', 'time', 'search'], overlayModes: ['current-state', 'historical-playback', 'simulation', 'digital-twin-health'], playbackEnabled: true } }; }
  apiDefinition(): ApiServiceDefinition { return geospatialOperationsApiDefinition(); }
  private playback(features: MapFeature[], at?: string): PlaybackFrame[] { return [...new Set(features.map((f) => f.timestamp).filter((t) => !at || t <= at).sort())].map((t) => ({ at: t, featureIds: features.filter((f) => f.timestamp <= t).map((f) => f.id), summary: `${features.filter((f) => f.timestamp <= t).length} map features active` })); }
  private registerDefaultOverlays() { (['sector','starting-gate','rail','barn','facility','camera','emergency-resource','surface-measurement','incident','maintenance','workforce','digital-twin'] as MapLayerType[]).forEach((layer, i) => this.overlays.set(layer, { id: layer, name: layer.replace(/-/g, ' '), layer, visible: true, opacity: 1, zIndex: i + 1, filters: {} })); }
}

function featuresForRaceSetup(setup: RaceSetupParameters, timestamp: string): MapFeature[] {
  const features: MapFeature[] = [{
    id: `gate:${setup.gatePlacement.gateId}:${setup.raceId}`,
    layer: 'starting-gate',
    label: `Starting gate ${setup.gatePlacement.gateId} for ${setup.raceId}`,
    geometry: { type: 'Point', coordinates: setup.gatePlacement.location },
    status: setup.calculations?.regulatoryFlags.length ? 'warning' : 'standby',
    timestamp,
    source: 'track-configuration',
    linkedAssetId: setup.gatePlacement.gateId,
    linkedTwinId: `race-setup:${setup.raceId}`,
    properties: { raceId: setup.raceId, distanceMeters: setup.distanceMeters, headingDegrees: setup.gatePlacement.headingDegrees, runUpMeters: setup.gatePlacement.runUpMeters ?? 0, calculations: setup.calculations },
  }];
  if (setup.railPosition) features.push({ id: `rail:${setup.railPosition.railId}:${setup.raceId}`, layer: 'rail', label: `Rail ${setup.railPosition.railId}`, geometry: { type: 'Point', coordinates: setup.gatePlacement.location }, status: setup.railPosition.offsetMeters > 12 ? 'warning' : 'nominal', timestamp, source: 'track-configuration', linkedTwinId: `race-setup:${setup.raceId}`, properties: { raceId: setup.raceId, offsetMeters: setup.railPosition.offsetMeters, protectedTurns: setup.railPosition.protectedTurns, effectiveFrom: setup.railPosition.effectiveFrom, effectiveTo: setup.railPosition.effectiveTo } });
  if (setup.turfConfiguration) features.push({ id: `turf:${setup.turfConfiguration.lane}:${setup.raceId}`, layer: 'sector', label: `Turf lane ${setup.turfConfiguration.lane}`, geometry: { type: 'Point', coordinates: setup.gatePlacement.location }, status: setup.turfConfiguration.resting ? 'closed' : 'nominal', timestamp, source: 'track-configuration', linkedTwinId: `race-setup:${setup.raceId}`, properties: { raceId: setup.raceId, going: setup.turfConfiguration.going, irrigationMillimeters: setup.turfConfiguration.irrigationMillimeters, mowingHeightMillimeters: setup.turfConfiguration.mowingHeightMillimeters, resting: setup.turfConfiguration.resting } });
  return features;
}

function matches(f: MapFeature, q: MapFilter) { const text = `${f.id} ${f.label} ${JSON.stringify(f.properties)}`.toLowerCase(); return (!q.layers || q.layers.includes(f.layer)) && (!q.statuses || q.statuses.includes(f.status)) && (!q.sources || q.sources.includes(f.source)) && (!q.atOrBefore || f.timestamp <= q.atOrBefore) && (!q.q || text.includes(q.q.toLowerCase())); }
function geometryFromLocation(location?: Record<string, unknown>): Geometry { const lat = Number(location?.latitude ?? location?.lat ?? 38.05); const lon = Number(location?.longitude ?? location?.lon ?? -76.95); return { type: 'Point', coordinates: { latitude: lat, longitude: lon } }; }
function statusFromValue(v: unknown): MapFeatureStatus { return ['nominal','standby','warning','critical','closed','in-progress','simulated'].includes(String(v)) ? String(v) as MapFeatureStatus : 'nominal'; }
function statusFromAsset(a: RegistryAsset): MapFeatureStatus { return a.maintenance.status === 'out-of-service' ? 'critical' : a.maintenance.status === 'overdue' ? 'warning' : a.lifecycleStatus === 'inactive' ? 'closed' : 'nominal'; }
function layerForAsset(a: RegistryAsset): MapLayerType { const t = `${a.assetType} ${a.tags.join(' ')}`.toLowerCase(); if (t.includes('gate')) return 'starting-gate'; if (t.includes('rail')) return 'rail'; if (t.includes('barn')) return 'barn'; if (t.includes('camera')) return 'camera'; if (t.includes('ambulance') || t.includes('emergency')) return 'emergency-resource'; if (t.includes('crew') || t.includes('workforce')) return 'workforce'; if (t.includes('facility')) return 'facility'; return 'asset'; }
function viewportFor(features: MapFeature[], zoom: number): MapViewport { const points = features.flatMap((f) => f.geometry.type === 'Point' ? [f.geometry.coordinates] : f.geometry.coordinates); const lats = points.map((p) => p.latitude); const lons = points.map((p) => p.longitude); const north = Math.max(...lats, 38.08), south = Math.min(...lats, 38.02), east = Math.max(...lons, -76.92), west = Math.min(...lons, -76.98); return { center: { latitude: (north + south) / 2, longitude: (east + west) / 2 }, zoom, minZoom: 10, maxZoom: 22, bounds: { north, south, east, west } }; }
export function geospatialOperationsApiDefinition(): ApiServiceDefinition { return { id: 'geospatial-operations', name: 'Geospatial Operations Map', domain: 'operations', version: 'v1', basePath: '/api/v1/geospatial', description: 'Digital Twin visual map for sectors, gates, rails, facilities, cameras, emergency resources, measurements, incidents, maintenance, workforce, overlays, playback, and simulations.', owner: { team: 'racetrack-platform', productOwner: 'Director of Operations Technology', technicalOwner: 'Geospatial Operations Owner', supportChannel: '#trackmind-geo' }, lifecycle: 'active', auth: ['jwt','oauth2','mtls'], rateLimit: { requests: 600, perSeconds: 60, burst: 100 }, tags: ['geospatial','digital-twin','operations','telemetry'], slo: { availability: 99.95, latencyMs: 250 }, endpoints: [{ method: 'GET', path: '/map', summary: 'Render filtered track map state', scopes: ['geospatial:read'] }, { method: 'PATCH', path: '/overlays/{id}', summary: 'Toggle or configure map overlays', scopes: ['geospatial:write'] }, { method: 'GET', path: '/playback', summary: 'Replay historical geospatial state', scopes: ['geospatial:read'] }, { method: 'POST', path: '/simulations', summary: 'Project simulation overlays on the Digital Twin map', scopes: ['geospatial:simulate'] }] }; }
