import type { ApprovalToken, CentralizedApprovalService } from './approvals.js';
import { hasPermission, type Permission, type Role } from '@trackmind/shared';
import type { RaceOfficeApprovalActionDto, RaceOfficeWorkspaceDto } from '@trackmind/shared';
import type { ImmutableAuditLog } from './auditLog.js';
import type { UniversalEventBus } from './eventBus.js';
import type { WorkflowOrchestrationEngine, WorkflowInstance } from './workflowEngine.js';
import type { DigitalTwinRuntime } from './digitalTwinRuntime.js';
import type { ApiServiceDefinition } from './enterpriseApiGateway.js';

export type RaceStatus = 'draft' | 'scheduled' | 'entries-open' | 'declared' | 'post-positions-drawn' | 'ready' | 'running' | 'official' | 'cancelled';
export type ApprovalState = 'not-required' | 'pending' | 'approved' | 'rejected';
export type RaceActivityType = 'race.meet.created' | 'race.day.created' | 'race.card.created' | 'race.approval.requested' | 'race.status.changed' | 'race.scheduled' | 'race.schedule.changed' | 'race.entry.added' | 'race.entry.declared' | 'race.entry.scratched' | 'race.declarations.closed' | 'race.posts.drawn' | 'race.gates.assigned' | 'race.conditions.updated' | 'race.staffing.assigned' | 'race.resources.allocated' | 'race.readiness.assessed' | 'race.started' | 'race.execution.tracked' | 'race.official' | 'race.cancelled';

export interface RaceMeet { id: string; trackId: string; name: string; startsOn: string; endsOn: string; status: 'draft' | 'open' | 'closed' | 'cancelled'; officialConfig: RaceOfficeOfficialConfig; updatedAt: string; }
export interface RaceDay { id: string; meetId: string; trackId: string; raceDate: string; status: 'draft' | 'carding' | 'entries-open' | 'ready' | 'closed' | 'cancelled'; raceIds: string[]; updatedAt: string; }
export interface RaceOfficeOfficialConfig { stewards: string[]; racingSecretary: string; commission: string; rulesVersion: string; scratchDeadlineMinutes: number; maxFieldSize: number; }
export interface RaceOfficeActor { id: string; roles: Role[]; human?: boolean; }
export interface RaceCondition { surface: 'dirt' | 'turf' | 'synthetic'; distanceFurlongs: number; classLevel: string; purse: number; eligibility: string[]; medicationRules?: string[]; weatherRestrictions?: string[]; surfaceRequirements?: string[]; }
export interface RaceEntry { id: string; horseId: string; trainerId: string; ownerId: string; jockeyId?: string; weightLbs?: number; declared?: boolean; scratched?: boolean; scratchReason?: string; scratchApprovedBy?: string; postPosition?: number; gate?: string; }
export interface StaffingAssignment { id: string; role: keyof StaffingPlan | string; personId: string; shiftStart: string; shiftEnd: string; status: 'assigned' | 'checked-in' | 'released'; zone?: string; }
export interface RaceCard { id: string; trackId: string; raceDate: string; raceNumber: number; scheduledPostTime: string; status: RaceStatus; conditions: RaceCondition; entries: RaceEntry[]; approvals: Record<string, ApprovalState>; regulatoryControls: string[]; twinLinks: string[]; telemetryStreams: string[]; staffingPlan?: StaffingPlan; staffingAssignments: StaffingAssignment[]; resources: ResourceAllocation[]; workflowInstanceId?: string; readiness?: RaceReadinessAssessment; updatedAt: string; }
export interface StaffingPlan { stewards: string[]; veterinarians: string[]; gateCrew: string[]; outriders: string[]; trackMaintenance: string[]; security: string[]; }
export interface ResourceAllocation { id: string; type: 'starting-gate' | 'ambulance' | 'tractor' | 'harrow' | 'camera' | 'sensor' | 'tote' | 'security-post'; zone: string; status: 'allocated' | 'standby' | 'unavailable'; }
export interface RaceTelemetrySignal { streamId: string; type: 'gate' | 'surface' | 'weather' | 'gps' | 'vision' | 'biometric' | 'tote'; observedAt: string; healthy: boolean; value: number | string | boolean; }
export interface RaceExecutionEvent { timestamp: string; type: 'loaded' | 'off' | 'fraction' | 'incident' | 'objection' | 'finish' | 'official'; message: string; severity?: 'info' | 'warning' | 'critical'; evidenceIds?: string[]; }
export interface RaceReadinessAssessment { raceId: string; ready: boolean; activeEntries: number; blockers: string[]; assessedAt: string; telemetryStreams: string[]; }
export interface RaceOperationsDashboard { generatedAt: string; totals: Record<RaceStatus | 'all', number>; byTrack: Array<{ trackId: string; races: number; ready: number; running: number; blocked: number }>; upcoming: Array<{ raceId: string; trackId: string; raceNumber: number; postTime: string; status: RaceStatus; blockers: string[] }>; resourceExceptions: Array<{ raceId: string; resourceId: string; type: string; status: string }>; staffingExceptions: Array<{ raceId: string; missing: string[] }>; executionAlerts: Array<{ raceId: string; timestamp: string; message: string; severity: string }>; }
export type RaceOfficeWorkspace = RaceOfficeWorkspaceDto;

const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const id = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
const raceStatuses: RaceStatus[] = ['draft','scheduled','entries-open','declared','post-positions-drawn','ready','running','official','cancelled'];

export class RaceOperationsRepository {
  private readonly races = new Map<string, RaceCard>();
  private readonly execution = new Map<string, RaceExecutionEvent[]>();
  private readonly meets = new Map<string, RaceMeet>();
  private readonly days = new Map<string, RaceDay>();
  saveMeet(meet: RaceMeet): RaceMeet { this.meets.set(meet.id, clone(meet)); return clone(meet); }
  getMeet(meetId: string): RaceMeet | undefined { const meet = this.meets.get(meetId); return meet ? clone(meet) : undefined; }
  listMeets(trackId?: string): RaceMeet[] { return [...this.meets.values()].filter((m) => !trackId || m.trackId === trackId).map(clone); }
  saveDay(day: RaceDay): RaceDay { this.days.set(day.id, clone(day)); return clone(day); }
  getDay(dayId: string): RaceDay | undefined { const day = this.days.get(dayId); return day ? clone(day) : undefined; }
  listDays(filter: { meetId?: string; trackId?: string; raceDate?: string } = {}): RaceDay[] { return [...this.days.values()].filter((d) => (!filter.meetId || d.meetId === filter.meetId) && (!filter.trackId || d.trackId === filter.trackId) && (!filter.raceDate || d.raceDate === filter.raceDate)).map(clone); }
  saveRace(race: RaceCard): RaceCard { this.races.set(race.id, clone(race)); return clone(race); }
  getRace(raceId: string): RaceCard | undefined { const race = this.races.get(raceId); return race ? clone(race) : undefined; }
  listRaces(filter: { trackId?: string; raceDate?: string; status?: RaceStatus } = {}): RaceCard[] { return [...this.races.values()].filter((r) => (!filter.trackId || r.trackId === filter.trackId) && (!filter.raceDate || r.raceDate === filter.raceDate) && (!filter.status || r.status === filter.status)).map(clone); }
  appendExecution(raceId: string, event: RaceExecutionEvent): RaceExecutionEvent[] { const events = [...(this.execution.get(raceId) ?? []), clone(event)].sort((a, b) => a.timestamp.localeCompare(b.timestamp)); this.execution.set(raceId, events); return events.map(clone); }
  executionEvents(raceId: string): RaceExecutionEvent[] { return (this.execution.get(raceId) ?? []).map(clone); }
}

export interface RaceOperationsDeps { approvalService?: CentralizedApprovalService; eventBus?: UniversalEventBus; auditLog?: ImmutableAuditLog; workflow?: WorkflowOrchestrationEngine; twinRuntime?: DigitalTwinRuntime; repository?: RaceOperationsRepository; tenantId?: string; }

export class RaceOperationsPlatform {
  private readonly repository: RaceOperationsRepository;
  private readonly tenantId: string;
  constructor(depsOrApproval?: RaceOperationsDeps | CentralizedApprovalService, tenantId = 'default-tenant') {
    const deps = depsOrApproval && 'assertAuthorized' in depsOrApproval ? { approvalService: depsOrApproval as CentralizedApprovalService, tenantId } : (depsOrApproval ?? {}) as RaceOperationsDeps;
    this.approvalService = deps.approvalService; this.eventBus = deps.eventBus; this.auditLog = deps.auditLog; this.workflow = deps.workflow; this.twinRuntime = deps.twinRuntime; this.repository = deps.repository ?? new RaceOperationsRepository(); this.tenantId = deps.tenantId ?? tenantId;
  }
  private readonly approvalService?: CentralizedApprovalService; private readonly eventBus?: UniversalEventBus; private readonly auditLog?: ImmutableAuditLog; private readonly workflow?: WorkflowOrchestrationEngine; private readonly twinRuntime?: DigitalTwinRuntime;


  createMeet(input: Omit<RaceMeet, 'status' | 'updatedAt'> & { status?: RaceMeet['status'] }, actor: RaceOfficeActor = { id: 'racing-office', roles: ['racing-secretary'] }): RaceMeet { this.assertRole(actor, 'race:request-start'); this.validateDateRange(input.startsOn, input.endsOn); this.validateOfficialConfig(input.officialConfig); const meet = this.repository.saveMeet({ ...input, status: input.status ?? 'draft', updatedAt: new Date().toISOString() }); this.connect('race.meet.created', actor.id, this.syntheticRace(meet.trackId, meet.id), { meet }); return meet; }
  createRaceDay(input: Omit<RaceDay, 'status' | 'raceIds' | 'updatedAt'> & { status?: RaceDay['status']; raceIds?: string[] }, actor: RaceOfficeActor = { id: 'racing-office', roles: ['racing-secretary'] }): RaceDay { this.assertRole(actor, 'race:request-start'); const meet = this.requireMeet(input.meetId); if (meet.trackId !== input.trackId) throw new Error('Race day track must match its meet'); if (input.raceDate < meet.startsOn || input.raceDate > meet.endsOn) throw new Error('Race day must fall within meet dates'); if (this.repository.listDays({ meetId: input.meetId, raceDate: input.raceDate }).some((day) => day.id !== input.id)) throw new Error('Race day already exists for meet and date'); const day = this.repository.saveDay({ ...input, status: input.status ?? 'draft', raceIds: input.raceIds ?? [], updatedAt: new Date().toISOString() }); this.connect('race.day.created', actor.id, this.syntheticRace(day.trackId, day.id), { day }); return day; }
  createRaceCard(dayId: string, input: Parameters<RaceOperationsPlatform['scheduleRace']>[0], actor: RaceOfficeActor = { id: 'racing-office', roles: ['racing-secretary'] }): RaceCard { const day = this.requireDay(dayId); const race = this.scheduleRace({ ...input, trackId: day.trackId, raceDate: day.raceDate }, actor.id); this.repository.saveDay({ ...day, status: 'carding', raceIds: [...new Set([...day.raceIds, race.id])], updatedAt: new Date().toISOString() }); this.connect('race.card.created', actor.id, race, { dayId, raceId: race.id }); return race; }
  requestSafetyCriticalAction(action: RaceOfficeApprovalActionDto, target: string, reason: string, actor: RaceOfficeActor, evidence: string[] = ['human-approval-record']): ReturnType<CentralizedApprovalService['createRequest']> { if (!this.approvalService) throw new Error('Approval service is required for safety-critical race-office actions'); this.assertRole(actor, 'race:request-start'); const request = this.approvalService.createRequest({ tenantId: this.tenantId, action, target, requestedBy: actor.id, actorType: actor.human === false ? 'service' : 'human', reason, evidence }); const race = this.repository.getRace(target) ?? this.syntheticRace('unknown-track', target); this.connect('race.approval.requested', actor.id, race, { action, target, approvalRequestId: request.id, reason }); return request; }
  scratchEntryWithApproval(raceId: string, entryId: string, reason: string, token: ApprovalToken, actor = 'stewards', now = new Date().toISOString()): RaceCard { this.requireApprovalService().assertAuthorized(token, 'race-office-scratch', raceId, this.tenantId, now); return this.mapEntry(raceId, entryId, actor, 'race.entry.scratched', (entry) => ({ ...entry, scratched: true, scratchReason: reason, scratchApprovedBy: actor })); }
  changeRaceStatus(raceId: string, status: RaceStatus, token: ApprovalToken, actor = 'stewards', now = new Date().toISOString()): RaceCard { this.requireApprovalService().assertAuthorized(token, status === 'cancelled' ? 'race-cancellation' : 'race-status-change', raceId, this.tenantId, now); this.validateStatusTransition(this.requireRace(raceId).status, status); return this.update(raceId, actor, status === 'cancelled' ? 'race.cancelled' : 'race.status.changed', (race) => ({ ...race, status })); }
  updateOfficialConfig(meetId: string, config: Partial<RaceOfficeOfficialConfig>, token: ApprovalToken, actor = 'racing-office', now = new Date().toISOString()): RaceMeet { this.requireApprovalService().assertAuthorized(token, 'race-office-configuration', meetId, this.tenantId, now); const meet = this.requireMeet(meetId); const next = this.repository.saveMeet({ ...meet, officialConfig: { ...meet.officialConfig, ...config }, updatedAt: now }); this.validateOfficialConfig(next.officialConfig); this.connect('race.status.changed', actor, this.syntheticRace(next.trackId, meetId), { meetId, officialConfig: next.officialConfig }); return next; }
  listMeets(trackId?: string) { return this.repository.listMeets(trackId); }
  listRaceDays(filter: { meetId?: string; trackId?: string; raceDate?: string } = {}) { return this.repository.listDays(filter); }

  scheduleRace(input: Omit<RaceCard, 'status' | 'entries' | 'approvals' | 'regulatoryControls' | 'twinLinks' | 'telemetryStreams' | 'staffingAssignments' | 'resources' | 'updatedAt'> & Partial<Pick<RaceCard, 'entries' | 'approvals' | 'regulatoryControls' | 'twinLinks' | 'telemetryStreams' | 'staffingAssignments' | 'resources'>>, actor = 'racing-office'): RaceCard {
    const now = new Date().toISOString();
    this.validateRaceSchedule(input);
    const race: RaceCard = { ...input, status: 'scheduled', entries: input.entries ?? [], approvals: { racingOffice: 'pending', stewards: 'pending', veterinarian: 'pending', ...(input.approvals ?? {}) }, regulatoryControls: input.regulatoryControls ?? ['HISA', 'ARCI', 'state-racing-commission'], twinLinks: input.twinLinks ?? [`track:${input.trackId}`, `race:${input.id}`], telemetryStreams: input.telemetryStreams ?? ['gate-status', 'surface-condition', 'weather', 'vision'], staffingAssignments: input.staffingAssignments ?? [], resources: input.resources ?? [], updatedAt: now };
    this.saveAndConnect(race, 'race.scheduled', actor, { race });
    return race;
  }
  addEntry(raceId: string, entry: RaceEntry, actor = 'racing-office'): RaceCard { const race = this.requireRace(raceId); this.assertMutableRace(race, 'add entries'); if (race.entries.some((current) => current.id !== entry.id && current.horseId === entry.horseId)) throw new Error('Horse already has an entry on this race card'); return this.update(raceId, actor, 'race.entry.added', (current) => ({ ...current, status: 'entries-open', entries: [...current.entries.filter((e) => e.id !== entry.id), { ...entry, declared: entry.declared ?? false, scratched: false }] })); }
  declareEntry(raceId: string, entryId: string, jockeyId: string, weightLbs: number, actor = 'racing-office'): RaceCard { if (weightLbs <= 0) throw new Error('Declaration requires a positive assigned weight'); const race = this.requireRace(raceId); this.assertMutableRace(race, 'declare entries'); const projected = race.entries.map((entry) => entry.id === entryId ? { ...entry, jockeyId, weightLbs, declared: true } : entry); this.validateFieldSize(race, projected); return this.mapEntry(raceId, entryId, actor, 'race.entry.declared', (entry) => ({ ...entry, jockeyId, weightLbs, declared: true })); }
  scratchEntry(_raceId: string, _entryId: string, _reason: string, _approvedBy: string, _actor = _approvedBy): RaceCard { throw new Error('horse scratches require scratchEntryWithApproval with an authorized human approval token'); }
  updateConditions(raceId: string, conditions: Partial<RaceCondition>, actor = 'racing-office'): RaceCard { if (conditions.distanceFurlongs !== undefined) throw new Error('race distance changes require the track configuration approval workflow'); return this.update(raceId, actor, 'race.conditions.updated', (race) => ({ ...race, conditions: { ...race.conditions, ...conditions } })); }
  updateConditionsWithApproval(raceId: string, conditions: Partial<RaceCondition>, token: ApprovalToken, actor = 'racing-office', now = new Date().toISOString()): RaceCard { const action = conditions.distanceFurlongs !== undefined ? 'race-distance-configuration' : 'race-office-configuration'; this.requireApprovalService().assertAuthorized(token, action, raceId, this.tenantId, now); return this.update(raceId, actor, 'race.conditions.updated', (race) => ({ ...race, conditions: { ...race.conditions, ...conditions } })); }
  rescheduleRaceWithApproval(raceId: string, scheduledPostTime: string, token: ApprovalToken, actor = 'racing-office', now = new Date().toISOString()): RaceCard { this.requireApprovalService().assertAuthorized(token, 'race-office-configuration', raceId, this.tenantId, now); this.validatePostTime(scheduledPostTime); return this.update(raceId, actor, 'race.schedule.changed', (race) => { this.validateRaceSchedule({ ...race, scheduledPostTime }, race.id); return { ...race, scheduledPostTime }; }); }
  closeDeclarations(raceId: string, actor = 'racing-office'): RaceCard { const race = this.requireRace(raceId); const active = this.activeEntries(race); if (!active.length) throw new Error('Cannot close declarations without active declared entries'); this.validateFieldSize(race, race.entries); return this.update(raceId, actor, 'race.declarations.closed', (current) => ({ ...current, status: 'declared' })); }
  drawPostPositions(raceId: string, seed = 1, actor = 'racing-office'): RaceCard { const race = this.requireRace(raceId); const active = this.activeEntries(race).sort((a, b) => `${a.id}:${seed}`.localeCompare(`${b.id}:${seed}`)); if (!active.length) throw new Error('Post positions require active declared entries'); this.validateFieldSize(race, race.entries); const positions = new Map(active.map((entry, index) => [entry.id, index + 1])); return this.update(raceId, actor, 'race.posts.drawn', (current) => ({ ...current, status: 'post-positions-drawn', entries: current.entries.map((entry) => positions.has(entry.id) ? { ...entry, postPosition: positions.get(entry.id) } : entry) })); }
  assignGates(raceId: string, gatePrefix = 'G', actor = 'starter'): RaceCard { const race = this.requireRace(raceId); if (!this.activeEntries(race).every((entry) => entry.postPosition)) throw new Error('Gate assignment requires drawn post positions for all active entries'); return this.update(raceId, actor, 'race.gates.assigned', (current) => ({ ...current, entries: current.entries.map((entry) => entry.postPosition && !entry.scratched ? { ...entry, gate: `${gatePrefix}-${entry.postPosition}` } : entry) })); }
  coordinateStaffing(raceId: string, staffingPlan: StaffingPlan, actor = 'operations'): RaceCard { return this.update(raceId, actor, 'race.staffing.assigned', (race) => ({ ...race, staffingPlan })); }
  assignStaffing(raceId: string, assignments: StaffingAssignment[], actor = 'operations'): RaceCard { return this.update(raceId, actor, 'race.staffing.assigned', (race) => ({ ...race, staffingAssignments: assignments.map(clone) })); }
  allocateResources(raceId: string, resources: ResourceAllocation[], actor = 'operations'): RaceCard { return this.update(raceId, actor, 'race.resources.allocated', (race) => ({ ...race, resources: resources.map(clone) })); }
  approveWorkflow(raceId: string, step: string, state: ApprovalState, actor = 'approval-engine'): RaceCard { return this.update(raceId, actor, 'race.readiness.assessed', (race) => ({ ...race, approvals: { ...race.approvals, [step]: state } })); }
  startWorkflow(raceId: string, definitionId = 'race-lifecycle', actor = 'racing-office'): WorkflowInstance | undefined { const race = this.requireRace(raceId); const instance = this.workflow?.start(definitionId, { tenantId: this.tenantId, priority: 'high', digitalTwinRefs: race.twinLinks, payload: { raceId, raceDate: race.raceDate, raceNumber: race.raceNumber } }, actor); if (instance) this.update(raceId, actor, 'race.scheduled', (r) => ({ ...r, workflowInstanceId: instance.id })); return instance; }
  assessReadiness(raceId: string, telemetry: RaceTelemetrySignal[], actor = 'operations'): RaceReadinessAssessment { const race = this.requireRace(raceId); const activeEntries = this.activeEntries(race); const approvalsOk = Object.values(race.approvals).every((state) => state === 'approved' || state === 'not-required'); const telemetryOk = telemetry.every((signal) => signal.healthy); const staffingOk = Boolean(race.staffingPlan?.stewards.length && race.staffingPlan.veterinarians.length && race.staffingPlan.gateCrew.length); const resourceOk = Boolean(race.resources?.some((r) => r.type === 'starting-gate' && r.status === 'allocated')); const postsOk = activeEntries.every((entry) => entry.postPosition); const gatesOk = activeEntries.every((entry) => entry.gate); const fieldOk = activeEntries.length <= this.maxFieldSizeForRace(race); const scheduleOk = this.scheduleConflictsFor(race).length === 0; const ready = activeEntries.length > 0 && approvalsOk && telemetryOk && staffingOk && resourceOk && postsOk && gatesOk && fieldOk && scheduleOk; const assessment = { raceId, ready, activeEntries: activeEntries.length, blockers: [activeEntries.length ? '' : 'no active declared entries', approvalsOk ? '' : 'workflow approvals pending', telemetryOk ? '' : 'telemetry unhealthy', staffingOk ? '' : 'staffing incomplete', resourceOk ? '' : 'starting gate unavailable', postsOk ? '' : 'post positions not drawn', gatesOk ? '' : 'gate assignments incomplete', fieldOk ? '' : 'field size exceeds meet limit', scheduleOk ? '' : 'race schedule conflict'].filter(Boolean), assessedAt: new Date().toISOString(), telemetryStreams: telemetry.map((t) => t.streamId) }; this.update(raceId, actor, 'race.readiness.assessed', (current) => ({ ...current, status: ready ? 'ready' : current.status, readiness: assessment })); return assessment; }
  startRace(raceId: string, token?: ApprovalToken, now = new Date().toISOString()): RaceCard { this.requireApprovalService().assertAuthorized(token, 'race-start', raceId, this.tenantId, now); const race = this.requireRace(raceId); if (race.status !== 'ready') throw new Error('Race must be ready before start'); this.appendExecutionEvent(raceId, { timestamp: now, type: 'off', message: 'approved race start' }, 'starter'); return this.requireRace(raceId); }
  cancelRace(raceId: string, token?: ApprovalToken, now = new Date().toISOString()): RaceCard { this.requireApprovalService().assertAuthorized(token, 'race-cancellation', raceId, this.tenantId, now); return this.update(raceId, 'stewards', 'race.cancelled', (race) => ({ ...race, status: 'cancelled' })); }
  publishOfficialResults(raceId: string, token?: ApprovalToken, now = new Date().toISOString()): RaceCard { this.requireApprovalService().assertAuthorized(token, 'official-results', raceId, this.tenantId, now); if (this.requireRace(raceId).status !== 'running') throw new Error('Official results require a running race'); this.appendExecutionEvent(raceId, { timestamp: now, type: 'official', message: 'approved official result' }, 'stewards'); return this.requireRace(raceId); }
  monitorExecution(raceId: string, event: RaceExecutionEvent, actor = 'race-control'): RaceExecutionEvent[] { if (event.type === 'off' || event.type === 'official') throw new Error('race start and official result events require approved controlled-action methods'); return this.appendExecutionEvent(raceId, event, actor); }
  operationalReport(raceId: string) { const race = this.requireRace(raceId); const events = this.repository.executionEvents(raceId); return { raceId, status: race.status, entries: race.entries.length, activeEntries: race.entries.filter((e) => e.declared && !e.scratched).length, scratches: race.entries.filter((e) => e.scratched).length, approvals: race.approvals, regulatoryControls: race.regulatoryControls, twinLinks: race.twinLinks, telemetryStreams: race.telemetryStreams, criticalEvents: events.filter((e) => e.severity === 'critical').length, events: events.length, workflowInstanceId: race.workflowInstanceId, readiness: race.readiness };
  }
  operationalDashboard(now = new Date().toISOString()): RaceOperationsDashboard { const races = this.repository.listRaces(); const totals = Object.fromEntries(raceStatuses.map((s) => [s, races.filter((r) => r.status === s).length])) as Record<RaceStatus, number>; const byTrack = [...new Set(races.map((r) => r.trackId))].map((trackId) => { const scoped = races.filter((r) => r.trackId === trackId); return { trackId, races: scoped.length, ready: scoped.filter((r) => r.status === 'ready').length, running: scoped.filter((r) => r.status === 'running').length, blocked: scoped.filter((r) => (r.readiness?.blockers.length ?? 0) > 0).length }; }); return { generatedAt: now, totals: { ...totals, all: races.length }, byTrack, upcoming: races.filter((r) => !['official','cancelled'].includes(r.status)).sort((a,b)=>a.scheduledPostTime.localeCompare(b.scheduledPostTime)).map((r) => ({ raceId: r.id, trackId: r.trackId, raceNumber: r.raceNumber, postTime: r.scheduledPostTime, status: r.status, blockers: r.readiness?.blockers ?? [] })), resourceExceptions: races.flatMap((r) => r.resources.filter((x) => x.status === 'unavailable').map((x) => ({ raceId: r.id, resourceId: x.id, type: x.type, status: x.status }))), staffingExceptions: races.map((r) => ({ raceId: r.id, missing: ['stewards','veterinarians','gateCrew'].filter((k) => !(r.staffingPlan as any)?.[k]?.length) })).filter((x) => x.missing.length), executionAlerts: races.flatMap((r) => this.repository.executionEvents(r.id).filter((e) => e.severity && e.severity !== 'info').map((e) => ({ raceId: r.id, timestamp: e.timestamp, message: e.message, severity: e.severity! }))) }; }
  raceOfficeWorkspace(_now = new Date().toISOString(), mock = false): RaceOfficeWorkspace {
    const races = this.repository.listRaces().sort((a, b) => a.scheduledPostTime.localeCompare(b.scheduledPostTime));
    const meets = this.repository.listMeets().sort((a, b) => a.startsOn.localeCompare(b.startsOn));
    const raceDays = this.repository.listDays().sort((a, b) => a.raceDate.localeCompare(b.raceDate));
    return {
      meets: meets.map((meet) => ({ id: meet.id, name: meet.name, trackId: meet.trackId, status: meet.status, startsOn: meet.startsOn, endsOn: meet.endsOn, officialConfig: clone(meet.officialConfig), updatedAt: meet.updatedAt })),
      raceDays: raceDays.map((day) => ({ id: day.id, meetId: day.meetId, trackId: day.trackId, raceDate: day.raceDate, status: day.status, raceIds: [...day.raceIds], updatedAt: day.updatedAt })),
      cards: races.map((race) => ({ id: race.id, trackId: race.trackId, raceDate: race.raceDate, raceNumber: race.raceNumber, scheduledPostTime: race.scheduledPostTime, status: race.status, conditions: clone(race.conditions), entries: race.entries.map(clone), approvals: clone(race.approvals), regulatoryControls: [...race.regulatoryControls], twinLinks: [...race.twinLinks], telemetryStreams: [...race.telemetryStreams], updatedAt: race.updatedAt })),
      readiness: races.map((race) => ({ raceId: race.id, ready: race.readiness?.ready ?? false, activeEntries: race.readiness?.activeEntries ?? this.activeEntries(race).length, blockers: race.readiness?.blockers ?? this.staticRaceBlockers(race), assessedAt: race.readiness?.assessedAt, telemetryStreams: race.readiness?.telemetryStreams ?? race.telemetryStreams })),
      approvalControls: this.raceOfficeApprovalControls(races, meets),
      lifecycle: races.map((race) => {
        const nextAction = this.nextLifecycleApprovalAction(race);
        const approvalRequired = /approval|official results/i.test(nextAction);
        return { raceId: race.id, status: race.status, nextAction, approvalRequired, eventType: this.lifecycleEventType(race), auditId: `audit:${race.id}:${race.status}`, updatedAt: race.updatedAt };
      }),
      mock,
    };
  }
  aiRecommendations(raceId: string, telemetry: RaceTelemetrySignal[]) { const readiness = this.assessReadiness(raceId, telemetry, 'ai-agent'); return { raceId, humanApprovalRequired: true, recommendations: readiness.ready ? ['proceed-to-post-parade'] : readiness.blockers.map((blocker) => `resolve:${blocker}`), evidence: telemetry.map((signal) => signal.streamId), policy: 'AI recommendations are advisory until approved by racing officials' }; }
  listRaces(filter: { trackId?: string; raceDate?: string; status?: RaceStatus } = {}) { return this.repository.listRaces(filter); }
  getRace(raceId: string): RaceCard { return this.requireRace(raceId); }
  apiDefinition(): ApiServiceDefinition { return { id: 'race-operations', name: 'Race Operations', domain: 'race-day', version: 'v1', basePath: '/api/v1/race-operations', description: 'APIs for schedules, entries, declarations, scratches, post positions, race conditions, readiness, gates, staffing, resources, and execution tracking.', owner: { team: 'racing-operations', productOwner: 'Racing Secretary', technicalOwner: 'Race Operations Platform Owner', supportChannel: '#race-ops' }, lifecycle: 'active', auth: ['jwt','oauth2','mtls'], rateLimit: { requests: 600, perSeconds: 60, burst: 100 }, tags: ['race-day','workflow','audit','digital-twin'], slo: { availability: 99.9, latencyMs: 250 }, endpoints: [{ method: 'POST', path: '/meets', summary: 'Create race meet', scopes: ['race:write'] }, { method: 'POST', path: '/race-days', summary: 'Create race day', scopes: ['race:write'] }, { method: 'POST', path: '/race-days/{dayId}/cards', summary: 'Create race card', scopes: ['race:write'] }, { method: 'POST', path: '/approvals/safety-critical-actions', summary: 'Request approval for scratches status changes configuration distance changes and cancellation', scopes: ['race:write'] }, { method: 'POST', path: '/races', summary: 'Schedule race', scopes: ['race:write'] }, { method: 'GET', path: '/races', summary: 'List races', scopes: ['race:read'] }, { method: 'GET', path: '/race-office', summary: 'Race Office workspace DTO', scopes: ['race:read'] }, { method: 'POST', path: '/races/{raceId}/schedule', summary: 'Reschedule race with approval', scopes: ['race:write'] }, { method: 'POST', path: '/races/{raceId}/entries', summary: 'Add entry', scopes: ['race:write'] }, { method: 'POST', path: '/races/{raceId}/declarations', summary: 'Declare entry', scopes: ['race:write'] }, { method: 'POST', path: '/races/{raceId}/declarations:close', summary: 'Close declarations', scopes: ['race:write'] }, { method: 'POST', path: '/races/{raceId}/scratches', summary: 'Scratch entry', scopes: ['race:write'] }, { method: 'POST', path: '/races/{raceId}/conditions', summary: 'Update race conditions', scopes: ['race:write'] }, { method: 'POST', path: '/races/{raceId}/post-positions', summary: 'Draw post positions', scopes: ['race:write'] }, { method: 'POST', path: '/races/{raceId}/readiness', summary: 'Assess readiness', scopes: ['race:write'] }, { method: 'POST', path: '/races/{raceId}/execution-events', summary: 'Track execution', scopes: ['race:write'] }, { method: 'GET', path: '/dashboard', summary: 'Operational dashboard', scopes: ['race:read'] }] }; }

  private raceOfficeApprovalControls(races: RaceCard[], meets: RaceMeet[]): RaceOfficeWorkspace['approvalControls'] { return [...races.flatMap((race) => [
    this.approvalControl('race-start', race.id, `Request race-start approval for Race ${race.raceNumber}`, 'Race start is protected and requires backend authorization before execution.', ['racing-secretary','steward','veterinarian'], ['readiness-assessment','human-approval-record']),
    this.approvalControl('race-office-scratch', race.id, `Request scratch approval for Race ${race.raceNumber}`, 'Scratches affect welfare, wagering, and official card state.', ['veterinarian','steward'], ['scratch-reason','human-approval-record']),
    this.approvalControl('race-cancellation', race.id, `Request race cancellation approval for Race ${race.raceNumber}`, 'Cancellation is a safety-critical official decision.', ['steward'], ['readiness-blockers','human-approval-record']),
    this.approvalControl('race-status-change', race.id, `Request lifecycle status approval for Race ${race.raceNumber}`, 'Lifecycle status changes require a backend approval token.', ['steward'], ['race-status','audit-trail','human-approval-record']),
    this.approvalControl('race-distance-configuration', race.id, `Draft race distance configuration for Race ${race.raceNumber}`, 'Distance changes must enter the track-configuration draft workflow.', ['racing-secretary','track-superintendent','steward'], ['distance-sheet','gps-verification','human-approval-record']),
    this.approvalControl('official-results', race.id, `Request official results approval for Race ${race.raceNumber}`, 'Official results publication is protected and steward-owned.', ['steward'], ['result-chart','inquiry-clearance','human-approval-record']),
  ]), ...meets.map((meet) => this.approvalControl('race-office-configuration', meet.id, `Request official configuration approval for ${meet.name}`, 'Official meet configuration changes affect governed race operations.', ['racing-secretary','steward'], ['rules-version','official-roster','human-approval-record']))]; }
  private approvalControl(action: RaceOfficeApprovalActionDto, target: string, label: string, reason: string, requiredRoles: string[], evidence: string[]): RaceOfficeWorkspace['approvalControls'][number] { return { id: `${action}-${target}`.replace(/[^a-zA-Z0-9:-]+/g, '-'), label, action, target, reason, requiredRoles, evidence, approvalApi: this.approvalApiForRaceOfficeAction(action), locked: true, safetyCritical: true }; }
  private approvalApiForRaceOfficeAction(action: RaceOfficeApprovalActionDto): string { return action === 'race-distance-configuration' ? 'POST /api/v1/track-configuration/draft-requests' : 'POST /api/v1/approvals/controlled-actions'; }
  private nextLifecycleApprovalAction(race: RaceCard): string { const actions = this.nextLifecycleActions(race); return actions.find((action) => /approval|official results/i.test(action)) ?? actions[0] ?? 'none'; }
  private lifecycleEventType(race: RaceCard): string { if (race.readiness) return 'race.readiness.assessed'; if (race.status === 'running') return 'race.started'; if (race.status === 'official') return 'race.official'; if (race.status === 'cancelled') return 'race.cancelled'; return 'race.status.changed'; }
  private appendExecutionEvent(raceId: string, event: RaceExecutionEvent, actor: string): RaceExecutionEvent[] { const events = this.repository.appendExecution(raceId, event); if (event.type === 'off') this.update(raceId, actor, 'race.started', (race) => ({ ...race, status: 'running' })); else if (event.type === 'official') this.update(raceId, actor, 'race.official', (race) => ({ ...race, status: 'official' })); else this.connect('race.execution.tracked', actor, this.requireRace(raceId), { event }); return events; }
  private requireApprovalService(): CentralizedApprovalService { if (!this.approvalService) throw new Error('Approval service is required for controlled race operations'); return this.approvalService; }
  private assertRole(actor: RaceOfficeActor, permission: Permission): void { if (!actor.roles.some((role) => hasPermission(role, permission))) throw new Error(`Actor ${actor.id} lacks ${permission}`); }
  private validateOfficialConfig(config: RaceOfficeOfficialConfig): void { if (!config.stewards.length) throw new Error('Official configuration requires at least one steward'); if (!config.racingSecretary || !config.commission || !config.rulesVersion) throw new Error('Official configuration requires racing secretary, commission, and rules version'); if (config.maxFieldSize < 1 || config.scratchDeadlineMinutes < 0) throw new Error('Official configuration numeric limits are invalid'); }
  private syntheticRace(trackId: string, idSeed: string): RaceCard { return { id: `office:${idSeed}`, trackId, raceDate: new Date().toISOString().slice(0, 10), raceNumber: 0, scheduledPostTime: new Date().toISOString(), status: 'draft', conditions: { surface: 'dirt', distanceFurlongs: 0, classLevel: 'office-record', purse: 0, eligibility: [] }, entries: [], approvals: {}, regulatoryControls: ['HISA', 'ARCI', 'state-racing-commission'], twinLinks: [`track:${trackId}`], telemetryStreams: [], staffingAssignments: [], resources: [], updatedAt: new Date().toISOString() }; }
  private requireMeet(meetId: string): RaceMeet { const meet = this.repository.getMeet(meetId); if (!meet) throw new Error(`Unknown meet ${meetId}`); return meet; }
  private requireDay(dayId: string): RaceDay { const day = this.repository.getDay(dayId); if (!day) throw new Error(`Unknown race day ${dayId}`); return day; }
  private mapEntry(raceId: string, entryId: string, actor: string, activity: RaceActivityType, mapper: (entry: RaceEntry) => RaceEntry): RaceCard { const race = this.requireRace(raceId); this.assertMutableRace(race, 'update entries'); if (!race.entries.some((entry) => entry.id === entryId)) throw new Error(`Unknown race entry ${entryId}`); return this.update(raceId, actor, activity, (current) => ({ ...current, status: activity === 'race.entry.scratched' ? current.status : 'declared', entries: current.entries.map((entry) => entry.id === entryId ? mapper(entry) : entry) })); }
  private update(raceId: string, actor: string, activity: RaceActivityType, mapper: (race: RaceCard) => RaceCard): RaceCard { const next = { ...mapper(this.requireRace(raceId)), updatedAt: new Date().toISOString() }; return this.saveAndConnect(next, activity, actor, { raceId }); }
  private saveAndConnect(race: RaceCard, activity: RaceActivityType, actor: string, payload: Record<string, unknown>): RaceCard { const saved = this.repository.saveRace(race); this.connect(activity, actor, saved, payload); return saved; }
  private connect(activity: RaceActivityType, actor: string, race: RaceCard, payload: Record<string, unknown>): void { const correlationId = `${race.id}:${activity}`; this.auditLog?.append({ id: id('audit-race'), type: activity.includes('twin') ? 'digital-twin-update' : activity.includes('approved') ? 'approval' : 'workflow-action', actor, timestamp: new Date().toISOString(), payload: { activity, ...payload }, subjectId: race.id, tenantId: this.tenantId, workflowId: race.workflowInstanceId, correlationId, severity: activity.includes('cancelled') ? 'warning' : 'info', regulations: race.regulatoryControls }); void this.eventBus?.publish({ type: activity, payload: { raceId: race.id, trackId: race.trackId, status: race.status, race, ...payload }, aggregateId: race.id, correlationId, producer: 'race-operations', metadata: { compliance: 'regulated', team: 'racing-operations', accountableRole: 'racing-secretary' } }); for (const twinId of race.twinLinks.filter((x) => x.startsWith('twin:'))) { try { this.twinRuntime?.updateState({ twinId, actor, sourceEventId: correlationId, patch: { raceId: race.id, raceStatus: race.status, raceNumber: race.raceNumber, scheduledPostTime: race.scheduledPostTime, conditions: race.conditions, entries: race.entries.length, activeEntries: this.activeEntries(race).length, scratches: race.entries.filter((entry) => entry.scratched).length, postPositions: race.entries.filter((entry) => entry.postPosition).map((entry) => ({ entryId: entry.id, postPosition: entry.postPosition })), readiness: race.readiness } }); } catch { /* twin may be provisioned asynchronously */ } } }
  private requireRace(raceId: string): RaceCard { const race = this.repository.getRace(raceId); if (!race) throw new Error(`Unknown race ${raceId}`); return race; }
  private validateDateRange(startsOn: string, endsOn: string): void { if (endsOn < startsOn) throw new Error('Meet end date must be on or after start date'); }
  private validatePostTime(postTime: string): void { if (Number.isNaN(Date.parse(postTime))) throw new Error('scheduledPostTime must be a valid timestamp'); }
  private validateRaceSchedule(input: Pick<RaceCard, 'id' | 'trackId' | 'raceDate' | 'raceNumber' | 'scheduledPostTime' | 'conditions'> & Partial<Pick<RaceCard, 'entries'>>, existingRaceId = input.id): void { if (input.raceNumber < 1) throw new Error('Race number must be positive'); this.validatePostTime(input.scheduledPostTime); if (input.conditions.distanceFurlongs <= 0) throw new Error('Race distance must be positive'); if (input.conditions.purse < 0) throw new Error('Race purse cannot be negative'); const conflicts = this.repository.listRaces({ trackId: input.trackId, raceDate: input.raceDate }).filter((race) => race.id !== existingRaceId && (race.raceNumber === input.raceNumber || race.scheduledPostTime === input.scheduledPostTime)); if (conflicts.length) throw new Error('Race schedule conflict for race number or post time'); }
  private validateStatusTransition(current: RaceStatus, next: RaceStatus): void { if (current === 'official' && next !== 'official') throw new Error('Official races cannot be reopened without a dedicated results-modification workflow'); if (current === 'cancelled' && next !== 'cancelled') throw new Error('Cancelled races cannot be reopened without a new race card'); }
  private assertMutableRace(race: RaceCard, action: string): void { if (['running','official','cancelled'].includes(race.status)) throw new Error(`Cannot ${action} after race is ${race.status}`); }
  private activeEntries(race: RaceCard): RaceEntry[] { return race.entries.filter((entry) => entry.declared && !entry.scratched); }
  private maxFieldSizeForRace(race: RaceCard): number { const day = this.repository.listDays().find((candidate) => candidate.raceIds.includes(race.id)); const meet = day ? this.repository.getMeet(day.meetId) : undefined; return meet?.officialConfig.maxFieldSize ?? Number.POSITIVE_INFINITY; }
  private validateFieldSize(race: RaceCard, entries: RaceEntry[]): void { const active = entries.filter((entry) => entry.declared && !entry.scratched); if (active.length > this.maxFieldSizeForRace(race)) throw new Error('Declared field exceeds meet maximum field size'); }
  private scheduleConflictsFor(race: RaceCard): RaceCard[] { return this.repository.listRaces({ trackId: race.trackId, raceDate: race.raceDate }).filter((candidate) => candidate.id !== race.id && (candidate.raceNumber === race.raceNumber || candidate.scheduledPostTime === race.scheduledPostTime)); }
  private staticRaceBlockers(race: RaceCard): string[] { const active = this.activeEntries(race); return [active.length ? '' : 'no active declared entries', Object.values(race.approvals).every((state) => state === 'approved' || state === 'not-required') ? '' : 'workflow approvals pending', active.every((entry) => entry.postPosition) ? '' : 'post positions not drawn', active.every((entry) => entry.gate) ? '' : 'gate assignments incomplete', race.resources.some((resource) => resource.type === 'starting-gate' && resource.status === 'allocated') ? '' : 'starting gate unavailable'].filter(Boolean); }
  private nextLifecycleActions(race: RaceCard): string[] { if (race.status === 'scheduled') return ['add entries', 'open declarations']; if (race.status === 'entries-open') return ['declare entries', 'close declarations']; if (race.status === 'declared') return ['draw post positions']; if (race.status === 'post-positions-drawn') return ['assign gates', 'assess readiness']; if (race.status === 'ready') return ['request race-start approval']; if (race.status === 'running') return ['monitor execution', 'publish official results with approval']; return []; }
}

export function raceOperationsControlMatrix() { return [ { workflow: 'schedule-to-card', approvals: ['racingOffice', 'stewards'], controls: ['condition-book', 'commission-rules'], systems: ['digital-twin', 'telemetry', 'event-bus'] }, { workflow: 'entries-declarations-scratches', approvals: ['racingOffice', 'veterinarian', 'stewards'], controls: ['eligibility', 'medication', 'welfare'], systems: ['passport', 'approval-store', 'audit-log'] }, { workflow: 'race-day-readiness', approvals: ['operations', 'safety', 'stewards'], controls: ['surface', 'weather', 'gate', 'staffing'], systems: ['iot', 'vision', 'ai-recommendations'] }, { workflow: 'execution-reporting', approvals: ['stewards'], controls: ['official-order', 'incident-evidence', 'regulatory-retention'], systems: ['telemetry', 'video', 'compliance-vault'] } ]; }
