import type { RouteSupportMetadata } from '../domain/support';

export const routes = [
  {
    id: 'dashboard',
    path: '/dashboard',
    aliases: ['/', '/operations', '/command-center', '/operations-command-center'],
    label: 'Dashboard',
    navigationGroup: 'Command',
    iconKey: 'command-center',
    requiredPermission: 'read:any',
    requiredRoles: 'authenticated',
    supportStatus: 'live-api',
    dataSource: 'Backend operations, platform health, approvals, audit, and AI governance routes.',
    pageComponent: 'DashboardPage',
    backendPaths: ['/api/v1/operations/command-center', '/api/v1/platform/health', '/api/v1/ai-control-plane/recommendations', '/api/v1/ai-governance/workspace', '/api/v1/approvals/requests', '/api/v1/audit/events', '/api/v1/kpis'],
    sharedTypes: ['OperationsCommandCenterDto', 'PlatformHealthWorkspaceDto', 'AIControlPlaneRecommendationDto', 'AIGovernanceWorkspaceDto', 'ApprovalDto', 'AuditEventDto', 'KPIWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [
      { source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Operations and platform health routes are implemented.' },
      { source: 'shared-contract', reference: 'packages/shared/src/apiContracts.ts', summary: 'Dashboard DTOs are shared.' },
    ],
    limitations: ['Platform observability is facade-level, not production telemetry.'],
  },
  {
    id: 'raceDay',
    path: '/race-day',
    aliases: ['/races', '/race-office', '/race-operations', '/race-day-readiness', '/readiness', '/track-map', '/starting-gate', '/surface', '/surface-intelligence'],
    label: 'Race Day',
    navigationGroup: 'Operations',
    iconKey: 'race-day',
    requiredPermission: 'race:request-start',
    requiredRoles: 'authenticated',
    supportStatus: 'facade-api',
    dataSource: 'Race summaries, race office workspace, race-day readiness, surface intelligence, and track configuration map.',
    pageComponent: 'RaceDayPage',
    backendPaths: ['/api/v1/races', '/api/v1/race-operations/race-office', '/api/v1/race-day-readiness/dashboard', '/api/v1/surface-intelligence/workspace', '/api/v1/track-configuration/map'],
    sharedTypes: ['RaceDto', 'RaceOfficeWorkspaceDto', 'RaceDayReadinessDashboardDto', 'SurfaceIntelligenceDto', 'TrackMapDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Race-day routes compose race office and readiness service outputs.' }],
    limitations: ['No race start/stop/result execution controls are exposed.'],
  },
  {
    id: 'equine',
    path: '/equine',
    aliases: ['/equine-intelligence', '/horse-profile', '/horses', '/barns', '/barn-operations'],
    label: 'Equine',
    navigationGroup: 'Operations',
    iconKey: 'horse',
    requiredPermission: 'vet:review',
    requiredRoles: 'authenticated',
    supportStatus: 'facade-api',
    dataSource: 'Equine intelligence horse profile plus barn operations readiness with veterinary privacy boundaries.',
    pageComponent: 'EquinePage',
    backendPaths: ['/api/v1/equine-intelligence/horses/horse-1', '/api/v1/barn-operations/workspace'],
    sharedTypes: ['EquineIntelligenceDto', 'BarnOperationsDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/services/equine', summary: 'Equine privacy service exists but route is facade-backed.' }],
    limitations: ['Veterinary data is privacy-scoped and not shown by default.'],
  },
  {
    id: 'approvals',
    path: '/approvals',
    aliases: ['/approval-queue', '/approval-center', '/approvals-center'],
    label: 'Approvals',
    navigationGroup: 'Governance',
    iconKey: 'approval',
    requiredPermission: 'ai:approve',
    requiredRoles: 'authenticated',
    supportStatus: 'live-api',
    dataSource: 'Central approval records and approval request routes.',
    pageComponent: 'ApprovalsPage',
    backendPaths: ['/api/v1/approvals/requests'],
    sharedTypes: ['ApprovalDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/approvals.ts', summary: 'Centralized approval service is implemented in memory.' }],
    limitations: ['Frontend may request approval only; it cannot authorize execution.'],
  },
  {
    id: 'incidents',
    path: '/incidents',
    aliases: ['/incident-center', '/security-incidents', '/emergency', '/emergency-operations'],
    label: 'Incidents',
    navigationGroup: 'Operations',
    iconKey: 'incident',
    requiredPermission: 'incident:manage',
    requiredRoles: 'authenticated',
    supportStatus: 'facade-api',
    dataSource: 'Security operations and emergency operations workspaces.',
    pageComponent: 'IncidentsPage',
    backendPaths: ['/api/v1/security-operations/workspace', '/api/v1/emergency-operations/workspace'],
    sharedTypes: ['SecurityOperationsDto', 'EmergencyOperationsDto'],
    databaseSupport: 'partial',
    evidence: [
      { source: 'backend-route', reference: 'apps/api/src/securityOps.ts', summary: 'Security incidents are backend-facade supported.' },
      { source: 'backend-route', reference: 'apps/api/src/emergencyOperations.ts', summary: 'Emergency operations workspace is generated from service-backed runtime data.' },
    ],
    limitations: ['Frontend has no direct emergency execution path; authorized humans retain emergency authority and AI may not block.'],
  },
  {
    id: 'compliance',
    path: '/compliance',
    aliases: ['/compliance-center', '/control-library', '/controls'],
    label: 'Compliance',
    navigationGroup: 'Governance',
    iconKey: 'compliance',
    requiredPermission: 'compliance:audit',
    requiredRoles: ['admin', 'compliance-officer', 'read-only-auditor'],
    supportStatus: 'facade-api',
    dataSource: 'Compliance control library readiness metadata.',
    pageComponent: 'CompliancePage',
    backendPaths: ['/api/v1/compliance/control-library'],
    sharedTypes: ['ComplianceControlLibraryDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Compliance control-library route returns readiness mappings and certification-candidate metadata.' }],
    limitations: ['No external certification, audit opinion, or regulator approval is claimed.'],
  },
  {
    id: 'security',
    path: '/security',
    aliases: ['/security-operations', '/security-center'],
    label: 'Security',
    navigationGroup: 'Operations',
    iconKey: 'security',
    requiredPermission: 'security:manage',
    requiredRoles: ['admin', 'security', 'compliance-officer'],
    supportStatus: 'facade-api',
    dataSource: 'Security operations workspace.',
    pageComponent: 'SecurityPage',
    backendPaths: ['/api/v1/security-operations/workspace'],
    sharedTypes: ['SecurityOperationsDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/securityOps.ts', summary: 'Security workspace route is active.' }],
    limitations: ['Sensitive fields must stay role-filtered at backend boundary.'],
  },
  {
    id: 'facilities',
    path: '/facilities',
    aliases: ['/facilities-maintenance', '/facility-maintenance', '/maintenance'],
    label: 'Facilities',
    navigationGroup: 'Operations',
    iconKey: 'facility',
    requiredPermission: 'track:readings',
    requiredRoles: 'authenticated',
    supportStatus: 'live-api',
    dataSource: 'Facilities maintenance service backed by RACR assets, inspections, work orders, approvals, audit, events, and Digital Twin health.',
    pageComponent: 'FacilitiesPage',
    backendPaths: ['/api/v1/facilities-maintenance/workspace'],
    sharedTypes: ['FacilitiesMaintenanceWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [
      { source: 'backend-route', reference: 'apps/api/src/facilitiesMaintenance.ts', summary: 'Facilities workspace is generated by FacilitiesMaintenanceService.' },
      { source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Runtime API state seeds service-backed facilities assets, inspections, work orders, and approvals.' },
    ],
    limitations: ['Current implementation is in-memory; return-to-service and safety-critical maintenance actions remain approval-gated.'],
  },
  {
    id: 'ticketing',
    path: '/ticketing',
    aliases: ['/tickets', '/fan-ticketing'],
    label: 'Ticketing',
    navigationGroup: 'Enterprise',
    iconKey: 'ticket',
    requiredPermission: 'ticketing:manage',
    requiredRoles: ['admin', 'ticketing-manager'],
    supportStatus: 'facade-api',
    dataSource: 'Finance ticketing service state with active tickets, revenue summary, and payment control boundaries.',
    pageComponent: 'TicketingPage',
    backendPaths: ['/api/v1/services/finance/ticketing'],
    sharedTypes: ['FinanceTicketingWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/services/financeService.ts', summary: 'Ticketing workspace is generated from FinanceService ticket state.' }],
    limitations: ['No sales execution, payment capture, or attendee identity mutation is exposed from the frontend.'],
  },
  {
    id: 'finance',
    path: '/finance',
    aliases: ['/payments', '/payouts'],
    label: 'Finance',
    navigationGroup: 'Enterprise',
    iconKey: 'finance',
    requiredPermission: 'finance:payout',
    requiredRoles: ['admin', 'finance'],
    supportStatus: 'facade-api',
    dataSource: 'Finance service read model for ticket revenue and protected payout approval posture.',
    pageComponent: 'FinancePage',
    backendPaths: ['/api/v1/services/finance/ticketing'],
    sharedTypes: ['FinanceTicketingWorkspaceDto', 'ProtectedAction'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/services/financeService.ts', summary: 'Finance payout release is protected by the approval gateway.' }],
    limitations: ['Payouts are protected actions and cannot execute from the UI.'],
  },
  {
    id: 'federation',
    path: '/federation',
    aliases: ['/federation-workspace', '/multi-track', '/network'],
    label: 'Federation',
    navigationGroup: 'Enterprise',
    iconKey: 'federation',
    requiredPermission: 'compliance:audit',
    requiredRoles: ['admin', 'compliance-officer', 'read-only-auditor'],
    supportStatus: 'facade-api',
    dataSource: 'Aggregate-only federation workspace metadata.',
    pageComponent: 'FederationPage',
    backendPaths: ['/api/v1/federation/workspace'],
    sharedTypes: ['FederationWorkspaceDto'],
    databaseSupport: 'none',
    evidence: [{ source: 'shared-contract', reference: 'FederationWorkspaceDto', summary: 'Aggregate-only federation contract exists.' }],
    limitations: ['No raw cross-track data is exposed.'],
  },
  {
    id: 'dataHub',
    path: '/data-hub',
    aliases: ['/api-hub', '/api-hub-dashboard', '/data-api-hub', '/racing-data', '/racing-data-api-hub'],
    label: 'Data Hub',
    navigationGroup: 'Enterprise',
    iconKey: 'data-hub',
    requiredPermission: 'compliance:audit',
    requiredRoles: ['admin', 'compliance-officer', 'racing-secretary', 'read-only-auditor'],
    supportStatus: 'facade-api',
    dataSource: 'Racing Data API Hub readiness metadata.',
    pageComponent: 'DataHubPage',
    backendPaths: ['/api/v1/racing-data'],
    sharedTypes: ['RacingDataWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Racing Data API Hub route returns provider readiness, lineage, quality, and export-control metadata.' }],
    limitations: ['Licensed provider readiness only; no scraping or live provider claim.'],
  },
  {
    id: 'audit',
    path: '/audit',
    aliases: ['/audit-events', '/audit-ledger', '/ledger'],
    label: 'Audit',
    navigationGroup: 'Governance',
    iconKey: 'audit',
    requiredPermission: 'compliance:audit',
    requiredRoles: ['admin', 'compliance-officer', 'read-only-auditor'],
    supportStatus: 'live-api',
    dataSource: 'Audit event records and approval references.',
    pageComponent: 'AuditPage',
    backendPaths: ['/api/v1/audit/events'],
    sharedTypes: ['AuditEventDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/auditLog.ts', summary: 'Immutable audit facade is active in memory.' }],
    limitations: ['Hash integrity is reference-level until durable audit storage is wired.'],
  },
  {
    id: 'admin',
    path: '/admin',
    aliases: ['/administration', '/platform-health'],
    label: 'Admin',
    navigationGroup: 'Administration',
    iconKey: 'admin',
    requiredPermission: 'read:any',
    requiredRoles: ['admin'],
    supportStatus: 'facade-api',
    dataSource: 'Platform health facade with service, dependency, approval-engine, deployment, and frontend health signals.',
    pageComponent: 'AdminPage',
    backendPaths: ['/api/v1/platform/health'],
    sharedTypes: ['PlatformHealthWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/platformObservability.ts', summary: 'Admin page reads platform health and dependency records.' }],
    limitations: ['No user, tenant provisioning, privileged elevation, or settings persistence route exists.'],
  },
  {
    id: 'settings',
    path: '/settings',
    aliases: ['/ai-policy', '/policy', '/preferences'],
    label: 'Settings',
    navigationGroup: 'Administration',
    iconKey: 'settings',
    requiredPermission: 'read:any',
    requiredRoles: 'authenticated',
    supportStatus: 'facade-api',
    dataSource: 'AI control-plane policy route with protected actions, evidence requirements, and governance mappings.',
    pageComponent: 'SettingsPage',
    backendPaths: ['/api/v1/ai-control-plane/policy'],
    sharedTypes: ['AIControlPlanePolicyDto'],
    databaseSupport: 'none',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Settings reads AI control-plane policy metadata from the active API facade.' }],
    limitations: ['No model-serving switch, runtime policy mutation, secret management, or execution toggles.'],
  },
] as const satisfies readonly RouteSupportMetadata[];

export type AppRoute = typeof routes[number];

export const routeById = Object.fromEntries(routes.map((route) => [route.id, route])) as Record<AppRoute['id'], AppRoute>;
export const defaultRoute = routeById.dashboard;

export function resolveRoute(pathname: string): AppRoute {
  const normalized = pathname === '/' ? '/dashboard' : pathname.replace(/\/+$/, '') || '/dashboard';
  return routes.find((route) => {
    if (route.path === normalized) return true;
    const aliases = (route as RouteSupportMetadata).aliases;
    return aliases?.some((alias) => normalized === alias || normalized.startsWith(`${alias}/`));
  }) ?? defaultRoute;
}
