import type { RouteSupportMetadata } from '../domain/support';
import { backendContractPathsForRoute } from '../api/paths';

const routePermissions = {
  dashboard: 'read:any',
  raceDay: 'read:any',
  equine: 'vet:review',
  approvals: 'read:any',
  incidents: 'incident:manage',
  compliance: 'compliance:report',
  security: 'security:read',
  facilities: 'track:readings',
  ticketing: 'ticketing:manage',
  finance: 'finance:payout',
  federation: 'compliance:report',
  dataHub: 'data-hub:read',
  audit: 'audit:read',
  admin: 'service:operate',
  settings: 'ai:read',
} as const satisfies Record<RouteSupportMetadata['id'], RouteSupportMetadata['requiredPermission']>;

export const routes = [
  {
    id: 'dashboard',
    path: '/dashboard',
    label: 'Command Center',
    navigationGroup: 'Command',
    iconKey: 'command-center',
    requiredPermission: routePermissions.dashboard,
    requiredRoles: 'authenticated',
    supportStatus: 'facade-api',
    dataSource: 'Monitor race-day readiness, operational risk, approvals, audit evidence, and advisory AI from one governed command view.',
    backendPaths: backendContractPathsForRoute('dashboard'),
    sharedTypes: ['OperationsCommandCenterDto', 'PlatformHealthWorkspaceDto', 'AIControlPlaneRecommendationDto', 'AIGovernanceWorkspaceDto', 'ApprovalDto', 'AuditEventDto', 'KPIWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [
      { source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Operations and platform health read routes are wired.' },
      { source: 'shared-contract', reference: 'packages/shared/src/apiContracts.ts', summary: 'Dashboard DTOs are shared.' },
    ],
    limitations: ['Platform observability is facade-level, not production telemetry.'],
  },
  {
    id: 'raceDay',
    path: '/race-day',
    label: 'Race Day',
    navigationGroup: 'Operations',
    iconKey: 'race-day',
    requiredPermission: routePermissions.raceDay,
    requiredRoles: 'authenticated',
    supportStatus: 'facade-api',
    dataSource: 'Review race office readiness, surface conditions, track configuration, approvals, and safety guardrails before post time.',
    backendPaths: backendContractPathsForRoute('raceDay'),
    sharedTypes: ['RaceDto', 'RaceOfficeWorkspaceDto', 'RaceDayReadinessDashboardDto', 'SurfaceIntelligenceDto', 'TrackMapDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Race-day routes compose race office and readiness service outputs.' }],
    limitations: ['No race start, stop, result, scratch, cancellation, status/configuration, or gate/config execution controls are exposed.'],
  },
  {
    id: 'equine',
    path: '/equine',
    label: 'Equine Intelligence',
    navigationGroup: 'Operations',
    iconKey: 'horse',
    requiredPermission: routePermissions.equine,
    requiredRoles: 'authenticated',
    supportStatus: 'facade-api',
    dataSource: 'Review horse lifecycle, eligibility, welfare, barn readiness, and veterinary status in one equine workspace.',
    backendPaths: backendContractPathsForRoute('equine'),
    sharedTypes: ['EquineIntelligenceDto', 'BarnOperationsDto'],
    databaseSupport: 'partial',
    evidence: [
      { source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Horse profile facade exposes seeded EquineIntelligenceDto data.' },
      { source: 'backend-route', reference: 'apps/api/src/barnOperations.ts', summary: 'Barn workspace data is exposed through the barn operations facade.' },
    ],
    limitations: ['Detailed veterinary records are omitted here; this route renders a seeded equine workspace summary and barn facade data.'],
  },
  {
    id: 'approvals',
    path: '/approvals',
    label: 'Approvals',
    navigationGroup: 'Governance',
    iconKey: 'approval',
    requiredPermission: routePermissions.approvals,
    requiredRoles: 'authenticated',
    supportStatus: 'live-api',
    dataSource: 'Review visible approval request records, escalation metadata, and supporting evidence.',
    backendPaths: backendContractPathsForRoute('approvals'),
    sharedTypes: ['ApprovalDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'GET /approvals/requests exposes view-only approval records.' }],
    limitations: ['This workspace currently renders the approval queue read-only; backend draft request and approve/reject handlers exist, but no approval decision or protected execution controls are exposed from this page.'],
  },
  {
    id: 'incidents',
    path: '/incidents',
    label: 'Incident Review',
    navigationGroup: 'Operations',
    iconKey: 'incident',
    requiredPermission: routePermissions.incidents,
    requiredRoles: ['admin', 'security'],
    supportStatus: 'facade-api',
    dataSource: 'Review emergency posture, incident metadata, security incident summaries, and response references without exposing direct command controls.',
    backendPaths: backendContractPathsForRoute('incidents'),
    sharedTypes: ['SecurityOperationsDto', 'EmergencyOperationsDto'],
    databaseSupport: 'partial',
    evidence: [
      { source: 'backend-route', reference: 'apps/api/src/securityOps.ts', summary: 'Security incidents are backend-facade supported.' },
      { source: 'backend-route', reference: 'apps/api/src/emergencyOperations.ts', summary: 'Emergency operations workspace is generated from service-backed runtime data.' },
    ],
    limitations: ['Frontend has no direct emergency execution path; authorized humans retain emergency authority and AI may not block. Security data is limited to the facade records returned by the route.'],
  },
  {
    id: 'compliance',
    path: '/compliance',
    label: 'Compliance',
    navigationGroup: 'Governance',
    iconKey: 'compliance',
    requiredPermission: routePermissions.compliance,
    requiredRoles: ['admin', 'compliance-officer', 'read-only-auditor'],
    supportStatus: 'facade-api',
    dataSource: 'Review compliance frameworks, control mappings, and internal readiness metadata from the control-library facade.',
    backendPaths: backendContractPathsForRoute('compliance'),
    sharedTypes: ['ComplianceControlLibraryDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Compliance control-library route returns internal readiness mappings and candidate evidence metadata.' }],
    limitations: ['No external certification, audit opinion, or regulator approval is claimed.'],
  },
  {
    id: 'security',
    path: '/security',
    label: 'Security Operations',
    navigationGroup: 'Operations',
    iconKey: 'security',
    requiredPermission: routePermissions.security,
    requiredRoles: ['admin', 'security', 'compliance-officer'],
    supportStatus: 'facade-api',
    dataSource: 'Review security incident and camera-health summary metadata from a facade-backed DTO.',
    backendPaths: backendContractPathsForRoute('security'),
    sharedTypes: ['SecurityOperationsDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/securityOps.ts', summary: 'Security workspace route is active.' }],
    limitations: ['This HTTP facade returns masked security fields. Frontend is read-only; no incident escalation, investigation mutation/export, camera control, camera-health update, or emergency-zone action is exposed.'],
  },
  {
    id: 'facilities',
    path: '/facilities',
    label: 'Facilities Maintenance',
    navigationGroup: 'Operations',
    iconKey: 'facility',
    requiredPermission: routePermissions.facilities,
    requiredRoles: 'authenticated',
    supportStatus: 'live-api',
    dataSource: 'Review track assets, inspections, work orders, maintenance risk, approvals, audit evidence, and in-memory Digital Twin health.',
    backendPaths: backendContractPathsForRoute('facilities'),
    sharedTypes: ['FacilitiesMaintenanceWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [
      { source: 'backend-route', reference: 'apps/api/src/facilitiesMaintenance.ts', summary: 'Facilities workspace is generated by FacilitiesMaintenanceService.' },
      { source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Runtime API state seeds service-backed facilities assets, inspections, work orders, and approvals.' },
    ],
    limitations: ['Current implementation is in-memory and read-only from the frontend; return-to-service and safety-critical maintenance transitions are not exposed as UI execution controls.'],
  },
  {
    id: 'ticketing',
    path: '/ticketing',
    label: 'Ticketing',
    navigationGroup: 'Enterprise',
    iconKey: 'ticket',
    requiredPermission: routePermissions.ticketing,
    requiredRoles: ['admin', 'ticketing-manager', 'finance'],
    supportStatus: 'facade-api',
    dataSource: 'Understand ticket state, active-ticket value, race-day coverage, and payment-control boundaries.',
    backendPaths: backendContractPathsForRoute('ticketing'),
    sharedTypes: ['FinanceTicketingWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/services/financeService.ts', summary: 'Ticketing workspace is generated from FinanceService ticket state.' }],
    limitations: ['No sales execution, payment capture, or attendee identity mutation is exposed from the frontend.'],
  },
  {
    id: 'finance',
    path: '/finance',
    label: 'Finance & Payouts',
    navigationGroup: 'Enterprise',
    iconKey: 'finance',
    requiredPermission: routePermissions.finance,
    requiredRoles: ['admin', 'finance'],
    supportStatus: 'facade-api',
    dataSource: 'Review active ticket value, released payout records, finance controls, and approval/audit boundaries.',
    backendPaths: backendContractPathsForRoute('finance'),
    sharedTypes: ['FinanceTicketingWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/services/financeService.ts', summary: 'Finance payout requests are protected by the APEX approval gateway; this page reads ticketing/payout state only.' }],
    limitations: ['Payouts are protected actions and cannot execute from the UI.'],
  },
  {
    id: 'federation',
    path: '/federation',
    label: 'Federation',
    navigationGroup: 'Enterprise',
    iconKey: 'federation',
    requiredPermission: routePermissions.federation,
    requiredRoles: ['admin', 'compliance-officer', 'read-only-auditor'],
    supportStatus: 'facade-api',
    dataSource: 'Compare aggregate, anonymized racetrack readiness and federation metadata without exposing raw cross-track records.',
    backendPaths: backendContractPathsForRoute('federation'),
    sharedTypes: ['FederationWorkspaceDto'],
    databaseSupport: 'none',
    evidence: [
      { source: 'backend-route', reference: 'apps/api/src/federation.ts', summary: 'Federation workspace facade returns aggregate-only metadata.' },
      { source: 'shared-contract', reference: 'FederationWorkspaceDto', summary: 'Aggregate-only federation contract exists.' },
    ],
    limitations: ['Facade metadata only; no raw cross-track records, tenant provisioning, federation exports, or execution endpoints are exposed.'],
  },
  {
    id: 'dataHub',
    path: '/data-hub',
    label: 'Data Hub',
    navigationGroup: 'Enterprise',
    iconKey: 'data-hub',
    requiredPermission: routePermissions.dataHub,
    requiredRoles: ['admin', 'compliance-officer', 'racing-secretary', 'read-only-auditor'],
    supportStatus: 'facade-api',
    dataSource: 'Inspect provider license-readiness metadata, lineage, quality, entity resolution, and sharing-control posture.',
    backendPaths: backendContractPathsForRoute('dataHub'),
    sharedTypes: ['RacingDataWorkspaceDto'],
    databaseSupport: 'none',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Racing Data API Hub route returns provider readiness, lineage, quality, and sharing-control metadata.' }],
    limitations: ['Provider license-readiness metadata only; no external license, scraping, export, or live provider claim.'],
  },
  {
    id: 'audit',
    path: '/audit',
    label: 'Audit',
    navigationGroup: 'Governance',
    iconKey: 'audit',
    requiredPermission: routePermissions.audit,
    requiredRoles: ['admin', 'compliance-officer', 'read-only-auditor'],
    supportStatus: 'live-api',
    dataSource: 'Review audit event metadata, approval references, evidence IDs, and integrity references.',
    backendPaths: backendContractPathsForRoute('audit'),
    sharedTypes: ['AuditEventDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'GET /audit/events exposes audit event records with hash references.' }],
    limitations: ['Hash integrity is reference-level until durable audit storage and verification workflows are wired.'],
  },
  {
    id: 'admin',
    path: '/admin',
    label: 'Platform Health',
    navigationGroup: 'Administration',
    iconKey: 'admin',
    requiredPermission: routePermissions.admin,
    requiredRoles: ['admin', 'operations-admin'],
    supportStatus: 'facade-api',
    dataSource: 'Review facade-level platform health metadata: seeded service records, dependency declarations, approval queue counts, deployment-boundary assumptions, and frontend error signal declarations.',
    backendPaths: backendContractPathsForRoute('admin'),
    sharedTypes: ['PlatformHealthWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/platformObservability.ts', summary: 'Admin page reads platform health and dependency records.' }],
    limitations: ['No user, tenant provisioning, privileged elevation, or settings persistence route exists.'],
  },
  {
    id: 'settings',
    path: '/settings',
    label: 'AI Policy',
    navigationGroup: 'Governance',
    iconKey: 'settings',
    requiredPermission: routePermissions.settings,
    requiredRoles: 'authenticated',
    supportStatus: 'facade-api',
    dataSource: 'Review advisory AI policies, protected actions, evidence requirements, and human approval mappings.',
    backendPaths: backendContractPathsForRoute('settings'),
    sharedTypes: ['AIControlPlanePolicyDto'],
    databaseSupport: 'none',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Settings reads AI control-plane policy metadata from the active API facade.' }],
    limitations: ['No model-serving switch, runtime policy mutation, secret management, or execution toggles.'],
  },
] as const satisfies readonly RouteSupportMetadata[];

export type AppRoute = typeof routes[number];

export const routeById = Object.fromEntries(routes.map((route) => [route.id, route])) as Record<AppRoute['id'], AppRoute>;
export const defaultRoute = routeById.dashboard;

export function resolveRoute(pathname: string): AppRoute {
  const normalized = pathname === '/' ? '/dashboard' : pathname.replace(/\/+$/, '') || '/dashboard';
  return routes.find((route) => route.path === normalized || normalized.startsWith(`${route.path}/`)) ?? defaultRoute;
}

