import type { RouteSupportMetadata } from '../domain/support';
import { backendContractPathsForRoute } from '../api/paths';
import { frontendRoutePermissionRegistry } from '@trackmind/shared';

export const routes = [
  {
    id: 'dashboard',
    path: '/dashboard',
    label: 'Dashboard',
    navigationGroup: 'Command',
    iconKey: 'command-center',
    requiredPermission: frontendRoutePermissionRegistry.dashboard,
    requiredRoles: 'authenticated',
    supportStatus: 'live-api',
    dataSource: 'Backend operations, platform health, approvals, audit, and AI governance routes.',
    backendPaths: backendContractPathsForRoute('dashboard'),
    sharedTypes: ['OperationsCommandCenterDto', 'PlatformHealthWorkspaceDto', 'AIControlPlaneRecommendationDto', 'AIGovernanceWorkspaceDto', 'ApprovalDto', 'AuditEventDto', 'KPIWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [
      { source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Operations and platform health routes are implemented.' },
      { source: 'shared-contract', reference: 'packages/shared/src/apiContracts.ts', summary: 'Dashboard DTOs are shared.' },
    ],
    limitations: ['Platform observability is facade-level, not production telemetry.'],
  },
  {
    id: 'raceDay',
    path: '/race-day',
    label: 'Race Day',
    navigationGroup: 'Operations',
    iconKey: 'race-day',
    requiredPermission: frontendRoutePermissionRegistry.raceDay,
    requiredRoles: 'authenticated',
    supportStatus: 'facade-api',
    dataSource: 'Race summaries, race office workspace, race-day readiness, surface intelligence, and track configuration map.',
    backendPaths: backendContractPathsForRoute('raceDay'),
    sharedTypes: ['RaceDto', 'RaceOfficeWorkspaceDto', 'RaceDayReadinessDashboardDto', 'SurfaceIntelligenceDto', 'TrackMapDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Race-day routes compose race office and readiness service outputs.' }],
    limitations: ['No race start/stop/result execution controls are exposed.'],
  },
  {
    id: 'equine',
    path: '/equine',
    label: 'Equine',
    navigationGroup: 'Operations',
    iconKey: 'horse',
    requiredPermission: frontendRoutePermissionRegistry.equine,
    requiredRoles: 'authenticated',
    supportStatus: 'facade-api',
    dataSource: 'Equine intelligence horse profile plus barn operations readiness with veterinary privacy boundaries.',
    backendPaths: backendContractPathsForRoute('equine'),
    sharedTypes: ['EquineIntelligenceDto', 'BarnOperationsDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/services/equine', summary: 'Equine privacy service exists but route is facade-backed.' }],
    limitations: ['Veterinary data is privacy-scoped and not shown by default.'],
  },
  {
    id: 'approvals',
    path: '/approvals',
    label: 'Approvals',
    navigationGroup: 'Governance',
    iconKey: 'approval',
    requiredPermission: frontendRoutePermissionRegistry.approvals,
    requiredRoles: 'authenticated',
    supportStatus: 'live-api',
    dataSource: 'Central approval records and approval request routes.',
    backendPaths: backendContractPathsForRoute('approvals'),
    sharedTypes: ['ApprovalDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/approvals.ts', summary: 'Centralized approval service is implemented in memory.' }],
    limitations: ['Frontend may request approval only; it cannot authorize execution.'],
  },
  {
    id: 'incidents',
    path: '/incidents',
    label: 'Incidents',
    navigationGroup: 'Operations',
    iconKey: 'incident',
    requiredPermission: frontendRoutePermissionRegistry.incidents,
    requiredRoles: 'authenticated',
    supportStatus: 'facade-api',
    dataSource: 'Security operations and emergency operations workspaces.',
    backendPaths: backendContractPathsForRoute('incidents'),
    sharedTypes: ['SecurityOperationsDto', 'EmergencyOperationsDto'],
    databaseSupport: 'partial',
    evidence: [
      { source: 'backend-route', reference: 'apps/api/src/securityOps.ts', summary: 'Security incidents are backend-facade supported.' },
      { source: 'backend-route', reference: 'apps/api/src/emergencyOperations.ts', summary: 'Emergency operations workspace is generated from service-backed runtime data.' },
    ],
    limitations: ['Frontend has no direct emergency execution path; authorized humans retain emergency authority and AI may not block.'],
  },
  {
    id: 'compliance',
    path: '/compliance',
    label: 'Compliance',
    navigationGroup: 'Governance',
    iconKey: 'compliance',
    requiredPermission: frontendRoutePermissionRegistry.compliance,
    requiredRoles: ['admin', 'compliance-officer', 'read-only-auditor'],
    supportStatus: 'facade-api',
    dataSource: 'Compliance control library readiness metadata.',
    backendPaths: backendContractPathsForRoute('compliance'),
    sharedTypes: ['ComplianceControlLibraryDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Compliance control-library route returns readiness mappings and certification-candidate metadata.' }],
    limitations: ['No external certification, audit opinion, or regulator approval is claimed.'],
  },
  {
    id: 'security',
    path: '/security',
    label: 'Security',
    navigationGroup: 'Operations',
    iconKey: 'security',
    requiredPermission: frontendRoutePermissionRegistry.security,
    requiredRoles: ['admin', 'security', 'compliance-officer'],
    supportStatus: 'facade-api',
    dataSource: 'Security operations workspace.',
    backendPaths: backendContractPathsForRoute('security'),
    sharedTypes: ['SecurityOperationsDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/securityOps.ts', summary: 'Security workspace route is active.' }],
    limitations: ['Sensitive fields must stay role-filtered at backend boundary.'],
  },
  {
    id: 'facilities',
    path: '/facilities',
    label: 'Facilities',
    navigationGroup: 'Operations',
    iconKey: 'facility',
    requiredPermission: frontendRoutePermissionRegistry.facilities,
    requiredRoles: 'authenticated',
    supportStatus: 'live-api',
    dataSource: 'Facilities maintenance service backed by RACR assets, inspections, work orders, approvals, audit, events, and Digital Twin health.',
    backendPaths: backendContractPathsForRoute('facilities'),
    sharedTypes: ['FacilitiesMaintenanceWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [
      { source: 'backend-route', reference: 'apps/api/src/facilitiesMaintenance.ts', summary: 'Facilities workspace is generated by FacilitiesMaintenanceService.' },
      { source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Runtime API state seeds service-backed facilities assets, inspections, work orders, and approvals.' },
    ],
    limitations: ['Current implementation is in-memory; return-to-service and safety-critical maintenance actions remain approval-gated.'],
  },
  {
    id: 'ticketing',
    path: '/ticketing',
    label: 'Ticketing',
    navigationGroup: 'Enterprise',
    iconKey: 'ticket',
    requiredPermission: frontendRoutePermissionRegistry.ticketing,
    requiredRoles: ['admin', 'ticketing-manager'],
    supportStatus: 'facade-api',
    dataSource: 'Finance ticketing service state with active tickets, revenue summary, and payment control boundaries.',
    backendPaths: backendContractPathsForRoute('ticketing'),
    sharedTypes: ['FinanceTicketingWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/services/financeService.ts', summary: 'Ticketing workspace is generated from FinanceService ticket state.' }],
    limitations: ['No sales execution, payment capture, or attendee identity mutation is exposed from the frontend.'],
  },
  {
    id: 'finance',
    path: '/finance',
    label: 'Finance',
    navigationGroup: 'Enterprise',
    iconKey: 'finance',
    requiredPermission: frontendRoutePermissionRegistry.finance,
    requiredRoles: ['admin', 'finance'],
    supportStatus: 'facade-api',
    dataSource: 'Finance service read model for ticket revenue and protected payout approval posture.',
    backendPaths: backendContractPathsForRoute('finance'),
    sharedTypes: ['FinanceTicketingWorkspaceDto', 'ProtectedAction'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/services/financeService.ts', summary: 'Finance payout release is protected by the approval gateway.' }],
    limitations: ['Payouts are protected actions and cannot execute from the UI.'],
  },
  {
    id: 'federation',
    path: '/federation',
    label: 'Federation',
    navigationGroup: 'Enterprise',
    iconKey: 'federation',
    requiredPermission: frontendRoutePermissionRegistry.federation,
    requiredRoles: ['admin', 'compliance-officer', 'read-only-auditor'],
    supportStatus: 'facade-api',
    dataSource: 'Aggregate-only federation workspace metadata.',
    backendPaths: backendContractPathsForRoute('federation'),
    sharedTypes: ['FederationWorkspaceDto'],
    databaseSupport: 'none',
    evidence: [{ source: 'shared-contract', reference: 'FederationWorkspaceDto', summary: 'Aggregate-only federation contract exists.' }],
    limitations: ['No raw cross-track data is exposed.'],
  },
  {
    id: 'dataHub',
    path: '/data-hub',
    label: 'Data Hub',
    navigationGroup: 'Enterprise',
    iconKey: 'data-hub',
    requiredPermission: frontendRoutePermissionRegistry.dataHub,
    requiredRoles: ['admin', 'compliance-officer', 'racing-secretary', 'read-only-auditor'],
    supportStatus: 'facade-api',
    dataSource: 'Racing Data API Hub readiness metadata.',
    backendPaths: backendContractPathsForRoute('dataHub'),
    sharedTypes: ['RacingDataWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Racing Data API Hub route returns provider readiness, lineage, quality, and export-control metadata.' }],
    limitations: ['Licensed provider readiness only; no scraping or live provider claim.'],
  },
  {
    id: 'audit',
    path: '/audit',
    label: 'Audit',
    navigationGroup: 'Governance',
    iconKey: 'audit',
    requiredPermission: frontendRoutePermissionRegistry.audit,
    requiredRoles: ['admin', 'compliance-officer', 'read-only-auditor'],
    supportStatus: 'live-api',
    dataSource: 'Audit event records and approval references.',
    backendPaths: backendContractPathsForRoute('audit'),
    sharedTypes: ['AuditEventDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/auditLog.ts', summary: 'Immutable audit facade is active in memory.' }],
    limitations: ['Hash integrity is reference-level until durable audit storage is wired.'],
  },
  {
    id: 'admin',
    path: '/admin',
    label: 'Admin',
    navigationGroup: 'Administration',
    iconKey: 'admin',
    requiredPermission: frontendRoutePermissionRegistry.admin,
    requiredRoles: ['admin'],
    supportStatus: 'facade-api',
    dataSource: 'Platform health facade with service, dependency, approval-engine, deployment, and frontend health signals.',
    backendPaths: backendContractPathsForRoute('admin'),
    sharedTypes: ['PlatformHealthWorkspaceDto'],
    databaseSupport: 'partial',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/platformObservability.ts', summary: 'Admin page reads platform health and dependency records.' }],
    limitations: ['No user, tenant provisioning, privileged elevation, or settings persistence route exists.'],
  },
  {
    id: 'settings',
    path: '/settings',
    label: 'Settings',
    navigationGroup: 'Administration',
    iconKey: 'settings',
    requiredPermission: frontendRoutePermissionRegistry.settings,
    requiredRoles: 'authenticated',
    supportStatus: 'facade-api',
    dataSource: 'AI control-plane policy route with protected actions, evidence requirements, and governance mappings.',
    backendPaths: backendContractPathsForRoute('settings'),
    sharedTypes: ['AIControlPlanePolicyDto'],
    databaseSupport: 'none',
    evidence: [{ source: 'backend-route', reference: 'apps/api/src/server.ts', summary: 'Settings reads AI control-plane policy metadata from the active API facade.' }],
    limitations: ['No model-serving switch, runtime policy mutation, secret management, or execution toggles.'],
  },
] as const satisfies readonly RouteSupportMetadata[];

export type AppRoute = typeof routes[number];

export const routeById = Object.fromEntries(routes.map((route) => [route.id, route])) as Record<AppRoute['id'], AppRoute>;
export const defaultRoute = routeById.dashboard;

export function resolveRoute(pathname: string): AppRoute {
  const normalized = pathname === '/' ? '/dashboard' : pathname.replace(/\/+$/, '') || '/dashboard';
  return routes.find((route) => route.path === normalized || normalized.startsWith(`${route.path}/`)) ?? defaultRoute;
}
