import type { ApprovalDto, AuditEventDto, TrackMapDto } from '../types.js';

export function StatusCard({ title, status, detail }: { title: string; status: string; detail: string }) { return <article tabIndex={0} aria-label={`${title}: ${status}`}><h3>{title}</h3><p><span aria-hidden="true">●</span> <strong>{status}</strong></p><p>{detail}</p></article>; }
export function KpiTile({ label, value, trend }: { label: string; value: string; trend: string }) { return <article aria-label={`${label} KPI`}><p>{label}</p><strong>{value}</strong><small>{trend}</small></article>; }
export function RiskBadge({ level }: { level: 'low' | 'medium' | 'high' | 'critical' }) { return <span aria-label={`Risk level ${level}`} data-risk={level}><span aria-hidden="true">◆</span> {level.toUpperCase()}</span>; }
export function ApprovalChip({ status }: { status: ApprovalDto['status'] }) { return <span aria-label={`Approval ${status}`}><span aria-hidden="true">●</span> {status}</span>; }
export function EventTimeline({ events }: { events: { time: string; label: string; tone: string }[] }) { return <ol aria-label="Event timeline">{events.map((event) => <li key={`${event.time}-${event.label}`}><time>{event.time}</time> <span aria-hidden="true">●</span> {event.label} ({event.tone})</li>)}</ol>; }
export function AuditEventRow({ event }: { event: AuditEventDto }) { return <article aria-label={`Audit event ${event.id}`}><strong>{event.type}</strong><p>{event.actor} → {event.subjectId}</p><code>{event.hash}</code></article>; }
export function AssetHealthIndicator({ status, label }: { status: string; label: string }) { return <span aria-label={`${label} health ${status}`}><span aria-hidden="true">●</span> {label}: {status}</span>; }
export function DigitalTwinRelationshipCard({ source, relationship, target }: { source: string; relationship: string; target: string }) { return <article aria-label="Digital Twin relationship"><h3>{source}</h3><p>{relationship}</p><strong>{target}</strong></article>; }
export function TrackMapPanel({ map }: { map: TrackMapDto }) { return <section aria-label="Track map panel"><h2>Track Map</h2>{map.sectors.map((sector) => <StatusCard key={sector.id} title={sector.name} status={sector.condition} detail={`${sector.startMeters}–${sector.endMeters} meters`} />)}</section>; }
export function SafetyCriticalActionButton({ approvalsSatisfied, backendLive, authenticated, children }: { approvalsSatisfied: boolean; backendLive: boolean; authenticated: boolean; children: React.ReactNode }) { const disabled = !(approvalsSatisfied && backendLive && authenticated); return <button type="button" disabled={disabled} aria-disabled={disabled} aria-describedby="safety-lock-reason">{children}</button>; }
